### ISSUE TITLE
Shutter assumes ~/.config/autostart/shutter.desktop is writable, fails to exit

### ISSUE THREAD

**Issue by Photon89** [shutter-project/shutter#162]
I've made a symlink ~/.config/autostart/shutter.desktop -> /usr/share/applications/shutter.desktop

Trying to close shutter produces:
*** unhandled exception in callback:
***   Permission denied at /usr/share/shutter/resources/modules/Shutter/App/Autostart.pm line 59.
***  ignoring at /usr/bin/shutter line 2884.

Shutter is unresponsive thereafter, need to resort to SIGKILL.

Replacing the symlink with a copy fixes the issue.

Shutter should fail gracefully in such a case and exit normally.

Launchpad Details: [#LP1418162](https://bugs.launchpad.net/bugs/1418162) Mindaugas Jakutis - 2015-02-04 18:26:13 +0000

**Comment by yorik** [comment]
I have similar issue. Are there anyway to prevent shutter from trying to creating ~/.config/autostart/shutter.desktop ?
