### ISSUE TITLE
Shutter does not scale on a HiDPI screen

### ISSUE THREAD

**Issue by Photon89** [shutter-project/shutter#167]
$ rpm -q shutter
shutter-0.93-1.fc21.noarch

On Fedora 21, shutter does not scale toolbar icons in the image editor, causing the icons to be very small and almost unusable. This is on a laptop that has a HiDPI screen, in Gnome 3.14 using 2x scaling.

Launchpad Details: [#LP1434044](https://bugs.launchpad.net/bugs/1434044) cwawak - 2015-03-19 11:47:52 +0000

**Comment by Photon89** [comment]
This also happens in Ubuntu 15.04 on Unity using 2x scaling.

Launchpad Details: [#LPC](https://bugs.launchpad.net/shutter/+bug/1434044/comments/1) Mike Alesso - 2015-05-29 18:18:56 +0000

**Comment by Photon89** [comment]
Attachment: [shutter_editor.png](https://api.launchpad.net/1.0/shutter/+bug/1434044/+attachment/4576644/data)

This also happens on Ubuntu 14.04.4 LTS with shutter 0.90.1-0ubuntu1.1 and 2x scaling.

See attached screenshot.



Launchpad Details: [#LPC](https://bugs.launchpad.net/shutter/+bug/1434044/comments/2) Tobias Suchy - 2016-02-20 16:42:57 +0000

**Comment by Photon89** [comment]
Still no support for HiDPI? 
It is painful to work on a 4k display...

Launchpad Details: [#LPC](https://bugs.launchpad.net/shutter/+bug/1434044/comments/3) althalus1969 - 2016-10-20 12:14:48 +0000

**Comment by Photon89** [comment]
Also affecting Mint Linux 18 using Cinnamon desktop.

Launchpad Details: [#LPC](https://bugs.launchpad.net/shutter/+bug/1434044/comments/4) risingfish - 2016-12-27 23:12:01 +0000

**Comment by Photon89** [comment]
I should note the current version I have installed is 0.93.1.

Launchpad Details: [#LPC](https://bugs.launchpad.net/shutter/+bug/1434044/comments/5) risingfish - 2016-12-27 23:13:38 +0000

**Comment by Photon89** [comment]
Attachment: [Selection_004.png](https://api.launchpad.net/1.0/shutter/+bug/1434044/+attachment/4797352/data)

Screen cap in Mint Linux 18 and Cinnamon.

Launchpad Details: [#LPC](https://bugs.launchpad.net/shutter/+bug/1434044/comments/6) risingfish - 2016-12-27 23:18:10 +0000

**Comment by Photon89** [comment]
Someone fix it please! 

Launchpad Details: [#LPC](https://bugs.launchpad.net/shutter/+bug/1434044/comments/7) Ivanov Sergey - 2017-08-21 17:44:52 +0000

**Comment by Photon89** [comment]
Should be fixed after the GTK3 merge.

**Comment by Flimm** [comment]
I can confirm that the new version of Shutter works well on HiDPI. Thank you!
