### ISSUE TITLE
Missing way to autocapture of the selection without pressing "enter"

### ISSUE THREAD

**Issue by Photon89** [shutter-project/shutter#183]
I have two laptops here with two different Shutter versions where the new one is missing a cool feature...

Version 0.87.3, running on RHEL 6.6 with compz 0.8.2
- When selection capture was called a cross appeared to select a segment to be captured. Once selected the capture is performed immediately. This was cool for a "rapid-capture" where one just needed to take several selection screens in a row.

In version 0.93.1, running on Fedora 22 with Mate-Compiz desktop 1.10.2 and compiz 0.8.8
- When selection capture is called, then whole screen is greyed and cross appears for the selection. Once selected it does not take the capture automatically but waiting for "enter" to be pressed. On the one side it allows to move/change the selection before taking a screen-shots but on other side it is breaking the rapid capturing.

Could you please add a function to the shutter which will allows taking a selection screenshot without the need of pressing the <enter>? Thanks!

Launchpad Details: [#LP1494700](https://bugs.launchpad.net/bugs/1494700) HolyK - 2015-09-11 10:45:10 +0000

**Comment by ezyang** [comment]
Fixed in https://github.com/shutter-project/shutter/pull/610

**Comment by Photon89** [comment]
Right, this is a duplicate of #590 then!
