### ISSUE TITLE
The snap in 20.04 only allows selection and desktop

### ISSUE THREAD

**Issue by Photon89** [shutter-project/shutter#278]
Any other option under "new" causes the app to crash, the three dot icon in the title bar to disappear, and the app to be unusable for a period of time. This is version 0.94.3 rev 1306.  I am using Ubuntu focal 20.04. I have three machines with similar setups and all have the same problem.

Launchpad Details: [#LP1881678](https://bugs.launchpad.net/bugs/1881678) Rob Ball - 2020-06-01 23:18:26 +0000

**Comment by Photon89** [comment]
Seems like an issue with the snap packaging. Please report the bug here: https://github.com/popey/shutter-snap/issues 

Launchpad Details: [#LPC](https://bugs.launchpad.net/shutter/+bug/1881678/comments/1) Michael Kogan - 2020-06-02 04:50:45 +0000

**Comment by Photon89** [comment]
Closing as the bug is already reported downstream. Please report a new bug in case it turns out that this is not a snap issue.

**Comment by Flimm** [comment]
It looks like the snap package has been deleted, since this link gives a 404 error: https://snapcraft.io/install/shutter

**Comment by Photon89** [comment]
Well, the old snap package wasn't working properly anyway, so we remain with no (working) snap package. Contributions are welcome though!
