### ISSUE TITLE
"Open with..." functionality is broken

### ISSUE THREAD

**Issue by Photon89** [shutter-project/shutter#286]
"Open with..." function is broken with

```
*** unhandled exception in callback:
***   need an array ref to convert to GList at /usr/bin/shutter line 6852.
***  ignoring at /usr/bin/shutter line 2838.
```
at r1447.

**Comment by DarthGandalf** [comment]
What version? There is no r1447 in git world.

**Comment by Photon89** [comment]
Latest as of now (https://github.com/shutter-project/shutter/commit/fcca997f142868124d0a8cc04872762cb7b55190) But it was there prior to commit https://github.com/DarthGandalf/shutter/commit/a72b684c71e74aa9eeb0d7b93ae7f056087e31c1 already.

**Comment by DarthGandalf** [comment]
Works for me

**Comment by Photon89** [comment]
I tested on two machines, both show the error... Maybe I am missing some new dependency? I added perl-glib-object-introspection and perl-number-bytes-human, maybe there is something else?

**Comment by DarthGandalf** [comment]
Is there a version which is working? Could you try bisecting? (`git bisect`)

**Comment by Photon89** [comment]
Sure, I will bisect and report back!

**Comment by Photon89** [comment]
I did some kind of a manual bisect:

r1393 277755dd83e781e2fdadbfb1931bf0b84645455f OK
r1404 c3826cf4816871c8e7d377464a7f4be4cfafa266 NOT STARTING
r1405 ed6e055016ec3ed0e2151c61f5e28ee092cab9e9 NOT STARTING
r1420 d0aca4c4736377d72afe33628bf5b0c54c073d1b NOT STARTING
r1424 3659ddde7e6bb8b4cf8b11987a1dbe20b47125cc NOT STARTING
r1425 6aa6e3347887f8619383032905a64f12df651de0 BROKEN

The commits between c3826cf4816871c8e7d377464a7f4be4cfafa266 and 3659ddde7e6bb8b4cf8b11987a1dbe20b47125cc are not starting due to the Glib::IO dependency which I didn't yet figure out where to get from. Commit 6aa6e3347887f8619383032905a64f12df651de0 is the first one to start but shows the buggy behaviour. Last commit working is 277755dd83e781e2fdadbfb1931bf0b84645455f There were commits between 277755dd83e781e2fdadbfb1931bf0b84645455f and c3826cf4816871c8e7d377464a7f4be4cfafa266 which were made in the "novfs" branch but this branch is gone now.

If this doesn't help, I will read into how to do a proper bisect (didn't do yet because I use a PKGBUILD to check out different commits).

**Comment by DarthGandalf** [comment]
`Glib::Object::Introspection->setup(...)` is the only thing Glib::IO does: https://metacpan.org/release/Glib-IO/source/lib/Glib/IO.pm
I replaced `use Glib::IO` with the `setup()` call directly. You can install it though if it makes it any easier to bisect.

**Comment by DarthGandalf** [comment]
`git bisect` can go through branches to point out the exact commit.

**Comment by Photon89** [comment]
Sorry for the delay. Packaged a few perl modules for Arch to be able to test some commits. git bisect reports

```
6755806dcc72d1fd3cdfaf9bb603ed0bb2b97c9d is the first bad commit
commit 6755806dcc72d1fd3cdfaf9bb603ed0bb2b97c9d
Author: Dominique Dumont <dod@debian.org>
Date:   Sun Mar 25 20:59:08 2018 +0200

    use MIME::Detect instead of VFS mime ...
    
    work in progress...

 bin/shutter | 34 +++++++++++++++++++++-------------
 1 file changed, 21 insertions(+), 13 deletions(-)
```

edit: The error output at this commit (with correct line numbers) is

```
GLib-CRITICAL **: Source ID 31 was not found when attempting to remove it at ./bin/shutter line 7306.
*** unhandled exception in callback:
***   need an array ref to convert to GList at ./bin/shutter line 7130.
***  ignoring at ./bin/shutter line 2932.
```

**Comment by DarthGandalf** [comment]
I reproduced it. There are so many ways to open it with, and I was testing with two other which work.
