### ISSUE TITLE
Huge memory usage at startup when restoring there are lots of screenshots in history

### ISSUE THREAD

**Issue by fviard** [shutter-project/shutter#294]
(Probably partially related to the issues reported in #115 )

When starting shutter, memory usage can be huge when a lot of previous screenshots are still visible in the history.
For example, with around 300 existing previous screenshots, there could be ~2GB of RSS memory usage a few seconds after startup.

Interestingly, once the user change of tab in the main window, the RSS memory usage will drop to a stable low value ( ~150MB).

To be noted: I have a fix for this issue that will come with a PR soon.
(Might also reduce memory usage/leak for other operations at the same time)

Root cause:
Inside the "fct_update_tab" function, the "pixbuf" image content in full resolution is loaded without direct usage.
In fact, this operation is done just to be able to determine the dimensions of the real image for later usage.

So, for example at startup, the full image content (and not a thumbnail reduced size) will be loaded inside all the tabs, and so the memory usage will be huge.
But this is not needed as a thumbnail image content will be regenerated for each tab when we switch to it, and this will override the pixbuf for this tab.
(Also, the drop in memory usage when switching of tab comes from the fact that the tab_switching function will clear the pixbuf for all other tabs when switching to a specific tab).

**Comment by DarthGandalf** [comment]
If not for your mention of #115 I'd thought it's my fault, because I recently changed how thumbnails work, by using pixbuf directly instead of thumbnails (via `Gtk2::Gdk::Pixbuf->new_from_file_at_size`), when removing old dependency on Gnome2.

**Comment by fviard** [comment]
Don't worry, from what I can see, this is not related to that, and comes from code that is untouched for 8 years.
And in fact, it is not really related to the thumbnails themselves, but to the fact that the "preview" in each tab are loaded.

A little spoiler of what I modified is the following code:
```
 		#THUMBNAIL
 		#--------------------------------------
 		#maybe we have a pixbuf already (e.g. after taking a screenshot)
-		unless ($pixbuf) {
-			$pixbuf = $lp_ne->load($session_screens{$key}->{'long'}, undef, undef, undef, TRUE);
-			unless ($pixbuf) {
+		my ($im_format, $im_height, $im_width) = Gtk2::Gdk::Pixbuf->get_file_info($session_screens{$key}->{'long'});
+		unless ($im_format) {
...
-		$session_screens{$key}->{'image'}->set_pixbuf($pixbuf);
```

So, instead of loading the full image in the tab in advance, to later only use its dimensions, we can just directly use the get_file_info api of Gdk.
But, I'm still looking around my fix, because there are special case where we might still want to load the image here (ex.: undo/redo/monitor file changed ...)

**Comment by fviard** [comment]
In addition to the current issue, I noticed 2 unrelated memory leaks that I plan to open other issues for but that are a lot smaller:
1) (very small one), if i have hundred of tabs in the history, sometimes, when I switch through all of them, at some point there is a sudden little increase in memory.
But I'm not sure if it is related to particular files, or some race condition on the notebook_tab_switch or something else.

2) As reported by other, I noticed that when using the advanced select tool, there is a consequent memory leak with each new screenshot.
From what I see, it might just because a "screenshooter" is not "freed" a screenshot and stays associated with a screenshot for some reasons.
And, that could be ok if it was "cleaned" after usage and not keeping around a variable with its one pixbuf of the screen before screenshot or something like that.
The issue here is that it's not yet clear for me, but I think things from the screenshot or screenshooter could still be used at a later time for "save to clipboard" image or a redo operation.

**Comment by fviard** [comment]
I have opened the PR with the patch for this issue.

To be noted, there are a lot of memory leaks in shutter but still lighter than this issue.
I lost a lot of time investigating a few of them, but it looks like that nothing could be done, ugly hacks included, as they all look like to be coming from perl-gtk2 issues.

In my opinion, perl-gtk2 is not very serious as a binding...

FYI, a few of my findings, if either someone look at that in the future:
1) The ImageView leaks a lot when the "Selector" tool is attached to it.
> $self->{_selector} = Gtk2::ImageView::Tool::Selector->new($self->{_view});


It looks like that the selector is keeping multiple cache of the windows for his work, but they are not freed in the end.
If we try to clear the "pixbuf" of the ImageView with something like:
> ...view->set_pixbuf(undef)

This is useless, as in the selector tool code, nothing is done (including no clearing of buffer) if there is no pixbuf:

```
static void pixbuf_changed (GtkIImageTool *tool, gboolean       reset_fit, GdkRectangle  *rect)
...
GdkPixbuf *pixbuf = gtk_image_view_get_pixbuf (selector->view);
    if (!pixbuf)
        return;
...
```

So, the only way to reduce a little bit the memory usage is to replace the pixbuf with another one that is very small.

2) Gtk2 Cairo / Surface things do not look like to be freed when the perl objects are undef/destroyed...

**Comment by DarthGandalf** [comment]
Can you try the gtk3 branch? #284 
It's not fully working yet, but startup should already be there. Does it show the same leaks? You probably won't be able to use the selector feature of it yet though, as it currently uses some hacks specific to my machine

**Comment by DarthGandalf** [comment]
Ah, no, sorry, probably currently even startup there doesn't work without putting correct version of Gtk3::ImageView to the correct place

**Comment by fviard** [comment]
> Ah, no, sorry, probably currently even startup there doesn't work without putting correct version of Gtk3::ImageView to the correct place

If you can give me direction to do that, I might be able to give it a try.
(I'm on an ubuntu 18.08 btw)

For what I see in #284, you are trying to do your own reimplementation of ImageView directly in perl?

**Comment by DarthGandalf** [comment]
Something like that. Author of Gtk2::ImageView perl bindings implemented it, but considerably changed API in the process, I'm adapting it back.

1. Clone https://github.com/carygravel/gtk3-imageview locally
   * I *think* none of my PRs to it are required for the version of shutter I pushed to gtk3 branch so far.
2. Update `import lib "$shutter_root/gtk3-imageview-code/lib";` in bin/shutter to where you cloned it
3. Hope that it runs
