### ISSUE TITLE
Are you going to use Releases/Tags on GitHub?

### ISSUE THREAD

**Issue by 3ter** [shutter-project/shutter#296]
I'm looking forward to the move to `gtk3` and therefore wanted to watch the repo for new releases.
Are you going to update them in the wake of your [move from Launchpad to GitHub](https://bugs.launchpad.net/shutter/+bug/1885303/comments/2)?
Thanks!

**Comment by DarthGandalf** [comment]
gtk3 branch (#284) is not ready yet, so there's nothing there to release

**Comment by 3ter** [comment]
I didn't want to rush anything :slightly_smiling_face: 
I just wanted to ask if the team _intends_ on using the Releases/Tags in the (not too distant) future.

**Comment by vadi2** [comment]
Yes, of course

**Comment by 3ter** [comment]
Thanks for the confirmation!
