### ISSUE TITLE
Add a screen recording feature

### ISSUE THREAD

**Issue by Mingun** [shutter-project/shutter#298]
#### Description of requested feature:
First of all, the Shutter is the best screenshot tool I ever known. Thanks for it!

What do you think about adding a video recording capability?

#### Reasons for adding feature:
Sometimes static screenshots is not enougth and it will be viable to take things in actions :)

#### Extra information, such as Shutter version, operating system and ideas for how to implement:
Maybe this can be implemented as a plugin

**Comment by Photon89** [comment]
I think, this is out of scope for Shutter. I'd recommend SimpleScreenRecorder for this functionality, it works really great!
