### ISSUE TITLE
Can't locate Gnome2/Wnck.pm 

### ISSUE THREAD

**Issue by fu123456** [shutter-project/shutter#299]
#### Brief summary of issue

My system is Manjaro and i3wm (window manager). I run shutter from shell, but the terminal outputs
errors as follows:
```text
Can't locate Gnome2/Wnck.pm in @INC (you may need to install the Gnome2::Wnck module) (@INC contains: /usr/lib/perl5/5.32/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/5.32/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/5.32/core_perl /usr/share/perl5/core_perl) at /usr/bin/shutter line 38.
BEGIN failed--compilation aborted at /usr/bin/shutter line 38.
```
In addition, I install shutter by 'yaourt -Sy shutter', so I am sure that I use the latest shutter version.

**Comment by Photon89** [comment]
Probably a rebuild of some Perl modules is necessary after a Perl update, please follow the instructions in https://aur.archlinux.org/packages/shutter/#pinned-610441

**Comment by fu123456** [comment]
I follow the instruction according to your link (namely, Ralf_Mardorf commented on 2017-09-03 13:25). But I get the same error.

**Comment by Photon89** [comment]
Please post the current output of `pacman -Qqo '/usr/lib/perl5/vendor_perl'`.

**Comment by fu123456** [comment]
For my system, vendor_perl is in perl5/5.32 (or 5.30). So I run
```shell
pacman -Qqo '/usr/lib/perl5/5.32/vendor_perl'
```
It outputs:
```text
apparmor
cairo-perl
glib-perl
gnome-perl
gnome-vfs-perl
gnomecanvas-perl
graphicsmagick
graphviz
gtk2-perl
imagemagick
libproxy
net-snmp
pango-perl
perl-alien-build
perl-alien-libxml2
perl-canary-stability
perl-capture-tiny
perl-cgi
perl-clone
perl-common-sense
perl-cpanel-json-xs
perl-data-dump
perl-dbi
perl-encode-locale
perl-error
perl-extutils-depends
perl-extutils-pkgconfig
perl-ffi-checklib
perl-file-basedir
perl-file-copy-recursive
perl-file-desktopentry
perl-file-listing
perl-file-mimeinfo
perl-file-slurp-tiny
perl-file-which
perl-gtk2-unique
perl-html-form
perl-html-parser
perl-html-tagset
perl-http-cookies
perl-http-daemon
perl-http-date
perl-http-message
perl-http-negotiate
perl-io-html
perl-io-socket-ssl
perl-ipc-system-simple
perl-json-maybexs
perl-json-xs
perl-libwww
perl-locale-gettext
perl-log-message
perl-log-message-simple
perl-lwp-mediatypes
perl-lwp-protocol-https
perl-mailtools
perl-net-dbus
perl-net-http
perl-net-ssleay
perl-path-tiny
perl-proc-processtable
perl-proc-simple
perl-rename
perl-sgmls
perl-sort-naturally
perl-term-readline-gnu
perl-term-ui
perl-test-pod
perl-text-iconv
perl-timedate
perl-try-tiny
perl-types-serialiser
perl-uri
perl-www-robotrules
perl-x11-protocol
perl-xml-libxml
perl-xml-parser
perl-xml-simple
perl-xml-twig
perl-xml-writer
subversion
```
In addition, If I run
```shell
 pacman -Qqo '/usr/lib/perl5/5.30/vendor_perl'
```
It outputs:
```text
perl-gnome2-wnck
perl-goo-canvas
perl-gtk2-imageview
```.

**Comment by Photon89** [comment]
There, you have it! ;) You still need to rebuild perl-gnome2-wnck (and the other two packages in the output for the 5.30 directory). Sometimes you need to rebuild the packages in a specific order (any package after its dependencies if both the package and its dependencies need a rebuild).

**Comment by fu123456** [comment]
I run the following command:
```shell
   pacman -Qqo '/usr/lib/perl5/5.32/vendor_perl' | xargs pacaur -Syu --rebuild
   pacman -Qqo '/usr/lib/perl5/5.30/vendor_perl' | xargs pacaur -Syu --rebuild
```
But the terminal outputs the same error.

**Comment by Photon89** [comment]
I don't know about how pacaur handles it, in yay you can choose to clean build an AUR package. Also, you don't need to rebuild the packages which are already built against 5.32, only the 5.30 ones. Maybe go through the packages one by one (since there are only three of them) and make sure that they are actually rebuilt.

**Comment by fu123456** [comment]
Until now, I still cannot solve this problem. I very like this software.

**Comment by Photon89** [comment]
Unfortunately, I don't know how pacaur handles clean building packages. But if you want to use yay for this particular issue: Do a

`yay -S perl-gnome2-wnck`

and when yay asks you whether you want to clean build it, answer yes. If everythinng worked out, Shutter's error message should change.

**Comment by Photon89** [comment]
Should be not relevant for version 0.96 since most Perl dependencies from the AUR (including perl-gnome2-wnck) have been dropped. Feel free to file a new report if the problem persists.
