### ISSUE TITLE
Any plan to support LTS of Ubuntu/Debian ?

### ISSUE THREAD

**Issue by vrkansagara** [shutter-project/shutter#300]
Any plan to support LTS of Ubuntu/Debian ?

**Comment by Photon89** [comment]
See https://github.com/shutter-project/shutter/issues/285.

**Comment by Photon89** [comment]
The unofficial linuxuprising PPA has been updated to Ubuntu 20.10 shipping Shutter 0.95: https://www.linuxuprising.com/2018/10/shutter-removed-from-ubuntu-1810-and.html
