### ISSUE TITLE
So happy to see this project on the move again!

### ISSUE THREAD

**Issue by joaoherberto** [shutter-project/shutter#304]
I cannot tell you how happy I am to see this project being continued! 
I would like to financially support this project, do you have a link?

I use Arch and Manjaro...would like to see this project move out of the AUR for sure.

Joao

**Comment by vadi2** [comment]
We're good, but if anything https://github.com/DarthGandalf might want to setup sponsorship because he's done a lot of work to make it move again :)

**Comment by Photon89** [comment]
AUR package maintainer here: I think, we will be able to move out of the AUR, as soon as the GTK3 branch is merged, which  is, however, currently blocked by upstream: https://github.com/shutter-project/shutter/pull/284#issuecomment-761534348

**Comment by DarthGandalf** [comment]
Hm, ok, let's see how this works.

One cost which I can think of is the domain name. Who's paying for it?

**Comment by joaoherberto** [comment]
Where can I send $20 US ?

**Comment by Photon89** [comment]
> One cost which I can think of is the domain name. Who's paying for it?

Vadim, I think.

**Comment by vadi2** [comment]
Yes that would be me. That said there's now a `sponrsor` on https://github.com/shutter-project/shutter:

![image](https://user-images.githubusercontent.com/110988/106860640-f41b8700-66c4-11eb-8648-d93beeb338b2.png)

So send your improvements that way :)
