### ISSUE TITLE
Web site URL links and copyright

### ISSUE THREAD

**Issue by Ricky-Tigg** [shutter-project/shutter#306]
**OS**:Fedora; **Shutter**  v.0.94.3;; **Build Date** : Thu 30 Jul 2020.

- Official web site is served as **HTTPS**. Thought in the application and package related to it, it is referred to as served as HTTP. Since the HTTP URL is redirected to an HTTPS URL. it is worth to be referred as so.

$ rpm -qi shutter | sed -n 15p
URL         : http://shutter-project.org

![Shutter_v 0 94 3_URL_links](https://user-images.githubusercontent.com/26058215/107195051-84293b80-69f9-11eb-809b-c0e9f578e718.png)

- **Copyright** of version 0.95 would be likely **© 2008–2021.**

**Comment by Photon89** [comment]
Fixed in 0.96.
