### ISSUE TITLE
Capture timer delay ignored in 0.95-1.

### ISSUE THREAD

**Issue by guigirl42** [shutter-project/shutter#309]
[Shutter_system_info+terminal_transcript.zip](https://github.com/shutter-project/shutter/files/6081696/Shutter_system_info%2Bterminal_transcript.zip)

#### Brief summary of issue
Even with capture timer delay to any non-zero value, Shutter **instantly** changes to the capture mode, thus ignoring the user setting & acting if value was still zero seconds. Older versions before 0.95-1 worked correctly.

#### Steps to reproduce the issue
1. Launch Shutter
2. Adjust its capture timer delay to any non-zero value, either via _Preferences_, or GUI bottom rhs corner
3. Initiate capture
4. Observe that Shutter **instantly** changes to the capture mode, thus ignoring the user setting & acting if value was still zero seconds.

#### Error output
See attached text file.

#### Extra information, such as Shutter version, operating system and ideas for how to solve:
See attached text file.

**Comment by Photon89** [comment]
I can't reproduce this. Could you please move ~/.shutter and check if the problem persists?

**Comment by guigirl42** [comment]
Hi, thanks for responding. Do you mean that the timer _does_ in fact work correctly for you? Oh dear, then i wonder what's wrong here...

When you say `move ~/.shutter`, are you basically meaning for me to remove my shutter config file/s, in case they're corrupted & causing my problem?
***
\
Oh dear, i must sincerely apologise to you -- my OP is simply incorrect! You can close this invalid ticket.

I began using Shutter several years ago, but a couple of years ago i abandoned it once its dependency hell became too much to manage. Until you recently released your new updated version, based on the newer libraries, i had been using alternatives [KSnip, Flameshot] & it seems in me getting used to them i must have forgotten the finer points of using Shutter [re the timer]. In doing further testing here following your reply, i realised i had been using the timer function incorrectly, & in fact i should have been using the menu/tooltip capture for what i was trying to do. Once i stopped trying the standard capture [with timer] & instead used the menu capture, i was indeed able to capture the cascading menu that i  needed.

Summary: There's nothing wrong with Shutter, it was entirely my error. I'm terribly sorry.

**Comment by vadi2** [comment]
No worries, thanks for reporting anyway - and enjoy the app!
