### ISSUE TITLE
annotation

### ISSUE THREAD

**Issue by relogi** [shutter-project/shutter#310]
It looks like I have to open a 3rd party tool (GIMP) to annotate... is that true or am i missing something

**Comment by DarthGandalf** [comment]
There is a Drawing Tool button in top right corner

пн, 8 мар. 2021 г. в 21:25, reagan Gibbs <notifications@github.com>:

**Comment by Photon89** [comment]
In case, it is greyed out you are missing some of the optional dependencies.

**Comment by relogi** [comment]
Got it... thanks...You guys are too kind, Yes i was missing the obvious... plz Stop wasting your time with me.... i think i was looking solely for the word "annotate" and just missed the drawing tool because it didn't begin with "a"... oof... going to go sleep now....
rG
