### ISSUE TITLE
libunique no longer in AUR.

### ISSUE THREAD

**Issue by guigirl42** [shutter-project/shutter#312]
Hello. 

Recently i realised that `libunique` is no longer in the AUR [nor the main repos, of course]. It's a dependency for `perl-gtk2-unique`, which in turn is a dependency for `shutter`.

Can you advise if there is any action i should perform re ongoing system maintenance here? Each time now i interact with _pacman_ or _kalu_ i am reminded of this issue, & i'm unsure how to resolve it. I expect that sooner or later some routine system update will break _shutter_ such that i need to rebuild it, but in that case, afaik, it will fail due to that unmet dependency...?

Thanks.

**Comment by Photon89** [comment]
I will take care of this in one week, please ignore the warning for now.

**Comment by Photon89** [comment]
In the mean time the maintainer of perl-gtk2-unique posted that he has a libunique PKGBUILD ready to go but cannot push it so far: https://aur.archlinux.org/packages/perl-gtk2-unique/#comment-798552 So I guess, there is not much we can do other than wait.

**Comment by Photon89** [comment]
Seems like the problem takes longer to solve than expected. In the mean time a libunique package can be downloaded from https://archive.archlinux.org/packages/l/libunique/

**Comment by Photon89** [comment]
Version 0.96 dropped the libunique dependency, closing.
