### ISSUE TITLE
CPU 100% after deleting images

### ISSUE THREAD

**Issue by yiideveloper** [shutter-project/shutter#320]
#### Brief summary of issue

 high CPU load  after moving images... Only killing process will help....

#### Steps to reproduce the issue

1. Do screenshots (in my case was 4 screenshots). Do not close shutter window and images in shutter window!
2. Open file manager (for ex. Dolphin) 
3. Rename and move screenshots-images to other folder
4. notice the high CPU load (for ex. in htop)

#### Extra information, such as Shutter version, operating system and ideas for how to solve:
Shutter 0.94.3
Rev.1306
Distributor ID:	Neon
Description:	KDE neon User Edition 5.21
Release:	20.04
Codename:	focal

**Comment by Photon89** [comment]
Possibly related: https://github.com/shutter-project/shutter/issues/273 and https://github.com/shutter-project/shutter/issues/220

**Comment by Photon89** [comment]
I cannot reproduce it anymore in 0.96. Please file a new report in case the issue is still present!
