### ISSUE TITLE
Toile-libre upload broken 

### ISSUE THREAD

**Issue by kcdtv** [shutter-project/shutter#323]
#### Brief summary of issue

upload to toile-libre gives back blank results
#### Steps to reproduce the issue

1. Take a screenshot
2. click on the option to upload it
3. choose toile-libre as a server

#### Error output
all links are blank (null)

#### Extra information, such as Shutter version, operating system and ideas for how to solve:
shutter 0.95 installed through linux-uprising ppa on ubuntu 20.04, kernel 5.4.0-66-generic

**Comment by Photon89** [comment]
I think, the service is down:
![Auswahl_062](https://user-images.githubusercontent.com/1191480/116289655-f60c5800-a792-11eb-92d2-b1bafdedd62c.png)

Question is, is this permanent? In this case, we should drop the upload plugin, I guess.

**Comment by kcdtv** [comment]
Thanks for your answer, i will send them a mail to ask and tell you. Framasoft projects are great, hopefully it is temporary....
_update_  
I could get some answer in their IRC canal
```
[10:16] <kcdtv> savez vous si le service d'upload d'images toile-libre est définitivement abandonné?
[10:17] <kcdtv> ou l'arrêt est temporaire?
[10:17] <kaos> C'est temporaire mais peut-être long
```
The service will be back but it might take some time. 
I would be personally very happy if you **don't** eliminate it.
I will keep an eye on this issue and tell you when something change. 
Cheers and thank you for giving us the best tool ever for making and editing screenshots. :smiley_cat:

**Comment by Photon89** [comment]
Thanks, my French is extremely poor, so I wouldn't have asked myself. :smile:

**Comment by Photon89** [comment]
Looks like the service is back online, but Shutter's upload is indeed broken:

```
Use of uninitialized value $ARGV[0] in exists at /usr/share/shutter/resources/system/upload_plugins/upload/ToileLibre.pm line 50.
	require ToileLibre.pm called at /usr/sbin/shutter line 10321
	eval {...} called at /usr/sbin/shutter line 10319
	Shutter::App::dlg_upload("[1] - Auswahl_10-07-2021_12:41:27.png") called at /usr/sbin/shutter line 6560
	Shutter::App::fct_upload(Gtk3::MenuToolButton=HASH(0x55abaa032e38)) called at /usr/lib/perl5/5.34/vendor_perl/Glib/Object/Introspection.pm line 67
	eval {...} called at /usr/lib/perl5/5.34/vendor_perl/Glib/Object/Introspection.pm line 67
	Glib::Object::Introspection::__ANON__(Shutter::App=HASH(0x55aba9b044f0)) called at /usr/sbin/shutter line 10832
*** unhandled exception in callback:
***   undefined value for mandatory argument 'text' encountered at /usr/share/shutter/resources/modules/Shutter/Upload/Shared.pm line 95.
***   	Shutter::Upload::Shared::create_entry_for_notebook(ToileLibre=HASH(0x55abaa4fe150), "direct_link", undef, Gtk3::SizeGroup=HASH(0x55abaafb24e0)) called at /usr/share/shutter/resources/modules/Shutter/Upload/Shared.pm line 71
***   	Shutter::Upload::Shared::create_tab(ToileLibre=HASH(0x55abaa4fe150)) called at /usr/share/shutter/resources/modules/Shutter/Upload/Shared.pm line 155
***   	Shutter::Upload::Shared::show(ToileLibre=HASH(0x55abaa4fe150)) called at /usr/sbin/shutter line 10364
***   	Shutter::App::dlg_upload("[1] - Auswahl_10-07-2021_12:41:27.png") called at /usr/sbin/shutter line 6560
***   	Shutter::App::fct_upload(Gtk3::MenuToolButton=HASH(0x55abaa032e38)) called at /usr/lib/perl5/5.34/vendor_perl/Glib/Object/Introspection.pm line 67
***   	eval {...} called at /usr/lib/perl5/5.34/vendor_perl/Glib/Object/Introspection.pm line 67
***   	Glib::Object::Introspection::__ANON__(Shutter::App=HASH(0x55aba9b044f0)) called at /usr/sbin/shutter line 10832
***  ignoring at /usr/lib/perl5/5.34/vendor_perl/Glib/Object/Introspection.pm line 67.
 at /usr/sbin/shutter line 10832.

```

**Comment by Photon89** [comment]
Looks like the server is down again, I'm getting a 503 error. Is it still possible to contact them and ask about the current status?

**Comment by letompouce** [comment]
The Pix service continuous abuse led the team to disable upload. It is not expected to be enabled back in a (near) future.

The server being down from times to times is another story :-)

**Comment by Photon89** [comment]
I see, thanks for your reply! So I guess, we should remove the upload plugin for the time being.
