### ISSUE TITLE
We need to update the dependency information

### ISSUE THREAD

**Issue by Photon89** [shutter-project/shutter#327]
I am trying to run the latest commit after the #284 merge but am struggling to collect all the new dependencies. So far I found the following new dependencies (Arch style package names)

perl-carp-always
perl-gtk3
perl-gtk3-imageview (version 7 or later)
perl-readonly
perl-goocanvas2
perl-goocanvas2-cairotypes

I packaged perl-gtk3-imageview-8 and am now trying to package perl-goocanvas2-cairotypes. I am not sure about its dependencies though, it is supposed to fix things in perl-goocanvas2 but doesn't mention it as dependency at https://metacpan.org/pod/GooCanvas2::CairoTypes, is this supposed to be this way?

**Comment by Photon89** [comment]
I am having trouble to build perl-goocanvas2-cairotypes as it checks for goocanvas-2.0 while Arch Linux ships goocanvas-3.0 since mid of March and perl-goocanvas2 has also been built against goocanvas-3.0: https://projects.archlinux.de/svntogit/community.git/log/trunk/PKGBUILD?h=packages/perl-goocanvas2 Is it possible to update perl-goocanvas2-cairotypes for goocanvas-3.0 compatibility or should I package goocanvas-2.0?

**Comment by DarthGandalf** [comment]
> it is supposed to fix things in perl-goocanvas2 but doesn't mention it as dependency

Correct. It depends only on the C library, not on the perl bindings.
In fact, the dependency may be the reverse, if GooCanvas2.pm [ever starts](https://github.com/MaxPerl/perl-GooCanvas2/issues/1) "require"ing GooCanvas2::CairoTypes

**Comment by DarthGandalf** [comment]
> Is it possible to update perl-goocanvas2-cairotypes for goocanvas-3.0 compatibility or should I package goocanvas-2.0?

Does perl-goocanvas2 itself work with goocanvas-3.0?

**Comment by DarthGandalf** [comment]
I see... https://projects.archlinux.de/svntogit/community.git/commit/trunk/PKGBUILD?h=packages/perl-goocanvas2&id=18f64b84269d2eab6ad8005b5997fe22e1d691e5

**Comment by Photon89** [comment]
The sed line in the PKGBUILD looks somewhat hackish, but looks like it works with goocanvas-3.0 this way...

**Comment by DarthGandalf** [comment]
goocanvas-3 is not in Gentoo yet, and without testing I don't feel comfortable updating GooCanvas2::CairoTypes to use it.

Can you try adding a similar sed line to it?

**Comment by Photon89** [comment]
Works, thanks! Shutter starts and works, as far as I have tested so far! :smiley: 

What is the status of perl-gtk3-imageview? Should I report the -6 package in Arch Linux as outdated so the maintainers update it to -8, or is -8 to be considered experimental so I should put a separate PKGBUILD for it into the AUR?

**Comment by Photon89** [comment]
> goocanvas-3 is not in Gentoo yet, and without testing I don't feel comfortable updating GooCanvas2::CairoTypes to use it.

Is there something specific which I should test in Shutter (or in any other way) to check if GooCanvas2::CairoTypes works well with goocanvas-3?

**Comment by DarthGandalf** [comment]
> Should I report the -6 package in Arch Linux as outdated so the maintainers update it to -8

8 is good
6 doesn't have some features shutter needs in it

> Is there something specific which I should test in Shutter (or in any other way) to check if GooCanvas2::CairoTypes works well with goocanvas-3?

If shutter starts, doesn't throw any weird error, actually takes screenshots, and doesn't look too blurry when zooming, it works.

**Comment by Photon89** [comment]
> If shutter starts, doesn't throw any weird error, actually takes screenshots, and doesn't look too blurry when zooming, it works.

It works then, as far as I can tell!

> 8 is good

I will try to get it into Arch's repos then.

**Comment by Photon89** [comment]
> It works then, as far as I can tell!

After further testing, I noticed that there might be a problem, see attached screenshot. In the front, the file is opened in a viewer, in the back the same file is opened in Shutter. As you can see, the lines are not smooth in Shutter.

 
![Bildschirmfoto_2021-05-08_21-49-28](https://user-images.githubusercontent.com/1191480/117551631-63e43980-b047-11eb-9048-5fb935261757.png)

**Comment by DarthGandalf** [comment]
Can you share the file?

**Comment by Photon89** [comment]
Sure!

![Auswahl_075](https://user-images.githubusercontent.com/1191480/117559916-97e04e80-b089-11eb-8700-588807bd71bf.png)

**Comment by DarthGandalf** [comment]
This is on the increased zoom?

My suspicion is that it's because I had to replace [`GDK_INTERP_TILES`](https://developer.gnome.org/gdk-pixbuf/stable/gdk-pixbuf-Scaling.html#GdkInterpType) with [`CAIRO_FILTER_NEAREST`](https://www.cairographics.org/manual/cairo-cairo-pattern-t.html#cairo-filter-t) due to using the completely different GtkN::ImageView library, which uses Cairo directly to implement zoom

**Comment by DarthGandalf** [comment]
It may be possible to implement in Gtk3::ImageView something similar to what old gtk2-imageview did - resize the pixbuf using gdk, and cache it (because otherwise it's very slow), I just didn't bother with such caching

**Comment by DarthGandalf** [comment]
https://github.com/carygravel/gtk3-imageview/issues/22

**Comment by Photon89** [comment]
> This is on the increased zoom?

I guess, it is, so the comparison with the image shown in the viewer, which is at original size, is quite unfair. But when zooming in in the viewer and also in Shutter 0.95, the lines remain relatively smooth.

Also I noticed that directly after taking a screenshot it is shown at 100% scale, even if it doesn't fit the window. But after switching to a different tab and then back, it is scaled to fit the window size.

**Comment by DarthGandalf** [comment]
> in Shutter 0.95, the lines remain relatively smooth.

Because it uses a different interpolation method

**Comment by Photon89** [comment]
I see, thanks for the explanation!

> Also I noticed that directly after taking a screenshot it is shown at 100% scale, even if it doesn't fit the window. But after switching to a different tab and then back, it is scaled to fit the window size.

I now noticed that it is not centered as well, if it is smaller than the window size. But it gets centered, when clicking on it. For the big images clicking doesn't help since the image is being moved with the mouse, if it doesn't fit into the window.

**Comment by DarthGandalf** [comment]
Should work now

**Comment by Photon89** [comment]
Thanks, works!

**Comment by Photon89** [comment]
Updated dependency information is now on the website.

**Comment by Photon89** [comment]
@DarthGandalf  Did we possibly miss pango-perl as a new dependency?

**Comment by DarthGandalf** [comment]
@Photon89 anything to prove that? But that's possible

**Comment by Photon89** [comment]
It says

 ```
 at /usr/bin/shutter line 8997.
	Shutter::App::fct_init_depend() called at /usr/bin/shutter line 194
Useless use of hash element in void context at /usr/share/shutter/resources/modules/Shutter/App/Common.pm line 77.
	require Shutter/App/Common.pm called at /usr/bin/shutter line 205
Useless use of hash element in void context at /usr/share/shutter/resources/modules/Shutter/App/Common.pm line 80.
	require Shutter/App/Common.pm called at /usr/bin/shutter line 205
Can't locate Pango.pm in @INC (you may need to install the Pango module) (@INC contains: /usr/share/shutter/resources/modules /usr/lib/perl5/5.32/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/5.32/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/5.32/core_perl /usr/share/perl5/core_perl) at /usr/share/shutter/resources/modules/Shutter/App/ShutterNotification.pm line 36.
	Shutter::App::ShutterNotification::BEGIN() called at /usr/share/shutter/resources/modules/Shutter/App/ShutterNotification.pm line 36
	eval {...} called at /usr/share/shutter/resources/modules/Shutter/App/ShutterNotification.pm line 36
	require Shutter/App/ShutterNotification.pm called at /usr/bin/shutter line 214
BEGIN failed--compilation aborted at /usr/share/shutter/resources/modules/Shutter/App/ShutterNotification.pm line 36.
	require Shutter/App/ShutterNotification.pm called at /usr/bin/shutter line 214
Compilation failed in require at /usr/bin/shutter line 214.
```

**Comment by Photon89** [comment]
Thanks!

**Comment by lingfish** [comment]
> Updated dependency information is now on the website.

Hi @Photon89, where is this info?  I don't see Carp for example at https://shutter-project.org/downloads/dependencies/

**Comment by DarthGandalf** [comment]
That's because we've missed that new dep. Added, thanks.
