### ISSUE TITLE
No tray icon shown when a libappindicator tray is in use

### ISSUE THREAD

**Issue by Photon89** [shutter-project/shutter#331]
#### Brief summary of issue

When using the following extension, there is no tray icon in Shutter 0.96: https://extensions.gnome.org/extension/615/appindicator-support/

#### Error output

https://pastebin.com/raw/dMgLE43L

#### Extra information, such as Shutter version, operating system and ideas for how to solve:

The original report: http://disq.us/p/2h7xsr3

**Comment by Photon89** [comment]
@logix2 I installed Ubuntu Gnome 21.04 in a virtualbox to play around with it and reproduce the issue. What are my options to install the required dependencies in a possibly painless way in Ubuntu? :smile:

**Comment by DarthGandalf** [comment]
@logix2 hi, can you try this? I remember making this work with AppIndicator3, but results were less satisfactory than Gtk3::StatusIcon

```diff
diff --git a/bin/shutter b/bin/shutter
index 00c98e0e..3056a3c1 100755
--- a/bin/shutter
+++ b/bin/shutter
@@ -190,7 +190,7 @@ my $gnome_web_photo = TRUE;
 my $nautilus_sendto = TRUE;
 my $goocanvas       = TRUE;
 my $exiftool        = TRUE;
-my $appindicator    = FALSE; # Gtk3::StatusIcon works better albeit being deprecated in Gtk3
+my $appindicator    = TRUE; # Gtk3::StatusIcon works better albeit being deprecated in Gtk3
 fct_init_depend();
 
 #--------------------------------------
@@ -9005,8 +9005,8 @@ sub STARTUP {
 				version  => '0.1',
 				package  => 'AppIndicator',
 			);
-		} if 0;
-		if (0 && $@) {
+		};
+		if ($@) {
 			warn "WARNING: AppIndicator is missing --> there will be no icon showing up in the status bar when running Unity!\n\n";
 			$appindicator = FALSE;
 		}

```

**Comment by logix2** [comment]
@Photon89 you can install Shutter 0.96 on Ubuntu 21.04 by using this test PPA (the dependencies for the latest Shutter are also in there): https://launchpad.net/~linuxuprising/+archive/ubuntu/ppa

@DarthGandalf The patch and installing ``gir1.2-appindicator3-0.1`` got the tray icon / appindicator to work.

**Comment by Photon89** [comment]
@logix2 I'm fine if the problem is solved already. :smiley:

**Comment by DarthGandalf** [comment]
It's not "solved" yet. I'm trying to remember what was the exact issue with appindicator which caused me to disable appindicator support after updating it for gtk3 in favor of StatusIcon... And need to fix that issue.

**Comment by logix2** [comment]
@DarthGandalf right now the only difference I'm seeing is that the tray icon doesn't disappear when taking a screenshot (if I remember correctly, it was disappearing using the GTK2 Shutter), and that you can't select a profile from the tray Quick Profile Select menu. 

But then again, the profiles don't seem to work correctly in Shutter. If I save new profiles, they show up in Shutter (but not in the tray) until I close Shutter. When I re-launch it, the profiles are no longer displayed in Shutter. But if I try to save a profile with the name of an existing profile, it says that the profile already exists, so Shutter knows it's there, it just doesn't diplay it in the options.

**Comment by DarthGandalf** [comment]
@logix2 can you try this patch please? Instead of the patch above
And show the log of what it's saying in AAAAAAA line.
This requires package gir1.2-xapp-1.0


```diff
diff --git a/bin/shutter b/bin/shutter
index 16b7018f..1e298bc8 100755
--- a/bin/shutter
+++ b/bin/shutter
@@ -55,6 +55,11 @@ BEGIN {
 		version  => '3.0',
 		package  => 'Gtk3::GdkX11',
 	);
+	Glib::Object::Introspection->setup(
+		basename => 'XApp',
+		version  => '1.0',
+		package  => 'XApps',
+	);
 }
 
 package Shutter::App;
@@ -630,12 +635,25 @@ sub STARTUP {
 	#command line param set to disable tray icon?
 	unless ($sc->get_disable_systray) {
 
-		if ($appindicator) {
+			$tray = XApps::StatusIcon->new;
+			$tray->set_icon_name('shutter-panel');
+			$tray->set_secondary_menu($tray_menu);
+			$tray->{'hid'} = $tray->signal_connect('activate', sub {
+				evt_activate_systray_statusicon(@_);
+			});
+			$tray->set_visible(1);
+			Glib::Timeout->add(
+				500,
+				sub {
+					say "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA: " . $tray->get_state;
+					return FALSE;
+				});
+
+		if (0 && $appindicator) {
 			local $, = ' ';
 			$tray = AppIndicator::Indicator->new("Shutter", "shutter-panel", 'application-status');
 			$tray->set_menu($tray_menu);
 			$tray->set_status('active');
-		} else {
 				$tray = Gtk3::StatusIcon->new();
 
 				$tray->set_from_icon_name("shutter-panel");
```

The problem with libappindicator is that gnome developers made a design choice which I disagree with: left-click on the icon always shows the menu, and there's no way to attach a signal handler there to do anything else. XApps library fixes the StatusIcon deprecatedness in a different way, which supports left click.

See also: https://stackoverflow.com/questions/66162473/is-there-a-way-to-detect-a-mouse-click-with-pygtk-appindicator

Edit: I made a typo when extracting this patch from my repo

**Comment by DarthGandalf** [comment]
> But then again, the profiles don't seem to work correctly in Shutter

I never used that feature, and don't even know how it should work.

**Comment by DarthGandalf** [comment]
nevermind, xapps seems to be specific to mint, despite what they say in readme...

**Comment by Photon89** [comment]
@DarthGandalf Great that this is fixed! The fix doesn't require a new optional libappindicator dependency, does it?

**Comment by DarthGandalf** [comment]
It does, and it's optional. Without the dependency, some DEs just won't have the tray icon.

**Comment by Photon89** [comment]
Yep, this is what I observed now on my Ubuntu VM. I had to install gir1.2-appindicator3 (additionally to libappindicator3) to get a tray icon there. But I cannot find a corresponding package in Arch/Manjaro. Possibly this additional package is only necessary in Ubuntu and friends...
