### ISSUE TITLE
Selection do not work

### ISSUE THREAD

**Issue by danielczestki** [shutter-project/shutter#336]
#### Brief summary of issue
I want to create shot from Selection method. It does not work

#### Steps to reproduce the issue

1. Choice Selection
2. Draw rectangle
3. --nothing happend

#### Error output
nothing

**Comment by Photon89** [comment]
Please specify the Shutter version you are using.

**Comment by danielczestki** [comment]
0.96
Rev.1547

**Comment by danielczestki** [comment]
After I draw rectangle I need to hit enter key. Previous it shouts after releasing the mouse button

**Comment by Photon89** [comment]
This is the expected behavior, it was like this in previous versions as well. The only difference is that in previous versions the screen has been darkened while in the current version this is not the case.

**Comment by Photon89** [comment]
Closing as there has been no reply from OP for two months and it looks like it is not actually a bug.

Feel free to comment and reopen in case there is actually a problem. In version 0.98 it is again possible to trigger the screenshot with both the Enter key and a doubleclick again, btw.
