### ISSUE TITLE
Include cursor causing "call method "intersect" on unblessed reference"

### ISSUE THREAD

**Issue by egbuk** [shutter-project/shutter#337]
#### Brief summary of issue
When "Include cursor" preference is turned on, exception is thrown after selecting area for screenshot, then the application seems frozen.
#### Steps to reproduce the issue

1. Go to Edit->Preferences->Capture, check "Include cursor when taking a screenshot" checkbox
2. Take a screenshot, guaranteed reproduced with area select mode
3. See the freeze

#### Error output
`Using monitor: 0 - 0 - 2560 - 1440
*** unhandled exception in callback:
***   Can't call method "intersect" on unblessed reference at /usr/share/shutter/resources/modules/Shutter/Screenshot/Main.pm line 486.
***     Shutter::Screenshot::Main::include_cursor(Shutter::Screenshot::SelectorAdvanced=HASH(0x559d3ba018d0), 831, 390, 993, 642, Gtk3::GdkX11::X11Window=HASH(0x559d3ba0da50), Gtk3::Gdk::Pixbuf=HASH(0x559d3bf87890)) called at /usr/share/shutter/resources/modules/Shutter/Screenshot/SelectorAdvanced.pm line 1005`
#### Extra information, such as Shutter version, operating system and ideas for how to solve:
perl 5, version 32, subversion 1 (v5.32.1) built for x86_64-linux-thread-multi.
Shutter 0.96 Rev.1547
ManjaroLinux 21.0.5

**Comment by Photon89** [comment]
Confirmed.
