### ISSUE TITLE
Failed installs/updates

### ISSUE THREAD

**Issue by Berkmann18** [shutter-project/shutter#346]
#### Brief summary of issue
I tried updating `shutter` (even with the rebuild and re-install approached) but it relies on a version of `perl-gtk3-imageview` (being `v9`, but the latest version is `v6.1`).

#### Steps to reproduce the issue

1. `yay -S shutter` # doing `yay -S perl-gtk3-imageview` after/before a `yay -Syu` doesn't help.

#### Error output
```
 -> Could not find all required packages:
	perl-gtk3-imageview>=9 (Wanted by: shutter)
```

#### Extra information, such as Shutter version, operating system and ideas for how to solve:
I had `v0.95-2` and was going to update to the latest being `0.96-3`.

**Comment by Photon89** [comment]
Which distro are you using? Arch Linux ships perl-gtk3-imageview version 9, most probably distros like Manjaro will have a delay of a few days or weeks. I had a package especially for Shutter uploaded to the AUR (perl-gtk3-imageview-shutter) but got criticised and filed a deletion request as soon as version 9 hit the official Arch repos: https://bbs.archlinux.org/viewtopic.php?pid=1974352#p1974352 Just wait a bit, version 9 should arrive downstream pretty soon!

**Comment by Berkmann18** [comment]
Yes, ArchLinux and I thought, it wasn't installed (given how many times I got this error) but manually installing the dependency didn't help.

**Comment by Photon89** [comment]
According to https://archlinux.org/packages/community/any/perl-gtk3-imageview/ version 9 is in the repos for almost a week already. But I just checked my own Arch machine and also only see version 6. Most probably an out of date mirror...

**Comment by delinuxco** [comment]
Even after upgrading to perl-gtk3-imageview version 9, you may still need to rebuild some other perl packages
If you are using an Arch based system, then I recommend installing a little package called rebuild-detector from the AUR. (https://github.com/maximbaz/rebuild-detector)

Once installed run: `checkrebuild `if any packages need to be rebuilt, they will be listed.

The package has a nice hook that runs every time you run `yay` to check if any packages need to be rebuilt.

**Comment by Berkmann18** [comment]
@delinuxco Thanks for that, it seems it's no longer on the AUR (it 404s for me and `yay` can't find either `checkrebuild` or `rebuild-detector`).

**Comment by Photon89** [comment]
@Berkmann18 I don't have access to my Arch machine, but on my Manjaro machine perk-gtk3-imageview 9 is already in community/, so I'd suspect that it is in Arch as well. Is the initial issue fixed for you?

**Comment by Berkmann18** [comment]
@Photon89 I still get the same error output.
And whenever I do a package search I get:
```
community/perl-gtk3-imageview 6-1 [installed]
    Image viewer widget for Gtk3
```

**Comment by delinuxco** [comment]
@Berkmann18 You have to be having an internet issue, rebuild-detector is most definitely in the AUR.  If you are getting a 404 error, you have to have an issue with your internet from your machine because the AUR has not been down for weeks...

**Comment by Photon89** [comment]
@Berkmann18 Just to be very sure: You ran a `pacman -Syy` and the problem still persists?

**Comment by Berkmann18** [comment]
@delinuxco Internet issues? Nah, every other website, package downloads and stuff worked fine.
@Photon89 Yup.

**Comment by Photon89** [comment]
Which mirror server are you using? In the mean time, even Manjaro has the new version in its repos...

**Comment by Berkmann18** [comment]
@Photon89 
```
Server = http://mirrors.ukfast.co.uk/sites/archlinux.org/$repo/os/$arch
Server = http://mirror.bytemark.co.uk/archlinux/$repo/os/$arch
Server = https://mirrors.ukfast.co.uk/sites/archlinux.org/$repo/os/$arch
Server = https://mirror.bytemark.co.uk/archlinux/$repo/os/$arch
Server = http://mirrors.melbourne.co.uk/archlinux/$repo/os/$arch
Server = https://mirrors.melbourne.co.uk/archlinux/$repo/os/$arch
Server = https://mirror.netweaver.uk/archlinux/$repo/os/$arch
Server = http://www.mirrorservice.org/sites/ftp.archlinux.org/$repo/os/$arch
Server = https://www.mirrorservice.org/sites/ftp.archlinux.org/$repo/os/$arch
Server = https://archlinux.uk.mirror.allworldit.com/archlinux/$repo/os/$arch
Server = http://mirror.netweaver.uk/archlinux/$repo/os/$arch
Server = http://archlinux.mirrors.uk2.net/$repo/os/$arch
Server = http://mirrors.gethosted.online/archlinux/$repo/os/$arch
Server = https://mirrors.gethosted.online/archlinux/$repo/os/$arch
Server = http://mirrors.manchester.m247.com/arch-linux/$repo/os/$arch
Server = http://lon.mirror.rackspace.com/archlinux/$repo/os/$arch
Server = https://lon.mirror.rackspace.com/archlinux/$repo/os/$arch
Server = http://archlinux.uk.mirror.allworldit.com/archlinux/$repo/os/$arch
Server = http://arch.serverspace.co.uk/arch/$repo/os/$arch
```

**Comment by Photon89** [comment]
Ok, I have access to my Arch machine again and had the same issue there. It was a mirror issue, I updated the mirrorlist (using https://ostechnix.com/retrieve-latest-mirror-list-using-reflector-arch-linux/) and got a huge update. Also, perl-gtk3-imageview has version 9 now.

Btw. I got dependency problems with various lib32 packages during this update, so I had to enable the multilib repo in pacman.conf (no idea why it was disabled in the first place...).

**Comment by delinuxco** [comment]
@Photon89 Your system must be borked... I just check and rebuild-detector is most definitely there:  

```
1 community/rebuild-detector 4.1.6-1 (7.1 KiB 4.9 KiB) (Installed)
    Detects which packages need to be rebuild
==> Packages to install (eg: 1 2 3, 1-3 or ^4)
==> 
```

I have installed Shutter on my current machine, it just updated to 0.97 today.
I have also built the package for my Manjaro spin distro and it worked fine, there is something wrong with either your machine or your internet connection.

**Comment by Photon89** [comment]
@delinuxco In my case the problem was definitely an out of sync mirror, after regenerating the mirror list the problem was solved. I assume that OP has exactly the same problem.

**Comment by Berkmann18** [comment]
@Photon89 I did the same following that article which broke yay but I managed to fix it.
And then installing `shutter` worked although it doesn't show up in the menu yet but I guess the desktop entry hasn't been re-created yet.

**Comment by Photon89** [comment]
It should show up in the menu, actually. :smiley:

**Comment by Berkmann18** [comment]
@Photon89 It always did on AwesomeWM but not the night I re-installed it, but now it does.
