### ISSUE TITLE
Shutter stopped working after upgrading to Ubuntu 21.04

### ISSUE THREAD

**Issue by tannerli** [shutter-project/shutter#348]
#### Brief summary of issue
No method of screen-grabbing works as expected after my Ubuntu upgrade to 21.04 'Hirsute Hippo'

#### Steps to reproduce the issue
See writeup of issue over at [AskUbuntu](https://askubuntu.com/questions/1344236/shutter-screenshot-application-is-broken-since-upgrade-to-ubuntu-21-04-hirsute-h)

#### Extra information, such as Shutter version, operating system and ideas for how to solve:
v0.95 Rev.1450

**Comment by DarthGandalf** [comment]
Are you using Wayland? It's not supported yet

**Comment by tannerli** [comment]
Yes indeed I am. So the upgrade switched me around...  Thank you for pointing me to the cause of the issue

**Comment by DarthGandalf** [comment]
#187 is the tracking bug for it
