### ISSUE TITLE
How to drag/move the selection frame

### ISSUE THREAD

**Issue by hertzhaft** [shutter-project/shutter#350]
ArchLinux 5.12.9-arch1-1, Shutter 096 rev. 1547 (from ArchLinux package)

I frequently have to produce screenshots of a predefined size (like 400 x 400 pixel).
I have preset these dimensions in my settings/profile. The selection frame is shown accordingly.
How can I drag/move the frame to another position, keeping the size? Is there a key+mousedrag combination for this? 

Just clicking and dragging starts a new selection. Ctrl or Alt keys + drag are ignored.
Ctrl or Alt + arrow keys just moves the crosshair to a corner of the selection.

Shift opens a window where I can change the values manually, but doing so does not change the size/position of the selection.

BTW: Is there an overview of all mouse/keyboard shortcuts commands?

**Comment by Photon89** [comment]
Currently impossible, I guess.

**Comment by DarthGandalf** [comment]
Oh, I forgot about this feature when working on Gtk3 ImageView
