### ISSUE TITLE
Install fails due to invalid key on Linux Mint 20.1 

### ISSUE THREAD

**Issue by lmmentel** [shutter-project/shutter#351]
#### Brief summary of issue

I cannot install shutter due to invalid gpg keys.

#### Steps to reproduce the issue

Here are the steps I use to install 

```bash
sudo add-apt-repository ppa:linuxuprising/shutter
sudo apt-get update
sudo apt install shutter
```
#### Error output

```bash
W: GPG error: http://ppa.launchpad.net/linuxuprising/shutter/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EA8CACC073C3DB2A
E: The repository 'http://ppa.launchpad.net/linuxuprising/shutter/ubuntu focal InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

#### Extra information, such as Shutter version, operating system and ideas for how to solve:

OS: 

Distributor ID:	Linuxmint
Description:	Linux Mint 20.1
Release:	20.1
Codename:	ulyssa

```bash
uname -a
Linux  5.4.0-74-generic #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Photon89** [comment]
Possible workaround: https://askubuntu.com/questions/308760/w-gpg-error-http-ppa-launchpad-net-precise-release-the-following-signatures

@logix2 is the PPA's maintainer, maybe he can help.

**Comment by lmmentel** [comment]
Thanks @Photon89 the workaround worked fine!

**Comment by Photon89** [comment]
Great, closing then!
