### ISSUE TITLE
can't start shutter-0.96 on Fedora34 vmware guest system

### ISSUE THREAD

**Issue by martinkg** [shutter-project/shutter#354]
#### error message when starting shutter

(shutter:32685): Wnck-WARNING **: 09:23:27.951: libwnck is designed to work in X11 only, no valid display found
Can't call method "force_update" on an undefined value at ./shutter line 453, <DATA> line 19.
	Shutter::App::STARTUP(Shutter::App=HASH(0x55d5bdf468c8)) called at /usr/lib64/perl5/vendor_perl/Glib/Object/Introspection.pm line 67
	Glib::Object::Introspection::__ANON__(Shutter::App=HASH(0x55d5bdf468c8)) called at ./shutter line 10789
GLib-GObject-CRITICAL **: g_boxed_free: assertion 'boxed != NULL' failed, <DATA> line 19 during global destruction.
 at ./shutter line 0, <DATA> line 19.

error message when starting with GDK_BACKEND=x11 ./shutter

Can't use an undefined value as an ARRAY reference at ./shutter line 8271, <DATA> line 19.
	Shutter::App::fct_ret_window_menu() called at ./shutter line 8371
	Shutter::App::fct_ret_tray_menu() called at ./shutter line 457
	Shutter::App::STARTUP(Shutter::App=HASH(0x55f99768eef0)) called at /usr/lib64/perl5/vendor_perl/Glib/Object/Introspection.pm line 67
	Glib::Object::Introspection::__ANON__(Shutter::App=HASH(0x55f99768eef0)) called at ./shutter line 10789
GLib-GObject-CRITICAL **: g_boxed_free: assertion 'boxed != NULL' failed, <DATA> line 19 during global destruction.
 at ./shutter line 0, <DATA> line 19.
	eval {...} called at ./shutter line 0

shutter-0.96
Fedora 34

**Comment by DarthGandalf** [comment]
The startup issue is fixed in #344 but you won't be able to take screenshots on wayland until #187 is fixed

> GDK_BACKEND=x11 ./shutter

That won't help if X11 server is not in fact running; for that you need to relogin and select the X11 session instead of Wayland session. And then you won't need the GDK_BACKEND var.
