### ISSUE TITLE
Some toolbar icons too large if icon theme doesn't provide a small icon size

### ISSUE THREAD

**Issue by Photon89** [shutter-project/shutter#355]
#### Brief summary of issue

In my case the "Desktop" icon is very large and thus the whole panel has a large height. Icons should be scaled down to the intended size even if the icon theme doesn't provide a suiting icon size.

![Снимок экрана_2021-06-19_19-08-10](https://user-images.githubusercontent.com/1191480/122650180-b417e680-d131-11eb-9bc3-a750fa0d165f.png)

#### Steps to reproduce the issue

1. Use an outdated or broken icon theme like Faenza-Green: https://www.gnome-look.org/p/1012230
2. Launch Shutter version 0.96 or later (after GTK3 port)
3. Observe some of the icons being too large

#### Error output

Nothing specific

#### Extra information, such as Shutter version, operating system and ideas for how to solve:

Shutter 0.97, Manjaro Linux, faenza-green icon theme package.

**Comment by DarthGandalf** [comment]
Please fill the "Extra information, such as Shutter version, operating system " section

**Comment by Photon89** [comment]
Done!

**Comment by Photon89** [comment]
I tried to have a look into it. Looks like there is nothing Shutter could do about it, the icon theme just doesn't provide a sufficiently small version of the desktop icon and Shutter is the only app which uses the desktop icon, so the problem never got visible in the past. In the mean time the icon theme isn't even available from the AUR any more and I couldn't reproduce the issue with any other icon theme, so I'd rather close this one.
