### ISSUE TITLE
Tray icon patch from old Gentoo package

### ISSUE THREAD

**Issue by Photon89** [shutter-project/shutter#356]
The following has been discovered in the AUR package:

```
# Fix tray icon under many icon themes, from Gentoo
sed -e "/\$tray->set_from_icon_name/s:set_from_icon_name:set_from_file:" \
      -e "s:shutter-panel:/usr/share/icons/hicolor/scalable/apps/&.svg:" \
      -i bin/shutter
```

Is it something which isn't needed any more or should it be implemented into Shutter's code directly?

**Comment by DarthGandalf** [comment]
Gentoo doesn't have such patch. I don't know what's the purpose of it is.

**Comment by Photon89** [comment]
Never mind, this got clarified: https://bbs.archlinux.org/viewtopic.php?pid=1979079#p1979079

The patch is rather ancient, it was already there in Shutter's old official package 2017 or even earlier.
