### ISSUE TITLE
Second instance crashes when launched without an option

### ISSUE THREAD

**Issue by Photon89** [shutter-project/shutter#357]
#### Brief summary of issue

When one instance is already running and a second instance is launched with just `shutter`, it fails to start. The main window of the running instance should be showed instead.

#### Steps to reproduce the issue

1. Launch Shutter
2. Launch another instance from command line with `shutter`
3. Observe the crash

#### Error output

`GLib-CRITICAL **: g_variant_new_array: assertion 'n_children > 0 || child_type != NULL' failed at /usr/sbin/shutter line 10902.`

#### Extra information, such as Shutter version, operating system and ideas for how to solve:

Shutter 0.97, Arch Linux. Probably it happened when moving away from libunique.

**Comment by DarthGandalf** [comment]
It's not actually a crash.  Glib is very annoying and shows these CRITICAL warnings all over the place.

Shutter just sees that an instance is running already, and happily shuts down. But I agree that showing the main window will be more intuitive.

**Comment by Photon89** [comment]
Thanks, works now!
