### ISSUE TITLE
Shutter package is not available in AUR for now

### ISSUE THREAD

**Issue by yell0w4x** [shutter-project/shutter#358]
https://aur.archlinux.org/packages/shutter

There is https://aur.archlinux.org/packages/shutter-git/ but anyway deps are not resolved...

**Comment by Photon89** [comment]
It is in the community repo now: https://archlinux.org/packages/community/any/shutter/ Probably derivative distros like Manjaro will take some time till the package will reach them, so for now shutter-git is the only option. Which dependency isn't being resolved for it?

**Comment by Yakkhini** [comment]
```
could not satisfy dependencies:
- unable to satisfy dependency 'perl-json-maybexs' required by shutter-git
- unable to satisfy dependency 'perl-goocanvas2-cairotypes' required by shutter-git
```

**Comment by Photon89** [comment]
Right, those are in the community repo as well and thus have been deleted from the AUR... I fear, there is nothing that can be done besides of waiting. I can post the PKGBUILDs of those packages here, if you want to build them via makepkg though.

**Comment by Photon89** [comment]
@yell0w4x @Yeyuehuke Which distro are you guys using btw.?

**Comment by Yakkhini** [comment]
> @yell0w4x @Yeyuehuke Which distro are you guys using btw.?

I'm using manjaro 🐝

**Comment by Photon89** [comment]
I requested to accelerate the process of importing Shutter to the Manjaro repos: https://forum.manjaro.org/t/update-requests-for-packages-imported-from-arch-linux/493/123

**Comment by delinuxco** [comment]
In the interim, package files can be found here for 0.97: https://repo.delinuxco.com/repository/delinuxco/x86_64/

**Comment by Photon89** [comment]
@yell0w4x @Yeyuehuke: Shutter reached stable today in Manjaro, could you guys confirm?

**Comment by delinuxco** [comment]
I refreshed the databases and search for Shutter, not showing up yet.

**Comment by Photon89** [comment]
@delinuxco Weird, it is there on my end, also should be there according to https://manjaro.org/branch-compare/?query=shutter Maybe an out of sync mirror?

**Comment by delinuxco** [comment]
No, I still don't see it. even tried switching to worlwide mirrors using 'yay', but the package being available there does not mean that it has been added to the .db file. As I understand it, the packages are made available in the repository first, then the repo database files are generated. So it may be waiting for the new db file to be generated before it shows up on any package manager.

**Comment by Photon89** [comment]
Is this something mirror specific? As I said it works for my mirror: 

```
$ yay shutter
4 aur/flash-screen-git 0.1.0.0.r0.g7dcc0ec-1 (+0 0.00) 
    Flashes the screen and emits a shutter sound
3 aur/shutter-git r1548.85dc91e8-5 (+2 0.46) 
    A featureful screenshot tool, git version
2 aur/shutter-encoder 15.2-1 (+3 1.13) 
    Converter for all formats video|audio|image professionnals codecs and standards - swiss knife tool for Linux
1 community/shutter 0.97-2 (1.5 MiB 16.9 MiB) (Installed)
    The feature-rich screenshot tool
==> Packages to install (eg: 1 2 3, 1-3 or ^4)
==> 

```

**Comment by delinuxco** [comment]
I just tried it again and it is there now!  odd... I am in Portugal but I had switched to the US mirrors first, then to worldwide and still nothing. now it just shows up.

**Comment by Photon89** [comment]
Great! I'm closing here then, but of course the issue is still open to further comments in case there are still some problems left.
