### ISSUE TITLE
Doubleclick for initiating a screenshot in selection mode stopped working in recent Shutter version(s)

### ISSUE THREAD

**Issue by Photon89** [shutter-project/shutter#359]
#### Brief summary of issue

Just got the following via the website's contact form:

> since Version 0.97 double click doesn't work when selecting a selection. Can you fix this? Thank you

> I used before the Update a double klick with left left mouse button to take  a screen shot after selecting an area

I assume that in versions prior to 0,96 the doubleclick was an alternative to the enter key for initiating the screenshot, but this alternative isn't present any more after the GTK3 merge.

#### Steps to reproduce the issue

1.  Launch the selection mode
2.  Select an area to take a screenshot
3.  Try to initiate the screenshot with a doubleclick

#### Error output

Nothing specific.

#### Extra information, such as Shutter version, operating system and ideas for how to solve:

Shutter 0.97, most probably also 0.96.

**Comment by DarthGandalf** [comment]
I didn't even know there is such feature... I always used Enter key for it

**Comment by Photon89** [comment]
Same here! But looks like some people did use it...

**Comment by blazendic** [comment]
wow :O I didn't even know that it was possible with "Enter" :rofl: 

From the first time I've used Shutter, I always used it with double click.
Luckily I've came here to check if someone has reported this issue.

**Comment by GrzegorzPawlowski-TomTom** [comment]
I observe the same problem in version 0.97.

**Comment by DarthGandalf** [comment]
> I observe the same problem in version 0.97.

Well, yes, since I didn't know about this feature, I missed it while reimplementing some parts of shutter for gtk3

**Comment by jcro21** [comment]
I also used this feature heavily; Means you don't have to have a hand on the keyboard! Just double-click after you release the mouse button (to set the selection area).

Is there an intention to reimplement this?

_As an aside, I've been using this gem of an application for several years - really appreciate those who've contributed to making it so great! :heart:_

**Comment by DarthGandalf** [comment]
> Is there an intention to reimplement this?

Sure. This is the main regression of 0.96 not fixed yet.

**Comment by mvivarelli** [comment]
Hi, just to point out that this function is needed when you take a screenshot of an RDP or virtual machine window, because the enter key get grabbed by the window itself.
In the mean time is it possible to reinstall 0.96 version in Ubuntu 20.04 or newer?
I searched but I wasn't able to do that
Thank's
Maurizio

**Comment by Photon89** [comment]
@mvivarelli I fear you would need 0.95 which still has most of the GTK2 dependencies.

**Comment by mvivarelli** [comment]
First of all thank's Michael for giving new life to this software that I really like.
Said that with this problem I need a temporary solution (my screenshot are mainly of VM's or RDP windows)
Is it possible to find a compiled version 0.95 for Ubuntu 20.04
Thank's
Maurizio

**Comment by Photon89** [comment]
All the credits go to @DarthGandalf :smiley: 

There are 0.95 packages in the Linuxuprising PPA but not for 20.04: https://launchpad.net/%7Elinuxuprising/+archive/ubuntu/shutter/+index?batch=75&memo=75&start=75 You can just download the 0.95 tarball from https://github.com/shutter-project/shutter/releases/tag/v0.95 and install it using "make install", it will uninstall cleanly with "make uninstall", so it's not that of an issue installing it past the package manager.

**Comment by mvivarelli** [comment]
It works
Thank's
Maurizio
-----Original Message-----From: Michael Kogan ***@***.***
>Reply-To: shutter-project/shutter <
***@***.***>To:
shutter-project/shutter ***@***.***>Cc: mvivarelli <
***@***.***>, Mention ***@***.***>Subject: Re:
[shutter-project/shutter] Doubleclick for initiating a screenshot in
selection mode stopped working in recent Shutter version(s) (#359)Date:
Tue, 20 Jul 2021 07:33:35 -0700

All the credits go to @DarthGandalf 😃
There are 0.95 packages in the Linuxuprising PPA but not for 20.04: 
https://launchpad.net/%7Elinuxuprising/+archive/ubuntu/shutter/+index?batch=75&memo=75&start=75
You can just download the 0.95 tarball and install it using "make
install", it will uninstall cleanly with "make uninstall", so it's not
that of an issue installing it past the package manager.

**Comment by Photon89** [comment]
Great, you're welcome!

**Comment by ak2766** [comment]
Might I add that when Shutter is configured to minimize to try on close, clicking the Shutter icon in the Gnome Dash does nothing.  Previously, it would open the main window.  It would be good to get functionality back as well.

I'm on a fully patched Ubuntu 20.04.2 LTS desktop.

**Comment by Photon89** [comment]
@ak2766 Please open a new issue about this problem. Though I fear that there won't be a fix any time soon since this seems to be the way how libappindicator works in Gnome (I might be wrong though)...

**Comment by ak2766** [comment]
Alright.  No worries - will do so right away.

**Comment by umeli** [comment]
> Hi, just to point out that this function is needed when you take a screenshot of an RDP or virtual machine window, because the enter key get grabbed by the window itself.
> In the mean time is it possible to reinstall 0.96 version in Ubuntu 20.04 or newer?
> I searched but I wasn't able to do that
> Thank's
> Maurizio

As a workaround hit the VM's escape key before you hit enter... for vm-ware it's CTRL-ALT then Enter....

**Comment by mvivarelli** [comment]
Thank's Urs, 
but I successfully installed 0.95 version following Michael directions
Can you forecast when the fix will be available?
Regards
Maurizio
-----Original Message-----From: Urs Meli ***@***.***>Repl
y-To: shutter-project/shutter <
***@***.***>To:
shutter-project/shutter ***@***.***>Cc: mvivarelli <
***@***.***>, Mention ***@***.***>Subject: Re:
[shutter-project/shutter] Doubleclick for initiating a screenshot in
selection mode stopped working in recent Shutter version(s) (#359)Date:
Wed, 28 Jul 2021 00:23:01 -0700

> Hi, just to point out that this function is needed when you take a
> screenshot of an RDP or virtual machine window, because the enter key
> get grabbed by the window itself.
> 
> In the mean time is it possible to reinstall 0.96 version in Ubuntu
> 20.04 or newer?
> 
> I searched but I wasn't able to do that
> 
> Thank's
> 
> Maurizio

As a workaround hit the VM's escape key before you hit enter... for vm-
ware it's CTRL-ALT then Enter....

**Comment by Photon89** [comment]
> Can you forecast when the fix will be available?

I guess, as soon as @DarthGandalf, our only developer, finds time to deal with it. :wink:  But it looks like the most pressing issue currently, as quite many people seem to be affected by it.

**Comment by mvivarelli** [comment]
ok
Thank's
-----Original Message-----From: Michael Kogan ***@***.***
>Reply-To: shutter-project/shutter <
***@***.***>To:
shutter-project/shutter ***@***.***>Cc: mvivarelli <
***@***.***>, Mention ***@***.***>Subject: Re:
[shutter-project/shutter] Doubleclick for initiating a screenshot in
selection mode stopped working in recent Shutter version(s) (#359)Date:
Wed, 28 Jul 2021 06:06:21 -0700
