### ISSUE TITLE
Shutter v 0.97 Rev: 1549

### ISSUE THREAD

**Issue by GrahamLees** [shutter-project/shutter#361]
#### Brief summary of issue

ubuntu 20.04.2 Shutter icon not loading in system tray

#### Steps to reproduce the issue

1. occurred since update a few days ago. Shutter not loading on startup and even when started does not appear in system tray.
2. OTOH I have the same version/Revision installed on scratch PC running ubuntu MATE 21.04 and it performs as expected
3. 

#### Error output
There is no error output.

#### Extra information, such as Shutter version, operating system and ideas for how to solve:
v 0.97 Rev: 1549 ubuntu 20.04.2 LTS

**Comment by Photon89** [comment]
Please see https://github.com/shutter-project/shutter/issues/331 and https://github.com/linuxmint/xapp/issues/137 I'm not sure but possibly the icon can be brought back by installing libappindicator.

**Comment by jcro21** [comment]
I solved this in my case (Ubuntu 21.04) by installing gir1.2-appindicator3.

Ensure you have appindicator up to date:
```bash
sudo apt update
sudo apt install gnome-shell-extension-appindicator
```

Then install gir1.2-appindicator3:
```bash
sudo apt install gir1.2-appindicator3-0.1
```

**Comment by DarthGandalf** [comment]
Thanks, I've updated the website to mention this dep.

**Comment by Photon89** [comment]
Reported downstream in Arch: https://bugs.archlinux.org/task/71502
