### ISSUE TITLE
Shutter icon is missing in task bar (Ubuntu Mate LTS 20.04) since last update (97)

### ISSUE THREAD

**Issue by arnoxz** [shutter-project/shutter#363]
#### Brief summary of issue
Icon in task bar (ubuntu mate LTS 20.04) is now appearing as a red circle (icon missing ?)

#### Steps to reproduce the issue

1. Start the tool and observe the task bar
2. 
3. 

#### Error output
no real error, more aspect and look of the tool

#### Extra information, such as Shutter version, operating system and ideas for how to solve:
it appears since last update to release 97
shutter/focal,focal,now 0.97-1~ 0linuxuprising1 ~focal1 all  [installé]
OS : Ubuntu Mate 20.04 LTS
![ShutterIcone](https://user-images.githubusercontent.com/87417965/125594437-a297c87b-3116-4bf1-8c98-b3ca96896f6b.jpg)
-Perhaps the solution, would target the path to the icon (if icon exists ?)

**Comment by Mpc46** [comment]
### No Icon at all on tray :Y
![image](https://user-images.githubusercontent.com/43671013/125985677-69060370-9fd6-491b-8f97-5158438ddcaf.png)

### MY everyday struggle:
![image](https://user-images.githubusercontent.com/43671013/125986312-f4bdbe8c-7bec-4cdb-82cc-ee87ac2a2f4e.png)

My settings:
![image](https://user-images.githubusercontent.com/43671013/125986110-de20a564-e115-4059-aa7e-ec3a07d5ab60.png)

**Comment by DarthGandalf** [comment]
@Mpc46 this is different from @arnoxz issue. Please don't post unrelated reports together

**Comment by Mpc46** [comment]
> @Mpc46 this is different from @arnoxz issue. Please don't post unrelated reports together

Im really sick :'v and I mistake this post with mine :v sorry :c

**Comment by Photon89** [comment]
@arnoxz Does the problem persist if you change the icon theme?

**Comment by Photon89** [comment]
@arnoxz I just installed Ubuntu Mate 20.04 in a VM and cannot reproduce the issue, neither on a clean install nor after running all the updates. 

Does the problem persist if you switch to a different icon theme? 

Does a 

`gtk-update-icon-cache`

help?

**Comment by arnoxz** [comment]
Hello,
thanks for your replies,...
Good, if I switch to another theme (out from Ambiant-Mate, Mate..), the icon is back (ex : Menta, GreenLaguna,... = ok).
It seems to be the source of the problem.
However I do not want to change all my environment icon/theme to another, is there a way to copy the shutter-icon under the Ambiant-Mate folder (if it works that way ?) 

Overview of the icon shutter named : 
`arnoxz@MED-E15302:/usr/share/icons$ find . -type f -iname "*shutter*" -exec ls -ltr {} \;
-rw-r--r-- 1 root root 18131 jui  6 10:23 ./HighContrast/scalable/apps/shutter.svg
-rw-r--r-- 1 root root 18131 jui  6 10:23 ./HighContrast/scalable/apps/shutter-panel.svg
-rw-r--r-- 1 root root 1957 jui  6 10:23 ./hicolor/32x32/apps/shutter.png
-rw-r--r-- 1 root root 2794 jui  6 10:23 ./hicolor/48x48/apps/shutter.png
-rw-r--r-- 1 root root 1001 jui  6 10:23 ./hicolor/22x22/apps/shutter.png
-rw-r--r-- 1 root root 1001 jui  6 10:23 ./hicolor/22x22/apps/shutter-panel.png
-rw-r--r-- 1 root root 4880 jui  6 10:23 ./hicolor/72x72/apps/shutter.png
-rw-r--r-- 1 root root 1615 jui  6 10:23 ./hicolor/24x24/apps/shutter.png
-rw-r--r-- 1 root root 1615 jui  6 10:23 ./hicolor/24x24/apps/shutter-panel.png
-rw-r--r-- 1 root root 354230 jui  6 10:23 ./hicolor/scalable/apps/shutter.svg
-rw-r--r-- 1 root root 354230 jui  6 10:23 ./hicolor/scalable/apps/shutter-panel.svg
-rw-r--r-- 1 root root 7093 jui  6 10:23 ./hicolor/96x96/apps/shutter.png
-rw-r--r-- 1 root root 4155 jui  6 10:23 ./hicolor/64x64/apps/shutter.png
-rw-r--r-- 1 root root 10519 jui  6 10:23 ./hicolor/128x128/apps/shutter.png
-rw-r--r-- 1 root root 1950 jui  6 10:23 ./hicolor/36x36/apps/shutter.png
-rw-r--r-- 1 root root 26828 jui  6 10:23 ./hicolor/256x256/apps/shutter.png
-rw-r--r-- 1 root root 17929 jui  6 10:23 ./hicolor/192x192/apps/shutter.png
-rw-r--r-- 1 root root 685 jui  6 10:23 ./hicolor/16x16/apps/shutter.png
-rw-r--r-- 1 root root 685 jui  6 10:23 ./hicolor/16x16/apps/shutter-panel.png
`

But no shutter-icon under Ambiant-Mate directory (if this comment make sense ? :-) )
`arnoxz@MED-E15302:/usr/share/icons/Radiant-MATE$ find . -type f -iname "*shutter*" -exec ls -ltr {} \;
arnoxz@MED-E15302:/usr/share/icons/Radiant-MATE$ ls
actions    animations    apps    categories    devices    icon-theme.cache  mimes    places    status    stock
actions@2  animations@2  apps@2  categories@2  devices@2  index.theme       mimes@2  places@2  status@2  stock@2
arnoxz@MED-E15302:/usr/share/icons/Radiant-MATE$ `

any idea for action / resolution ? Thanks

**Comment by arnoxz** [comment]
> gtk-update-icon-cache
does not make any differnce

--> switching theme resolve the problem, but I do want keep the Ambient-Mate look - !! ? any chance to adjust it to that theme ?

**Comment by Photon89** [comment]
I cannot reproduce the issue with this theme for some reason: 
![-shutter_001](https://user-images.githubusercontent.com/1191480/127872365-b9c9a474-8e44-4132-a96c-c52be9526b10.png)

**Comment by arnoxz** [comment]
I whish I had the same :-)

If you browse and try to find shutter icon to following subfolder, do you point out some shutter icon for the theme ?

What do you have under /usr/share/icons/Radiant-MATE/ ?

with this command
 find . -type f -iname "*shutter*" -exec ls -ltr {} \;

any shutter icon present ?

how did you install shutter ? PPA ? which one ?

**Comment by Photon89** [comment]
Linuxuprising PPA, currently at version 0.97 (latest available).

Actually, as far as I understand, Shutter should use its own icon if the theme doesn't provide one, which is at `/usr/share/icons/hicolor/scalable/apps/shutter-panel.svg` and `/usr/share/icons/hicolor/SIZE/apps/shutter-panel.png`, see https://github.com/shutter-project/shutter/tree/master/share/icons/hicolor

edit: Ambiant-MATE and Radiant-MATE don't provide this icon in my case as well, but the default one which is supplied by Shutter itself is used.

edit 2: What if you download the source tarball, extract it somewhere and launch Shutter from the ./bin directory? It should then use the icons in the extracted folder.

edit 3: Possibly the terminal output from Shutter launch will shed some light on why the default icon cannot be loaded.

**Comment by arnoxz** [comment]
ok same install and since version 0.97 icon disapeared

I got the point ok for icon location, they exists

>edit1 : not my case :-(
>edit2 : I will try in a soon (tarball) and come back to tell what happen
>edit3 : good idea, and yes I got multiple errors/warning at launch in terminal, i copy here just the part related to icon, does this means something can be made to resolve ? :-)

--> 
``
INFO: gathering system information...
Linux MED-E15302 5.4.0-80-generic #90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 20.04.2 LTS \n \l
Glib 1.3292 
Gtk3 0.037 
Glib built for 2.63.5, running with 2.64.6

(shutter:2807): Gtk-WARNING **: 21:55:32.455: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
LOG **: Name com.canonical.AppMenu.Registrar does not exist on the session bus
 at /usr/bin/shutter line 5436, <DATA> line 19.
	Shutter::App::fct_update_gui() called at /usr/bin/shutter line 638
	Shutter::App::STARTUP(Shutter::App=HASH(0x55fc2c2fd718)) called at /usr/lib/x86_64-linux-gnu/perl5/5.30/Glib/Object/Introspection.pm line 67
	Glib::Object::Introspection::__ANON__(Shutter::App=HASH(0x55fc2c2fd718)) called at /usr/bin/shutter line 10832
``

**Comment by Photon89** [comment]
```
(shutter:2807): Gtk-WARNING **: 21:55:32.455: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
```

Great catch, I think, that's it! 

People advise to reinstall `libgdk-pixbuf-2.0-0` and/or `shared-mime-info`.

**Comment by arnoxz** [comment]
:-o mmmh, not yet....
Reinstalled both without expected result !
[EDIT] : I also purged / reinstalled shutter and redo the steps, still the same

**Comment by Photon89** [comment]
What about

`update-mime-database /usr/share/mime`

and 

`gdk-pixbuf-query-loaders --update-cache`

see https://bbs.archlinux.org/viewtopic.php?id=261143

**Comment by arnoxz** [comment]
update-mime... done -     :   still same result

gdk-pixbuf-query-loaders --update-cache    doesn't seem to be available on MATE ?

arnoxz@MED-E15302:/$ gdk-pixbuf-query-loaders --update-cache
gdk-pixbuf-query-loaders : commande introuvable


Available commands  (gdk-pixbuf...) are the 3 following cmd : 
arnoxz@MED-E15302:/$ gdk-pixbuf-
gdk-pixbuf-csource      gdk-pixbuf-pixdata      gdk-pixbuf-thumbnailer

**Comment by Photon89** [comment]
What's 

`stat -c '%a' /usr/share/mime/`

giving?

**Comment by arnoxz** [comment]
Gives : 
arnoxz@MED-E15302:~$ stat -c '%a' /usr/share/mime/
755

ahah ? should I change it to 644 ?

(btw thanks for all your answers :-) )

**Comment by Photon89** [comment]
First of all: I'm stupid, I didn't restart Shutter after switching the icon theme when testing on Ubuntu Mate. :facepalm: 

755 is not that bad, I think, I have the same on my Arch machine and have the tray icon, hover, not the default one but the one from my icon theme. Let me test again on Ubuntu Mate and report back in some minutes.

**Comment by Photon89** [comment]
So, I just retested, and I still do have an icon, even if I restart Shutter after changing the icon theme.

My permission is 755 as well.

Maybe we need it to be more verbose... Which output do you get from 

`update-mime-database -V /usr/share/mime`

?

**Comment by arnoxz** [comment]
arnoxz@MED-E15302:~$ update-mime-database -V /usr/share/mime
Updating MIME database in /usr/share/mime...

Parsing source file /usr/share/mime/packages/AdobeAIR.xml...
Parsing source file /usr/share/mime/packages/apt.xml...
Parsing source file /usr/share/mime/packages/brasero.xml...
Parsing source file /usr/share/mime/packages/caja.xml...
Parsing source file /usr/share/mime/packages/code-workspace.xml...
Parsing source file /usr/share/mime/packages/codeblocks.xml...
Parsing source file /usr/share/mime/packages/freedesktop.org.xml...
Parsing source file /usr/share/mime/packages/gcr-crypto-types.xml...
Parsing source file /usr/share/mime/packages/kde5.xml...
Parsing source file /usr/share/mime/packages/librecad.xml...
Parsing source file /usr/share/mime/packages/libreoffice.xml...
Parsing source file /usr/share/mime/packages/mate-theme-package.xml...
Parsing source file /usr/share/mime/packages/openshot-qt.xml...
Parsing source file /usr/share/mime/packages/quarry.xml...
Parsing source file /usr/share/mime/packages/remmina-mime.xml...
Parsing source file /usr/share/mime/packages/rstudio.xml...
Parsing source file /usr/share/mime/packages/scratch.xml...
Parsing source file /usr/share/mime/packages/scribus.xml...
Parsing source file /usr/share/mime/packages/sludge-engine.xml...
Parsing source file /usr/share/mime/packages/squeak-vm.xml...
Parsing source file /usr/share/mime/packages/winff-data.xml...
Parsing source file /usr/share/mime/packages/x-k3b.xml...
Parsing source file /usr/share/mime/packages/zoom.xml...
I/O error : Permission denied
I/O error : Permission denied
Failed to write XML file; For permission problems, try rerunning as root

**Comment by Photon89** [comment]
Ah, see, we forgot the "sudo", so that's why it had no effect! Please retry as

`sudo update-mime-database -V /usr/share/mime`

**Comment by arnoxz** [comment]
oops forgot sudo :-) 

arnoxz@MED-E15302:~$ sudo update-mime-database -V /usr/share/mime
[sudo] Mot de passe de arnoxz : 
Updating MIME database in /usr/share/mime...

Parsing source file /usr/share/mime/packages/AdobeAIR.xml...
Parsing source file /usr/share/mime/packages/apt.xml...
Parsing source file /usr/share/mime/packages/brasero.xml...
Parsing source file /usr/share/mime/packages/caja.xml...
Parsing source file /usr/share/mime/packages/code-workspace.xml...
Parsing source file /usr/share/mime/packages/codeblocks.xml...
Parsing source file /usr/share/mime/packages/freedesktop.org.xml...
Parsing source file /usr/share/mime/packages/gcr-crypto-types.xml...
Parsing source file /usr/share/mime/packages/kde5.xml...
Parsing source file /usr/share/mime/packages/librecad.xml...
Parsing source file /usr/share/mime/packages/libreoffice.xml...
Parsing source file /usr/share/mime/packages/mate-theme-package.xml...
Parsing source file /usr/share/mime/packages/openshot-qt.xml...
Parsing source file /usr/share/mime/packages/quarry.xml...
Parsing source file /usr/share/mime/packages/remmina-mime.xml...
Parsing source file /usr/share/mime/packages/rstudio.xml...
Parsing source file /usr/share/mime/packages/scratch.xml...
Parsing source file /usr/share/mime/packages/scribus.xml...
Parsing source file /usr/share/mime/packages/sludge-engine.xml...
Parsing source file /usr/share/mime/packages/squeak-vm.xml...
Parsing source file /usr/share/mime/packages/winff-data.xml...
Parsing source file /usr/share/mime/packages/x-k3b.xml...
Parsing source file /usr/share/mime/packages/zoom.xml...
Wrote 1239 strings at 2c - 6dfc
Wrote aliases at 6dfc - 7718
Wrote parents at 7718 - 9320
Wrote literal globs at 9320 - 9420
Wrote suffix globs at 9420 - 15b00
Wrote full globs at 15b00 - 15b58
Wrote magic at 15b58 - 23594
Wrote namespace list at 23594 - 236e8
Wrote icons list at 236e8 - 236fc
Wrote generic icons list at 236fc - 24348
Wrote types list at 24348 - 25144

**Comment by Photon89** [comment]
Ok, this looks good! If you restart Shutter, does it possibly have a proper tray icon now? :smiley:

**Comment by arnoxz** [comment]
not yet.... same for all sessions/user on the laptop

**Comment by Photon89** [comment]
Weird...

Could you please check if `libgdk-pixbuf2.0-bin` is installed? If not, install it and retry

`sudo gdk-pixbuf-query-loaders --update-cache`

**Comment by arnoxz** [comment]
It is installed -yes-, however the cmd is not called (commande introuvable = command not found) when I submit it.

Altough it could be found under /lib...
-rw-r--r-- 1 root root 975 fév 18 15:41 ./usr/share/man/man1/gdk-pixbuf-query-loaders.1.gz
-rwxr-xr-x 1 root root 13916 fév 18 15:41 ./usr/lib/i386-linux-gnu/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders
-rwxr-xr-x 1 root root 14656 fév 18 15:41 ./usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders

I then executed the cmd with the full path, nothing followed on screen, once shutter is launched the icon remain the same as before (fyi I am on 64bit, for sure = LTS20.04).

My steps action here next : 
arnoxz@MED-E15302:/$ 
arnoxz@MED-E15302:/$ sudo gdk-pixbuf-query-loaders --update-cache
sudo: gdk-pixbuf-query-loaders : commande introuvable
arnoxz@MED-E15302:/$ 
arnoxz@MED-E15302:/$ sudo /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders --update-cache
arnoxz@MED-E15302:/$ sudo /usr/lib/i386-linux-gnu/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders --update-cache
arnoxz@MED-E15302:/$

**Comment by Photon89** [comment]
I'm kind of out of ideas... Maybe people at https://askubuntu.com/ can give better input on this...

**Comment by arnoxz** [comment]
Thanks a lot, i do not know,...
I found something related to pixbuf, but not sure if I have to follow or if this is link to my problem...
https://github.com/aruiz/webp-pixbuf-loader/issues/9

thanks anyway, but this remain weird

**Comment by Photon89** [comment]
Well, the only relevant thing is that it confirms that gdk-pixbuf-query-loaders has been moved to /usr/lib/x86_64-linux-gnu/ and  /usr/lib/i386-linux-gnu/. But since running it didn't solve the icon problem, this isn't relevant any more...

**Comment by Photon89** [comment]
Another idea, what does `stat -c '%a' /usr/share/mime/icons` say?

**Comment by arnoxz** [comment]
ok let's go on further :-) 

arnoxz@MED-E15302:~$  stat -c '%a' /usr/share/mime/icons
644

**Comment by Photon89** [comment]
Ok, that looks good. I asked on askubuntu, let's see if somebody can give a hint: https://askubuntu.com/questions/1355710/shutter-shows-a-broken-icon-on-ubuntu-mate-20-04

**Comment by chelevich** [comment]
Looks fixed for me in the latest version 0.98 Rev. 1570
Ubuntu 20.04

**Comment by Photon89** [comment]
@chelevich Was it broken for you in 0.97 as well? I couldn't reproduce it neither in 0.97 nor in 0.98...

**Comment by chelevich** [comment]
@Photon89 yes, it was broken for me on previous version

**Comment by Photon89** [comment]
@arnoxz What does it look like for you in 0.98?

**Comment by arnoxz** [comment]
for me, completely opposite, it was fine up to 97, and since 98 I lost the icon

**Comment by DarthGandalf** [comment]
@arnoxz that contradicts your fist post here (the issue itself), which says it didn't work on 0.97

**Comment by Photon89** [comment]
I assume, it has worked up to 0.96 and broke in 0.97 and 0.98.

It would be interesting to downgrade to 0.96 and see if it solves the problem. I have the impression that the Shutter version doesn't matter at all, the problem just has been introduced by some other reason at the same time (during the same update) as Shutter got updated to 0.97.

**Comment by arnoxz** [comment]
> @DarthGandalf :  that contradicts your fist post here (the issue itself), which says it didn't work on 0.97

Yes you're right since my first post another release was triggered but did not solve the issue...
Correction : up to .096 included it was fine for me :-)

**Comment by DarthGandalf** [comment]
@arnoxz can you try downgrading and see if 0.96 still works?

**Comment by arnoxz** [comment]
> @DarthGandalf  can you try downgrading and see if 0.96 still works?

That would be great but have no idea how/where to do it ?!  could you tell me ? thanks (so far I used the PPA)

**Comment by Photon89** [comment]
@arnoxz You can download the tarball of any version at https://github.com/shutter-project/shutter/releases

Just unpack it and run Shutter from `bin/shutter`.

**Comment by arnoxz** [comment]
Thank you, I tried 0.96, but it is not better anymore, the icon remain ''red circle'' now !

**Comment by Photon89** [comment]
Very good, so we know for sure that it isn't a regression at least! 

I'd propose to examine the apt log and see which packages have been updated along Shutter around the time when the issue first appeared.

**Comment by arnoxz** [comment]
Gréat, my level isn't tough enough to find the accurate way to extract exactly what is necessary, could you please advise me which command line I should use to return the shutter log ?! thanks a lot for your time and help :-)

**Comment by Photon89** [comment]
Please just paste the content of `/var/log/apt/history.log` at https://pastebin.com/ and post the link to the paste!

**Comment by arnoxz** [comment]
here you are,... (not really old history log, hope this reveal something since ? thx)
https://pastebin.com/4NK8JH5L

**Comment by arnoxz** [comment]
I guess the log from july (shutter automatic update) might be more relevant ?
https://pastebin.com/PtEDevNG

**Comment by Photon89** [comment]
Right, that's August log, please do the same with the July log in `/var/log/apt/history.log.1.gz` It is a gzipped file, so you will need to first unpack it.

**Comment by arnoxz** [comment]
just done it at the same time you reply :-)  -the 2 logs july + august here above (link pastebin)

**Comment by Photon89** [comment]
Ok, I see, the July log is already there! 

On July 14th you posted the issue here, this is exactly the day when Shutter got updated to 0.97. The previous version was 0.94.3 and it has been installed on July 10th. There were no further updates between the two days. 

Is it true that Shutter has been first installed on July 10th, showed the icon correctly for four days and then broke with the update on July 14th?

**Comment by arnoxz** [comment]
Difficult to say : 
-I probably first time installed shutter (do not know which release perhaps 0.94) a year ago, about august 2020 - when I bought my new computer, it is one of the first app I always install,....
-I think the automatic update was on 10th (I can read a kind of mix in the log : shutter:amd64 (0.94.3-1~0linuxuprising1~focal1, 0.97-1~0linuxuprising1~focal1)).
-I probably reinstalled/purge shutter several time since and on the 14th to try to solve the icon problem (not sure but I think this is the real (hi)story) (?)....
-definitely the problem occurs at the automatic update of 0.97 around july

[EDIT] - I wanted to try to install the older release previous .094 - but aren"t available on the source link - oldest available is 95 (and can't be launched on my computer) :  https://github.com/shutter-project/shutter/releases

**Comment by Photon89** [comment]
So, the question is, if the problem first appeared on 14th with the 0.97 update and not on 10th already. If this is the case, we can rule out package updates as root of the problem, because there were none at this time besides of the Shutter update (and a Kazam installation which should be irrelevant for the given issue).

edit: 0.95 and older releases have different dependencies, in particular GTK2 libs, that's why they don't launch. It would be rather troublesome to find and install all the dependencies, I guess.

**Comment by arnoxz** [comment]
Ok, again could you help with the detailed process/command to follow your advised proposal ?
Yeah kazam is less good for sure... i was so upset that I nearly switched :-) 
Thx

**Comment by Photon89** [comment]
There is no process, I'm again out of ideas...

At least, thanks to your last comment I now realized that the upgrade to 0.97 happened on 10th of July along with the upgrade of libuv1, linux-base, libgupnp and many packages related to avahi.

Maybe, try to downgrade linux-base from 4.5ubuntu3.6 to 4.5ubuntu3.5? The changelog for the update is here: http://changelogs.ubuntu.com/changelogs/pool/main/l/linux-base/linux-base_4.5ubuntu3.6/changelog Something happens with environmental variables, maybe this broke something...

**Comment by franco-bez** [comment]
I had precisely the same problem as arnoxz.

this hint actually worked https://askubuntu.com/questions/722708/how-do-i-refresh-the-icon-cache :
just run 
sudo update-icon-caches /usr/share/icons/*

and the icon is back again

**Comment by DarthGandalf** [comment]
Interesting, thanks.

In Gentoo, this command is called automatically after Shutter is installed, via [xdg_pkg_postinst](https://github.com/gentoo/gentoo/blob/542ba42f143441dfae40eccce973e7e3b6f85826/x11-misc/shutter/shutter-0.98.ebuild#L77) which ends up calling [gtk-update-icon-cache](https://github.com/gentoo/gentoo/blob/e136c3976aee76ad4ed432758a51ac2246f805dd/eclass/xdg-utils.eclass#L93). Maybe the ubuntu package can do the same? @logix2 WDYT?

**Comment by Photon89** [comment]
In https://github.com/shutter-project/shutter/issues/363#issuecomment-891038998 arnoxz said, this doesn't help in his case...

Oh, maybe I messed up the command and proposed to call it without the icon theme path as argument...

**Comment by arnoxz** [comment]
Yeeesss - Magnifique !! (i préviousely execute gtk-update, pixbuf update,.... and now...;

This last cmd : update-icon-caches /usr/share/icons/* solved my problem ----

--> so happy thanks you :-) !!

Thanks to all for your highly appreciated effort,.... I'm glad now !
Have a good day !

**Comment by Photon89** [comment]
Great, I'm also really happy that we could finally solve this issue! :smiley: Have fun screenshotting!

**Comment by logix2** [comment]
@Photon89 I can't reproduce the issue using the GNOME desktop, maybe it's a desktop specific thing? And as far as I know, the icon cache is updated upon installing it, e.g. this is shown when installing it: "Processing triggers for hicolor-icon-theme". Also, I'm using the original packaging which is identical to the Shutter package available in old Ubuntu versions (except for the dependencies), so if there's an issue, it should have always been there... So I'm not sure what's causing this exactly.

**Comment by Photon89** [comment]
@logix2 Well, I think, this is some hic-up which happened on OP's machine, no need to worry about it on a large scale.

**Comment by logix2** [comment]
I have a test package [here](https://launchpad.net/~linuxuprising/+archive/ubuntu/ppa/+packages?field.name_filter=shutter&field.status_filter=published&field.series_filter=) with a postinst script that updates the icons but I can't test and see if it fixes the issue. If someone who's experiencing the issue could give it a try, it'd be great. 

If there's no one to test it, I don't know, what do you think @Photon89, should I push that to the PPA or leave the packages as they are?

**Comment by Photon89** [comment]
@logix2 I fear, we won't find anybody with such an issue any time soon... As of myself, I couldn't reproduce this issue on my VM installs. But I think, this change can only make things better, not worse. Even if it breaks something, we will hopefully learn this quite soon here on the bug tracker.

**Comment by logix2** [comment]
@Photon89 Ok, I have copied the packages from my test PPA to the main Shutter PPA, they should be available in a few minutes to all PPA users.

**Comment by Photon89** [comment]
Great, thanks for taking care of this! Funny thing, I have a similar issue with my telegram-desktop client, it shows no icon when new messages arrive for some icon themes. However, in my case, the gtk-update-icon-cache command didn't help. But I guess, this is a completely different issue. :smile:
