### ISSUE TITLE
Clicking Shutter in Dash when application is running in tray does not launch main window.

### ISSUE THREAD

**Issue by ak2766** [shutter-project/shutter#373]
#### Brief summary of issue
When Shutter has been minimized to the tray, attempting to launch the main window by clicking the Shutter icon in the Dash doesn't work as it did in the previous versions - last version where it worked was 0.94.3-1 on Ubuntu 20.04 LTS desktop.

#### Steps to reproduce the issue

1.  Open Shutter
2.  In the Gnome Dash, right-click the Shutter icon and add to Favorites
3.  Configure Shutter to minimize to tray on close
![Selection_00004](https://user-images.githubusercontent.com/6629646/126890902-089a8724-cc4b-4c62-b2a9-a73b919d1f75.png)
4. Close main Shutter window
5. Click the Shutter icon in Gnome Dash
6. Nothing happens

#### Error output
N/A

#### Extra information, such as Shutter version, operating system and ideas for how to solve:
    Gnome-shell: v3.36.4-1ubuntu1~20.04.2
    Shutter: v0.97-1~0linuxuprising1~focal1
    OS: Ubuntu 20.04.2 LTS Desktop

**Comment by Photon89** [comment]
Maybe something useful can be found here: https://wiki.freepascal.org/How_to_use_a_TrayIcon

**Comment by ak2766** [comment]
Yes - when I right (or left) click the Shutter tray icon, I can bring up the main window.  And I did in fact use that method from time to time with the old versions.  So this looks like my only option at the moment.  Just need to retrain that muscle memory to not go for the dash icon if it's already minimized to the tray.

**Comment by DarthGandalf** [comment]
I think this is duplicate of #357 which is fixed in git already

**Comment by Photon89** [comment]
Right, I was thinking that the Dash shows a tray icon which is obviously wrong...

So, if @ak2766 could test the git version, we would know for sure!

**Comment by Photon89** [comment]
@ak2766 You can now also test the 0.98 version: https://github.com/shutter-project/shutter/releases/tag/v0.98

**Comment by ak2766** [comment]
Yeah - working great now with 0.98:
```shell
OS:          Ubuntu 20.04.2 LTS Desktop
Gnome-shell: 3.36.9-0ubuntu0.20.04.2
Shutter:     0.98-1~0linuxuprising1~focal0
```

Much obliged.
