### ISSUE TITLE
VMWare screenshots not always possible

### ISSUE THREAD

**Issue by umeli** [shutter-project/shutter#374]
#### Brief summary of issue
Using the selection to capture only a part of a vm (running vmware-player 16) is almost impossible.
Hit the enter key does not always take the screenshot.

#### Steps to reproduce the issue

1. run a windows vm (linux vm do behave the same)
2. use the "Selection" to capture part of the vm window
3. try to take the screenshot

#### Extra information, such as Shutter version, operating system and ideas for how to solve:
Shutter 0.97 on Xubuntu 20.04
It was working before I upgraded to Shutter 0.97

**Comment by Photon89** [comment]
Was it actually working reliably with the Enter key, or did you possibly use the doubleclick instead? If the latter is the case, it's a duplicate of https://github.com/shutter-project/shutter/issues/359

**Comment by umeli** [comment]
Looks like someone has been faster in createing the bug report. It's duplicate to #359
