### ISSUE TITLE
wrong icon size

### ISSUE THREAD

**Issue by martinkg** [shutter-project/shutter#384]
#### Brief summary of issue

rpmlint reports under Fedora the wrong icon size, please move the 2 icons to 32x 32

E: wrong-icon-size /usr/share/icons/hicolor/24x24/apps/shutter-panel.png expected: 24x24 actual: 32x32
E: wrong-icon-size /usr/share/icons/hicolor/24x24/apps/shutter.png expected: 24x24 actual: 32x32

**Comment by Photon89** [comment]
Already done in https://github.com/shutter-project/shutter/pull/383 among other things. Just waiting for @DarthGandalf to have a look before merging.

**Comment by Photon89** [comment]
#383 is in, so closing.
