### ISSUE TITLE
file shutter.appdata.xml has invalid type attribute

### ISSUE THREAD

**Issue by martinkg** [shutter-project/shutter#385]
#### Brief summary of issue

appstream-util validate-relax reports:
attribute-invalid     : <launchable> has invalid type attribute
and
attribute-invalid     : <component> has invalid type attribute

patch that fix this issue is attached

[shutter.appdata.xml.txt](https://github.com/shutter-project/shutter/files/6948818/shutter.appdata.xml.txt)

**Comment by DarthGandalf** [comment]
Why you didn't do this patch in form of pull request? That would be much easier to see the diff and merge it

**Comment by martinkg** [comment]
maybe later ...

**Comment by Photon89** [comment]
Since this is fixed by your PR #389 I'm closing here. Thanks for the PR!
