### ISSUE TITLE
shutter provides bundled tango-icon-theme package

### ISSUE THREAD

**Issue by martinkg** [shutter-project/shutter#390]
Shutter bundles Tango icons . shutter provides a bundled tango-icon-theme package, but Fedora provides a system installed version of the icon package (tango-icon-theme package) already.
The Icons should be unbundled. See <https://docs.fedoraproject.org/en-US/packaging-guidelines/#bundling>.
All the icons consume 7 MB. That's pretty wasteful.

**Comment by Photon89** [comment]
Removing the Tango items would introduce an additional dependency. For example in Arch Linux the Tango icons are not in the official repos, merely in the AUR. So I think, in this case it is better if you remove the corresponding folder (substitute it by a symlink) when building the Fedora package. @DarthGandalf what do you think?

**Comment by DarthGandalf** [comment]
I agree, we don't need to bundle it.

If these icons are useful at all, they can be added via symlink as `$ ln -s /usr/share/icons/Tango/scalable share/shutter/resources/icons/drawing_tool/objects/Tango`; then these icons just won't be available if Tango is not installed, and will if it is.

**Comment by Photon89** [comment]
In this case we need to revert some of the symlinks which I introduced in https://github.com/shutter-project/shutter/commit/18ea2ef25dbc6633bc8ced7273117ff6679bec19 as currently some of the necessary icons are just symlinks to images inside the Tango folder.

**Comment by DarthGandalf** [comment]
yep

**Comment by Photon89** [comment]
How will Shutter know where to look for the icons? Can we rely on the various distros putting them into some specific location?

**Comment by DarthGandalf** [comment]
I don't know. Maybe ask packagers? At least on Gentoo and Debian it seems to be the same, `/usr/share/icons/Tango`

**Comment by martinkg** [comment]
on Fedora an OpenSuse  it's on `/usr/share/icons/Tango`

**Comment by Photon89** [comment]
Ok, I checked on Arch, there we have the same path as well. But the folder structure is completely different:

The Tango icon theme located in `/usr/share/icons/Tango`:

```
$ ls /usr/share/icons/Tango/
128x128  22x22  32x32  64x64  96x96             index.theme
16x16    24x24  48x48  72x72  icon-theme.cache  scalable
```

What Shutter has bundled:

```
$ ls "/home/photon/shutter/share/shutter/resources/icons/drawing_tool/objects/Tango icon library"
Actions  Apps  Categories  Devices  Emblems  Emotes  MimeTypes  Places  Status
```
Are there even the same icons included?

Never mind, what Shutter bundles can be found in `/usr/share/icons/Tango/scalable`.

**Comment by Photon89** [comment]
@DarthGandalf I just experimented a little. 

1. When substituting the Tango folder with a symlink `/usr/share/icons/Tango/scalable` Shutter picks up the icons as expected.
2. When the Tango icons aren't installed, the symlink is broken but Shutter can deal with it and just doesn't show the Tango folder in the drawing tool.

So in principle it is not a problem to remove the Tango icons and put a symlink instead, from Shutter side, but I am pretty sure, the linter will be mad at a symlink pointing to a possibly non-existing location...

**Comment by Photon89** [comment]
I think, it would be better to change the location where Shutter searches for the Tango icons in the Shutter code.

**Comment by DarthGandalf** [comment]
What's so special about tango at all?

**Comment by Photon89** [comment]
No idea, to be honest. I mean, it's a good thing to have some icons like star/error/question mark/exclamation mark etc. but Tango is actually just an icon theme most of whose icons aren't really useful, in my opinion...

**Comment by Photon89** [comment]
@muflone We are considering to unbundle the tango icons to save disk space. In Arch the tango icons are currently in the AUR: https://aur.archlinux.org/packages/tango-icon-theme/ 

The tango icons are not core functionality, they just appear in a submenu of the editor and can then be added to the screenshot. But the easiest way to unbundle them would be to replace their folder by a symlink to `/usr/share/icons/Tango/scalable/`which does not exist if the Tango package `tango-icon-theme` is not installed. It's a bit ugly to have a symlink showing into nowhere, but Shutter would deal with it and just not show the icons in the editor.

You could take over `tango-icon-theme` and move it to community/ or just leave everything as is, if a dangling symlink is not a problem (I'm not sure if packaging guidelines have any rules regarding this). What do you think?

**Comment by muflone** [comment]
> You could take over `tango-icon-theme` and move it to community/ or just leave everything as is, if a dangling symlink is not a problem (I'm not sure if packaging guidelines have any rules regarding this). What do you think?

As an user I don't like applications forcing me to use a specific icon theme.

GTK allows developers to ask for an icon and the application will use the icon with the same name for the current icon theme


As a packager, it's not a real issue to have a dangling symlink which may point to a non existent folder.


I'd suggest to change the code to lookup the icon from the system theme and not force the Tango theme, regardless my choices.

As for moving Tango in the repositories I don't think it's worth as actually no other applications would require it and GTK themes break very often (in reality it's the opposite, GTK breaks everything)

**Comment by DarthGandalf** [comment]
> I'd suggest to change the code to lookup the icon from the system theme and not force the Tango theme, regardless my choices.

I would agree if this was for a lookup of an icon by name. These icons are only used to be embedded on top of the screenshot in the editing tool, so user can choose any icon from from disk, or from the `/usr/share/shutter/resources/icons/drawing_tool/objects` dir for easy access to some icons. Right now for whatever reason that dir contains a copy of Tango library.

Should it be using the icons from `/usr/share/icons` instead for this purpose?

**Comment by DarthGandalf** [comment]
> not force the Tango theme

I mean, I agree with you, just that's not how these images are now used

**Comment by Photon89** [comment]
@muflone It's about this functionality, where Tango icons can be inserted as images, not the icons which are used in the GTK interface:

![shutter](https://user-images.githubusercontent.com/1191480/131868272-9483e1e8-a0ce-4744-a4af-f42c74662148.png)

**Comment by muflone** [comment]
Ok it's more clear now

I understand the usage but I don't really get why needing to have the symlink to Tango theme instead of pointing directly the directory where the theme lives.

This path can both be found at runtime or set it at building time

**Comment by Photon89** [comment]
@muflone Currently, the Tango icons are part of the Shutter repo. No idea who had the idea to use them as image collection originally, maybe @vadi2 has some memories regarding this. 

But if we unbundle them, we can equally well point to all the icon themes rather than just Tango. @DarthGandalf Can we somehow point to /usr/share/icons/*/scalable, where "*" can be any subfolder?

Or we just say, it's not a good idea to have icon themes in this menu at all. No idea if anybody ever used this functionality... I mean, there is a collection of images available already, don't know if icon themes add anything useful to them.

**Comment by muflone** [comment]
> No idea if anybody ever used this functionality... I mean, there is a collection of images available already, don't know if icon themes add anything useful to them.

As a user, I wasn't aware about this functionality :-P

**Comment by DarthGandalf** [comment]
it was added in 6f9c4e4ca3c4fa331fec44382c7b5d147649d748 with very little explanation

**Comment by DarthGandalf** [comment]
> Can we somehow point to /usr/share/icons//scalable, where "" can be any subfolder?

The easiest is to point it at root of /usr/share/icons instead of Tango

> it's not a good idea to have icon themes in this menu at all

That also works for me

**Comment by Photon89** [comment]
> The easiest is to point it at root of /usr/share/icons instead of Tango

This would show all the subfolders with icon sizes as well, though. Like, [theme name]/24x24/[folders we actually want to see in the menu], [theme name]/32x32/[folders we actually want to see in the menu] etc.

**Comment by Photon89** [comment]
What if we just drop the Tango icon theme functionality and see if we get any complaints here at the issue tracker? :smile:

**Comment by DarthGandalf** [comment]
> This would show all the subfolders with icon sizes as well, though. Like, [theme name]/24x24/[folders we actually want to see in the menu], [theme name]/32x32/[folders we actually want to see in the menu] etc.

In theory, maybe. In practice, even if opening the scalable (svg) version, shutter converts it to pixbuf first, which is not scalable at all. Therefore, ability to select the more fitting size is a feature until shutter learns how to actually scale the scalable icons.

> What if we just drop the Tango icon theme functionality and see if we get any complaints here at the issue tracker?

Yep

**Comment by Photon89** [comment]
Right, good point!

So, I updated the PR and removed the Tango folder.
