### ISSUE TITLE
When I try to pen an existing image so it gives me this error Error while opening Image 'ARRAY

### ISSUE THREAD

**Issue by appify-hazrat** [shutter-project/shutter#398]

**Comment by Photon89** [comment]
Does it fail to open the image? There are several ways to open an existing image with Shutter, please describe how you did it. Also, which Shutter version are you using?

**Comment by appify-hazrat** [comment]
@Photon89 I tried to open from file menu
File -> open

**Comment by Photon89** [comment]
Looks like a duplicate of #393 which is already fixed in git but not yet released.

**Comment by appify-hazrat** [comment]
Yes the same issue #393 I am getting but when I click upon image and open with (select shutter) then it opens up, 
thanks for your information will update once released

**Comment by Photon89** [comment]
Yes exactly, there are several ways to open an image from file but only one of them was broken.

Closing as duplicate of #393 then!

**Comment by DarthGandalf** [comment]
A tip: " No description provided. " is not helpful. There's a reason why the template asks for steps to reproduce, shutter version and more.
