### ISSUE TITLE
shutter don't start

### ISSUE THREAD

**Issue by Nasdrovia69** [shutter-project/shutter#399]
#### Brief summary of issue
after update  version 0.98      shutter don't work when it works perfectly before
can you solve the problem and make an update working or  Tell me a correction I can make
I can't downgrade it !!
Thanks
#### Steps to reproduce the issue

1. 
2. 
3. 

#### Error output

(base) 0 -- 12:35:23 Zalman@gil $ ~  : shutter &
[1] 1081341
(base) 0 -- 13:10:09 Zalman@gil $ ~  : Typelib file for namespace 'Wnck', version '3.0' not found at /usr/lib64/perl5/vendor_perl/Glib/Object/Introspection.pm line 108.
BEGIN failed--compilation aborted at /usr/bin/shutter line 58.

#### Extra information, such as Shutter version, operating system and ideas for how to solve:
Kde fc 34

**Comment by DarthGandalf** [comment]
Please see https://github.com/shutter-project/shutter/issues/328#issuecomment-909151016

**Comment by Nasdrovia69** [comment]
Thank you for the answer, install libwnck3, and now it works nice
thank you for your rapidity you are up
long life to shutter nice program
