### ISSUE TITLE
In Debian 11, the gir1.2-appindicator3 package has been removed due to compatibility issues.

### ISSUE THREAD

**Issue by search5** [shutter-project/shutter#400]
#### Brief summary of issue
In Debian 11, the gir1.2-appindicator3 package has been removed due to compatibility issues.

Accordingly, Debian and Ubuntu recommend using the gir1.2-ayatanaappindicator3-0.1 package instead of the gir1.2-appindicator3 package.

I think shutter will also need to reflect package modifications.

#### Extra information, such as Shutter version, operating system and ideas for how to solve:

It is difficult to record the steps to reproduce the issue as the shutter package has not yet been reflected in Debian 11.

However, when I got the shutter package from salsa.debian.org and tried to build it manually and checked it, the tray icon was not confirmed.

Details of support for gir1.2-appindicator3 and libappindicator3 in Debian 11 can be found at the following URL.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=895037

If shutter is changed to use the gir1.2-ayatanaappindicator3 package instead of gir1.2-appindicator3, it seems that the contents of the dependency part of the shutter project homepage will also need to be updated.

https://shutter-project.org/downloads/dependencies/

The gir1.2-ayatanaappindicator3-0.1 package is currently reflected in Debian 11 and Ubuntu 21.04 as well.

The reason the gir1.2-appindicator3 package and related packages were removed from Debian 11 seems to be that the libappindicator3 package is no longer maintained since 2011.

**Comment by DarthGandalf** [comment]
Can you try this patch?

```diff
diff --git a/bin/shutter b/bin/shutter
index f315f5cc..3d4e3e8c 100755
--- a/bin/shutter
+++ b/bin/shutter
@@ -9056,8 +9056,17 @@ sub STARTUP {
 			);
 		};
 		if ($@) {
-			warn "WARNING: AppIndicator is missing --> there will be no icon showing up in the status bar when running Unity!\n\n";
-			$appindicator = FALSE;
+			eval {
+				Glib::Object::Introspection->setup(
+					basename => 'AyatanaAppIndicator3',
+					version  => '0.1',
+					package  => 'AppIndicator',
+				);
+			};
+			if ($@) {
+				warn "WARNING: AppIndicator is missing --> there will be no icon showing up in the status bar when running Unity!\n\n";
+				$appindicator = FALSE;
+			}
 		}
 
 		return TRUE;

```

**Comment by DarthGandalf** [comment]
Sorry, updated the patch.

**Comment by search5** [comment]
@DarthGandalf We have confirmed that the tray icon works normally with the newly modified patch.

**Comment by Photon89** [comment]
@DarthGandalf Does this patch affect dependencies in other distros as well?

**Comment by DarthGandalf** [comment]
That depends on the distro :)

More seriously, it's just a fallback. If appindicator3 is not available, it tries the ayatana one. One of them should be installed for the tray icon to work in certain DEs.

**Comment by search5** [comment]
Thanks for the quick action.

We are happy to make the tray icon available with the
gir1.2-ayatanaappindicator3-0.1 package.

However, we hope that the shutter team's homepage will also be updated
regarding this change.

Thank you.
------------------------------------------------------------------------
------------------------------------
There is a future society, but my future is not what others do.
Dept. of Information Science, Graduate School, Korea National Open
University


2021년 9월 2일 (목) 오전 5:21, Alexey Sokolov ***@***.***>님이 작성:

**Comment by Photon89** [comment]
@DarthGandalf I see, so we should probably update the dependency information on the website? And probably the Debian packagers would need a release containing the patch, so maybe we make a 0.98.2 release for this?

**Comment by DarthGandalf** [comment]
> I see, so we should probably update the dependency information on the website?

After the new release, sure

> And probably the Debian packagers would need a release containing the patch, so maybe we make a 0.98.2 release for this?

We don't have a Debian package, do we?

**Comment by Photon89** [comment]
Nope, but as @search5 pointed out, they are working on one, and probably they need the latest changes for their package to work.

**Comment by DarthGandalf** [comment]
Ah, that's great! I've missed that

**Comment by Photon89** [comment]
Check out the last few messages at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=964785 !
