### ISSUE TITLE
Capture the active window with the appropriate delay and display the cursor on it.

### ISSUE THREAD

**Issue by hongyi-zhao** [shutter-project/shutter#404]
I try to capture the active window with the appropriate delay, but the screenshot can't include the cursor on it. How to capture the active window with the appropriate delay and display the cursor on it?

Regards,
HY

**Comment by Photon89** [comment]
It works for me. Did you set the "Include Cursor" option  (right next to the delay setting, in the status line  of the main window)?

**Comment by hongyi-zhao** [comment]
Thank you for pointing this out. I have selected this option now, and it really works:

![image](https://user-images.githubusercontent.com/11155854/132977160-1b73f41d-2f56-463e-99b2-5d2a5a362cd5.png)

**Comment by DarthGandalf** [comment]
It's exposed even outside of Settings:

![-home-somebody-Картинки-Выделение_387 png - Shutter_001](https://user-images.githubusercontent.com/325092/132979702-bf197081-c279-4c14-b7b2-f4107b98bb21.png)

**Comment by hongyi-zhao** [comment]
I'm not sure what you mean.

**Comment by Photon89** [comment]
You don't have to open the settings dialog to change this setting, it is available from the main window, so you can change this option on the fly comfortably.

**Comment by hongyi-zhao** [comment]
@Photon89 Thank you for your explanation. @DarthGandalf uses the Russian version, but I don’t understand Russian at all.
