### ISSUE TITLE
Faster region capture by skipping enter press

### ISSUE THREAD

**Issue by nixRidge** [shutter-project/shutter#406]
#### Description of requested feature:
When capturing a user-defined rectangular region on screen, you have to press enter to actually perform the capture. An option to skip this extra step would be helpful.

#### Reasons for adding feature:
For those of us who do not necessarily need to use Shutter's editing tools most of the time, and just want to copy a region to the clipboard quickly for pasting elsewhere (Discord, Twitter, etc.), it would save us a few seconds each day :)

This will allow Shutter to _(no offense!)_ stay out of our way, living peacefully in the tray as an icon and nothing else, while we use keyboard shortcuts to do our region captures now and then.

#### Extra information, such as Shutter version, operating system and ideas for how to implement:
The feature could be implemented as an optional toggle in Shutter settings' "Behavior" tab.

**Comment by DarthGandalf** [comment]
have you tried the double click instead of enter? double click also captures the selected region

**Comment by nixRidge** [comment]
I wasn't aware of this function, thanks! It's a bit faster but I (personally at the very least) think capture on releasing the mouse button would be a lot better for many people.
This would also avoid the region being moved around when double clicking, in the case of a user with relatively unstable hands. I find myself moving my mouse around slightly when clicking sometimes 😅

Then again, I have no idea how much extra work it would take to implement this feature, so I'd understand if you want to close the issue and encourage double clicking instead. Thanks for the quick response regardless!

**Comment by DarthGandalf** [comment]
don't worry, until recently I wasn't aware of this function either :)

**Comment by Photon89** [comment]
This is actually the same as #590  and has been implemented in #610. Closing!
