### ISSUE TITLE
Pre-capture delay is not working

### ISSUE THREAD

**Issue by ramtg** [shutter-project/shutter#409]
Pre-capture delay seconds entered on the bottom right of the main window was not taking effect on Ubuntu 18.04.

I was using Shutter 0.94 Rev.1290.

Any help will be appreciated.

**Comment by Photon89** [comment]
Possible things to try:

1. Move `~/.shutter` to be sure that it's not a configuration issue.
2. Try the latest version (0.99) by unpacking the source tarball and launching Shutter from the unpacked directory. It requires some new dependencies though: https://shutter-project.org/downloads/dependencies/
3. Post the terminal output, possibly it shows something helpful.

**Comment by Photon89** [comment]
As there hasn't been a reply by OP for over two months, and also version 0.94 is quite outdated, I'm closing here. Please comment and/or reopen, if the issue persists.
