### ISSUE TITLE
Cannot call shutter while shutter is running

### ISSUE THREAD

**Issue by hellojoe88** [shutter-project/shutter#411]
#### Brief summary of issue
Previously it was possible to have shutter running and then invoke taking a screenshot by calling `shutter -e` or `shutter -f` or simply `shutter`. Now shutter exits with `g_application_get_is_remote: assertion 'application->priv->is_registered' failed`.

#### Steps to reproduce the issue

1. Run `shutter`
2. Run `shutter -e` (or any other capture mode)

#### Error output
`(shutter:4436): GLib-GIO-CRITICAL **: 11:25:39.408: g_application_get_is_remote: assertion 'application->priv->is_registered' failed`

#### Extra information, such as Shutter version, operating system and ideas for how to solve:
Full `shutter --debug` log: [https://pastebin.com/WpYXJuyg](https://pastebin.com/WpYXJuyg)

**Comment by DarthGandalf** [comment]
Fixed in git, see #407
