### ISSUE TITLE
Fill opacity no longer available.

### ISSUE THREAD

**Issue by richardcrossley** [shutter-project/shutter#412]
#### Brief summary of issue
Recent releases of Shutter on Ubuntu 20.04 LTS seem to be missing the ability to change the opacity of a shape. I can draw a filled rectangle or ellipse, but cannot draw an unfilled shape. Typically I use this for highlighting something on a screen shot.

#### Steps to reproduce the issue

1.  In the "Choose Fill Color" window there used to be a method of specifying an opacity, this seems to be no longer available.

#### Extra information, such as Shutter version, operating system and ideas for how to solve:

Ubuntu Linux 20.04
uname -r:
Linux borg 5.11.0-37-generic #41~20.04.2-Ubuntu SMP Fri Sep 24 09:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Cinnamon Desktop
Shutter 0.99 Rev 1591

**Comment by Photon89** [comment]
It works for me, you have to click the little plus button on the bottom left of the color chooser to get the dialog where you can specify the opacity with the slider on the bottom: 

![Bildschirmfoto_2021-10-16_10-06-33](https://user-images.githubusercontent.com/1191480/137579835-add2e633-6996-442b-9bb8-04f76aeb7fca.png)

**Comment by richardcrossley** [comment]
Thanks. Not having a label meant I missed it.

This can be closed now.
