### ISSUE TITLE
Shutter does not scale on a HiDPI screen

### ISSUE THREAD

**Issue by floyddcn** [shutter-project/shutter#413]
shutter version:shutter/impish,impish,now `0.99-1~1ppa1~impish0 `

ubuntu:GNOME
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu Impish Indri (development branch)
Release: 21.10
Codename: impish
**scaling:1.75x**

Every time i use 'shutter -s' to make some selection larger than a portion of the whole screen size( about 4/5 of the screen) ,
then the screen just black out and after one or two seconds the screen came back. It seems that the selection exceeds the range which shutter can handle. when i select a small region(less then 2/3 of the screen) it'll be ok.

**Comment by DarthGandalf** [comment]
How did you set up scaling?

Can you record a video which shows the problem? e.g. with simplescreenrecorder
