### ISSUE TITLE
Unable to capture desktop (org.freedesktop.portal.Desktop was not provided)

### ISSUE THREAD

**Issue by muflone** [shutter-project/shutter#416]
#### Brief summary of issue

Running shutter 0.99.1 on Arch Linux and capturing the desktop image I get the error:

org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files

#### Steps to reproduce the issue

1. Install shutter 0.99.1-1 on Arch Linux x86_64
2. Start shutter
3. Click on the Desktop button

#### Error output

org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files

**Comment by muflone** [comment]
In the terminal window I can read:

```
GLib-CRITICAL **: Source ID 429 was not found when attempting to remove it at /usr/bin/shutter line 6906.
 at /usr/bin/shutter line 6904.
	Shutter::App::fct_show_status_message(1, "Error while taking the screenshot.") called at /usr/bin/shutter line 6233
	Shutter::App::fct_take_screenshot(Gtk3::MenuToolButton=HASH(0x56528851c6a0), "full", undef, undef) called at /usr/bin/shutter line 3065
	Shutter::App::__ANON__() called at /usr/lib/perl5/5.34/vendor_perl/Glib/Object/Introspection.pm line 67
	eval {...} called at /usr/lib/perl5/5.34/vendor_perl/Glib/Object/Introspection.pm line 67
	Glib::Object::Introspection::__ANON__(Shutter::App=HASH(0x565288023070)) called at /usr/bin/shutter line 10943
```

**Comment by Photon89** [comment]
Hi, thanks for testing, are you possibly trying the newly implemented rudimentary Wayland support?

**Comment by Photon89** [comment]
@DarthGandalf Did we possibly miss documenting new dependencies, xdg-desktop-portal-gtk and xdg-desktop-portal, for Wayland support (see https://github.com/flatpak/flatpak/issues/2446)?

**Comment by DarthGandalf** [comment]
xdg-desktop-portal-gtk is not a dependency. xdg-desktop-portal probably is though.

Depending on what compositor is running, you may need xdg-desktop-portal-gtk, xdg-desktop-portal-kde, xdg-desktop-portal-wlr. And running the wrong one won't work.

**Comment by Photon89** [comment]
> Depending on what compositor is running, you may need xdg-desktop-portal-gtk, xdg-desktop-portal-kde, xdg-desktop-portal-wlr. And running the wrong one won't work.

Sounds like a lot of packaging fun... I hope, the xdg-desktop-portal package or the various DE metapackages take care of the DE specific xdg-desktop-portal packages, so it won't be upto the Shutter packge to deal with it...

**Comment by DarthGandalf** [comment]
I mentioned some of this in the changelog at https://shutter-project.org/releases/0.99.1/ but adding this to https://shutter-project.org/downloads/dependencies/ looks like good idea

**Comment by DarthGandalf** [comment]
At least in Gentoo, the plasma-meta package depends on xdg-desktop-portal-kde which depends on xdg-desktop-portal

**Comment by Photon89** [comment]
I see!

Thanks for updating the website!

**Comment by muflone** [comment]
> Hi, thanks for testing, are you possibly trying the newly implemented rudimentary Wayland support?

I'm not using Wayland at all, my server session is pure X11, is the dependency required also for non wayland servers?

**Comment by DarthGandalf** [comment]
> I'm not using Wayland at all, my server session is pure X11

That code is executed only if `$XDG_SESSION_TYPE` is `wayland`. Can you show `env | grep XDG`?

**Comment by muflone** [comment]
```
21:02:51 muflone:~$ env | grep XDG
XDG_MENU_PREFIX=gnome-
XDG_SESSION_DESKTOP=gnome
XDG_SESSION_TYPE=x11
XDG_CURRENT_DESKTOP=GNOME
XDG_SESSION_CLASS=user
XDG_RUNTIME_DIR=/run/user/1000
```

**Comment by muflone** [comment]
Installing xdg-desktop-portal works fine, with the portal confirmation dialog, but hangs indefinitively denying to pass the data

**Comment by DarthGandalf** [comment]
Ooh, it's my mistake
