### ISSUE TITLE
plugin / upload destination chevereto?

### ISSUE THREAD

**Issue by grand-lotus-iroh** [shutter-project/shutter#418]
Might anyone know if this is something that is available but I can't find on the web?

I was browsing around in the preferences and noticed the Upload and Plugin tab and thought maybe someone found a way to use shutter with chevereto?

Coming from Windows, I was able to use ShareX and configure chevereto with a username and password + API key and I believe Chevereto does not support FTP uploading.

**Comment by Photon89** [comment]
Unfortunately, Shutter has no option to add a custom upload service, so you would need to write a plugin for it.
