### ISSUE TITLE
Question regarding getting the dependencies

### ISSUE THREAD

**Issue by joaovarelas** [shutter-project/shutter#419]
Using Debian 10 Buster

Build from source with `make`.

Error:
```Can't locate Carp/Always.pm in @INC (you may need to install the Carp::Always module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/x86_64-linux-gnu/perl5/5.28 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) ```

Fixed by install

```bash
$ sudo apt install libcarp-always-perl
```

Then got error

```
Can't locate Number/Bytes/Human.pm in @INC (you may need to install the Number::Bytes::Human module) (@INC contains: /etc/perl
```

Fixed by install

```bash
$ sudo apt install libnumber-bytes-human-perl
```

Then got error

```
Can't locate Pango.pm in @INC (you may need to install the Pango module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.28.1 
```

Tried to install

```bash
$ sudo apt install libpango-perl
```

Without success.

Tried to install

```bash
$ sudo apt install --reinstall libgtk3-perl 
```

Without success.

Any hints? Cant find docs.

**Comment by Photon89** [comment]
So, after installing `libpango-perl`, it is still giving 

`Can't locate Pango.pm in @INC (you may need to install the Pango module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.28.1 `

?

**Comment by joaovarelas** [comment]
> So, after installing `libpango-perl`, it is still giving
> 
> `Can't locate Pango.pm in @INC (you may need to install the Pango module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.28.1 `
> 
> ?


The error output:

```
Subroutine Pango::Layout::set_text redefined at /usr/share/perl5/Gtk3.pm line 2238.
	require Gtk3.pm called at /usr/local/bin/shutter line 72
	Shutter::App::BEGIN() called at /usr/share/perl5/Gtk3.pm line 2238
	eval {...} called at /usr/share/perl5/Gtk3.pm line 2238
Subroutine Pango::Layout::set_markup redefined at /usr/share/perl5/Gtk3.pm line 2244.
	require Gtk3.pm called at /usr/local/bin/shutter line 72
	Shutter::App::BEGIN() called at /usr/share/perl5/Gtk3.pm line 2244
	eval {...} called at /usr/share/perl5/Gtk3.pm line 2244
Can't locate Gtk3/ImageView.pm in @INC (you may need to install the Gtk3::ImageView module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/x86_64-linux-gnu/perl5/5.28 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/local/bin/shutter line 74.
	Shutter::App::BEGIN() called at /usr/local/bin/shutter line 74
	eval {...} called at /usr/local/bin/shutter line 74
BEGIN failed--compilation aborted at /usr/local/bin/shutter line 74.
```

**Comment by Photon89** [comment]
> Can't locate Gtk3/ImageView.pm in @INC

So now it is `libgtk3-imageview-perl` which is missing. You need version 10, to be more precise.

**Comment by DarthGandalf** [comment]
Please see https://shutter-project.org/downloads/dependencies/ with the full list

**Comment by Photon89** [comment]
In the mean time Shutter has returned to the Debian repositories (for Debian 11 Bookworm): https://packages.debian.org/source/bookworm/shutter Closing, please comment, if the issue is still present.
