### ISSUE TITLE
The Editor doesn't work.

### ISSUE THREAD

**Issue by Helspank** [shutter-project/shutter#426]
#### Brief summary of issue

The Editor doesn't work. When I click on the "Edit" button, nothing happens.

#### Steps to reproduce the issue

1. Take a screenshot.
2. Open Shutter  (Right Click on tray -> Show Main Window)
3. Click on the "Edit" button

#### Error output

In the GUI, no output. Nothing happens.

https://user-images.githubusercontent.com/45527374/141284269-7f8185e5-7b11-4ee9-8813-33314796b61d.mp4

When ran from cli, this is the output I get whenever I click on the "Edit" button:

```
(shutter:125707): Gtk-CRITICAL **: 11:51:54.952: gtk_spin_button_new_with_range: assertion 'step != 0.0' failed
*** unhandled exception in callback:
***   Can't call method "set_value" on an undefined value at /usr/share/perl5/Shutter/Draw/DrawingTool.pm line 528.
***     Shutter::Draw::DrawingTool::setup_bottom_hbox(Shutter::Draw::DrawingTool=HASH(0x56487dd6c8e0)) called at /usr/share/perl5/Shutter/Draw/DrawingTool.pm line 423
***     Shutter::Draw::DrawingTool::show(Shutter::Draw::DrawingTool=HASH(0x56487dd6c8e0), "/home/Selection_022.png", "png", "image/png", "Selection_022", "", HASH(0x564862edc0e8)) called at /usr/bin/shutter line 5820
***     Shutter::App::fct_draw(Gtk3::ToolButton=HASH(0x5648653594e0)) called at /usr/lib/x86_64-linux-gnu/perl5/5.30/Glib/Object/Introspection.pm line 67
***     eval {...} called at /usr/lib/x86_64-linux-gnu/perl5/5.30/Glib/Object/Introspection.pm line 67
***     Glib::Object::Introspection::__ANON__(Shutter::App=HASH(0x56486478f320)) called at /usr/bin/shutter line 10849
***  ignoring at /usr/lib/x86_64-linux-gnu/perl5/5.30/Glib/Object/Introspection.pm line 67.
 at /usr/bin/shutter line 10849.
```

![Screenshot](https://user-images.githubusercontent.com/45527374/141285861-e7930ed0-4ef8-458c-a498-5b26e02ba1a6.png)

#### Extra information:

**Shutter version**: 0.99 rev 1591
**OS**: Kubuntu 20.04

KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.11.0-40-generic
OS Type: 64-bit

**Comment by Photon89** [comment]
I just set up Kubuntu 20.04 in a VM and installed Shutter 0.99.2 from the official PPA but cannot reproduce the issue. Is it still there with Shutter 0.99.2?

**Comment by Helspank** [comment]
The Editor now works in Shutter 0.99.2. Thanks!

**Comment by Photon89** [comment]
Great, thanks for letting us know!
