### ISSUE TITLE
Tests in CI

### ISSUE THREAD

**Issue by DarthGandalf** [shutter-project/shutter#436]
#### Description of requested feature:
Since we now have tests, it would be nice to automatically run then on push and on pull requests

#### Reasons for adding feature:
To avoid breaking code

#### Extra information, such as Shutter version, operating system and ideas for how to implement:
Github actions perhaps

**Comment by vadi2** [comment]
I can take this on, how does one run them?

**Comment by ruzhnikov** [comment]
> I can take this on, how does one run them?

```bash
cd <shutter project root directory>
TEST_APP_SHUTTER_PATH=$(pwd) prove -I share/shutter/resources/modules/ -I t/lib t -r
```

**Comment by ruzhnikov** [comment]
I suppose I will add the readme file in the `t/` folder a bit later

**Comment by vadi2** [comment]
https://github.com/shutter-project/shutter/runs/4600884499?check_suite_focus=true#step:3:4 it looks like some dependencies need to be installed?

**Comment by DarthGandalf** [comment]
Of course. Some may be installed via cpanm, some heavier ones from apt-get

**Comment by ruzhnikov** [comment]
in the root of project there’s a file `cpanfile`, it’s useful way to install all dependencies via cpanm

**Comment by vadi2** [comment]
Whatever cpanm installed, the tests are not finding it: https://github.com/shutter-project/shutter/runs/4604809241?check_suite_focus=true#step:4:4

This is going to need some better documentation here in order to be successful.

**Comment by vadi2** [comment]
ping @DarthGandalf @ruzhnikov

**Comment by ruzhnikov** [comment]
oops, I missed your last message.
Ok, may I reproduce the environment for running the task? I have few experience of working with github CI/CD
