### ISSUE TITLE
Shutter crashes at startup

### ISSUE THREAD

**Issue by gapys-krzysztof** [shutter-project/shutter#438]
#### Brief summary of issue
( Moved from https://github.com/shutter-project/shutter/issues/405 )

Shutter crashes at startup

#### Steps to reproduce the issue
1.  (Presumably related) Be on a Arch Linux + X server + DWM configuration
2.  Try launching app using a method of your choice - from a terminal, .desktop file etc.
3.  See issue (It doesn't launch, outputs error messages)

#### Error output
Full log at: https://pastebin.com/RXSJc1Us
Highlight:
```
Can't use an undefined value as an ARRAY reference at /usr/local/bin/shutter line 8346, <DATA> line 19.
        Shutter::App::fct_ret_window_menu() called at /usr/local/bin/shutter line 8449
        Shutter::App::fct_ret_tray_menu() called at /usr/local/bin/shutter line 473
        Shutter::App::STARTUP(Shutter::App=HASH(0x55a004477128)) called at /usr/lib/perl5/5.34/vendor_perl/Glib/Object/Introspection.pm line 67
        Glib::Object::Introspection::__ANON__(Shutter::App=HASH(0x55a004477128)) called at /usr/local/bin/shutter line 10950
```

#### Extra information, such as Shutter version, display server in use (Xorg or Wayland), operating system and ideas for how to solve:

Arch Linux
xorg-server 21.1.1-3
Shutter 0.99.2
dwm 6.2-3

Looked into the code, this seems the part of the code responsible for the crash:
```
#add all windows to menu to capture it directly
#foreach my $win (@{$wnck_screen->get_windows_stacked}) {
	# if ($active_workspace && $win->is_on_workspace($active_workspace)) {
	# 	my $win_name = $win->get_name;
	# 	Encode::_utf8_on($win_name);
	# 	my $window_item = Gtk3::ImageMenuItem->new_with_label($win_name);
	# 	foreach my $child ($window_item->get_children) {
	# 		if ($child =~ /Gtk3::AccelLabel/) {
	# 			$child->set_width_chars(50);
	# 			$child->set_ellipsize('middle');
	# 			last;
	# 		}
	# 	}
	# 	$window_item->set_image(Gtk3::Image->new_from_pixbuf($win->get_mini_icon));
	# 	$window_item->set('always_show_image' => TRUE);
	# 	$window_item->signal_connect(
	# 		'activate' => \&evt_take_screenshot,
	# 		"shutter_window_direct" . $win->get_xid
	# 	);
	# 	$menu_windows->append($window_item);
	# }
#}
```
(wnck_screen->get_windows_stacked) doesn't seem do be populated.
	
Commenting this part out makes app launch, though in limited capacity (can't make window or desktop screenshots).

**Comment by iysheng** [comment]
I met this bug too, I use fedora 35 with dwm. these log are same:
``` text
Linux fedora 5.15.6-200.fc35.x86_64 #1 SMP Wed Dec 1 13:41:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

\S
Kernel \r on an \m (\l)


Glib 1.3293
Gtk3 0.038

Glib built for 2.69.0, running with 2.70.2

Can't use an undefined value as an ARRAY reference at /bin/shutter line 8326, <DATA> line 19.
	Shutter::App::fct_ret_window_menu() called at /bin/shutter line 8429
	Shutter::App::fct_ret_tray_menu() called at /bin/shutter line 466
	Shutter::App::STARTUP(Shutter::App=HASH(0x55ab04b5d098)) called at /usr/lib64/perl5/vendor_perl/Glib/Object/Introspection.pm line 67
	Glib::Object::Introspection::__ANON__(Shutter::App=HASH(0x55ab04b5d098)) called at /bin/shutter line 10943
GLib-GObject-CRITICAL **: g_boxed_free: assertion 'boxed != NULL' failed, <DATA> line 19 during global destruction.
 at /bin/shutter line 0, <DATA> line 19.
	eval {...} called at /bin/shutter line 0
GLib-GObject-CRITICAL **: g_boxed_free: assertion 'boxed != NULL' failed, <DATA> line 19 during global destruction.
 at /bin/shutter line 0, <DATA> line 19.
	eval {...} called at /bin/shutter line 0
GLib-GObject-CRITICAL **: g_boxed_free: assertion 'boxed != NULL' failed, <DATA> line 19 during global destruction.
 at /bin/shutter line 0, <DATA> line 19.
	eval {...} called at /bin/shutter line 0
GLib-GObject-CRITICAL **: g_boxed_free: assertion 'boxed != NULL' failed, <DATA> line 19 during global destruction.
 at /bin/shutter line 0, <DATA> line 19.
	eval {...} called at /bin/shutter line 0
GLib-GObject-CRITICAL **: g_boxed_free: assertion 'boxed != NULL' failed, <DATA> line 19 during global destruction.
 at /bin/shutter line 0, <DATA> line 19.
	eval {...} called at /bin/shutter line 0
GLib-GObject-CRITICAL **: g_boxed_free: assertion 'boxed != NULL' failed, <DATA> line 19 during global destruction.
 at /bin/shutter line 0, <DATA> line 19.
	eval {...} called at /bin/shutter line 0
GLib-GObject-CRITICAL **: g_boxed_free: assertion 'boxed != NULL' failed, <DATA> line 19 during global destruction.
 at /bin/shutter line 0, <DATA> line 19.
	eval {...} called at /bin/shutter line 0
GLib-GObject-CRITICAL **: g_boxed_free: assertion 'boxed != NULL' failed, <DATA> line 19 during global destruction.
 at /bin/shutter line 0, <DATA> line 19.
	eval {...} called at /bin/shutter line 0
GLib-GObject-CRITICAL **: g_boxed_free: assertion 'boxed != NULL' failed, <DATA> line 19 during global destruction.
 at /bin/shutter line 0, <DATA> line 19.
	eval {...} called at /bin/shutter line 0
GLib-GObject-CRITICAL **: g_boxed_free: assertion 'boxed != NULL' failed, <DATA> line 19 during global destruction.
 at /bin/shutter line 0, <DATA> line 19.
	eval {...} called at /bin/shutter line 0
```

**Comment by Photon89** [comment]
I set up an Archlabs VM with dwm and can reproduce the issue. It looks like, as I suspected, wnck fails to get a list of windows in dwm. `$wnck_screen->get_windows_stacked` and `$wnck_screen->get_windows` are undefined in dwm. According to https://gitlab.gnome.org/GNOME/libwnck/-/issues/128 there should be support for _NET_CLIENT_LIST and/or ewmh in the window manager. It looks like https://dwm.suckless.org/patches/ewmhtags/ and/or https://github.com/bakkeby/patches/blob/master/dwm/dwm-netclientliststacking-6.2.diff could introduce this support but I am not experienced enough with dwm to try it out myself. Would you guys care to check if one of those dwm patches solve the problem for you?

**Comment by gapys-krzysztof** [comment]
I'll give it a go after a few days unless someone gets there faster

**Comment by gapys-krzysztof** [comment]
Can confirm application launches correctly after applying both patches :+1: Detecting windows and screen areas to take a screenshot of appears to be working correctly as well

**Comment by Photon89** [comment]
Possibly only one of them is actually necessary. If you can check this, we can add the information to our wiki. Thanks!

**Comment by gapys-krzysztof** [comment]
It seems both are needed, https://github.com/bakkeby/patches/blob/master/dwm/dwm-netclientliststacking-6.2.diff for running the app without crashes, and  https://dwm.suckless.org/patches/ewmhtags/ (6.2) for detecting windows correctly

**Comment by Photon89** [comment]
I see, thanks for investigating it! I've documented your findings in the wiki: https://github.com/shutter-project/shutter/wiki

**Comment by DarthGandalf** [comment]
Can we please kill the wiki, and put its content to the website?

**Comment by Photon89** [comment]
Sure, good idea! I'll take care of that.
