### ISSUE TITLE
Add 1 pixel per corner of the photo

### ISSUE THREAD

**Issue by ging-dev** [shutter-project/shutter#439]
Screenshot of CSD apps or mutter/metacity are often missing the border around the window, so can we add 1 pixel to each corner?
Ideas taken from https://github.com/xfce-mirror/xfce4-screenshooter/blob/e1effca4d088621d574328557a75576cf0091082/lib/screenshooter-capture.c#L389
![](https://i.imgur.com/mPRaimH.png)

**Comment by Photon89** [comment]
Could you solve the issue already?

**Comment by ging-dev** [comment]
> Could you solve the issue already?

i tried, but shutter doesn't support alpha channel, so this doesn't give me the result I expected.
https://github.com/shutter-project/shutter/issues/56
