### ISSUE TITLE
Shutter - gnome-web-photo issues

### ISSUE THREAD

**Issue by DanLo-peratingSystem** [shutter-project/shutter#440]
#### Brief summary of issue
The web-photo functionality has 3 issues I wanted to signal here. One main and 2 subsidiaries (I think those ones don't deserve their own issue for now, but just tell me otherwise).
- [x] The drop-down options for the timeout duration of the Website capture are blank : no text displayed.
An existing bypass of this issue is by reading the hovering info text... however :

- [x] The translation of the hovering text are grammatically wrong in French..! 
- [ ]  The button to do a web capture feels misleading IMO, as it looks like a Safari-thing (why ?!). At best it could be picked automatically from users default browser, or maybe a custom icon like this one : 
![image](https://user-images.githubusercontent.com/11614445/145800751-163cafb3-dc5d-4864-a86a-c5b6c304020c.png)

#### Steps to reproduce the issue

1. Start Shutter
2. Click on the drop-down menu options for a Web URL Capture (gnome-web-photo module)
3. See the 3 "problems" mentioned above.
![image](https://user-images.githubusercontent.com/11614445/145800938-e22db144-bc9a-489c-9bc5-924ee4e45c59.png)

#### Error output
Here are the logs I have for main issue, when I click on the drop-down button : 

```sh
fct_update_tray_menu was called by Wnck::Screen=HASH(0x559110097b08)
*** Gtk3::RadioMenuItem::new: passed too many parameters (expected 2, got 3); ignoring excess at /usr/share/perl5/Gtk3.pm line 1494.
	Gtk3::__ANON__("Gtk3::RadioMenuItem", undef, "Attendre ind\x{e9}finiment") called at /usr/bin/shutter line 8664
	Shutter::App::fct_ret_web_menu(Gtk3::MenuToolButton=HASH(0x559110c6bf68)) called at /usr/lib/x86_64-linux-gnu/perl5/5.30/Glib/Object/Introspection.pm line 67
	eval {...} called at /usr/lib/x86_64-linux-gnu/perl5/5.30/Glib/Object/Introspection.pm line 67
	Glib::Object::Introspection::__ANON__(Shutter::App=HASH(0x559110003c28)) called at /usr/bin/shutter line 10943
*** Gtk3::RadioMenuItem::new_from_widget: passed too many parameters (expected 2, got 3); ignoring excess at /usr/share/perl5/Gtk3.pm line 1494.
	Gtk3::__ANON__("Gtk3::RadioMenuItem", Gtk3::RadioMenuItem=HASH(0x55910cda6fc8), "Attendre maximum 10 secondes") called at /usr/bin/shutter line 8665
	Shutter::App::fct_ret_web_menu(Gtk3::MenuToolButton=HASH(0x559110c6bf68)) called at /usr/lib/x86_64-linux-gnu/perl5/5.30/Glib/Object/Introspection.pm line 67
	eval {...} called at /usr/lib/x86_64-linux-gnu/perl5/5.30/Glib/Object/Introspection.pm line 67
	Glib::Object::Introspection::__ANON__(Shutter::App=HASH(0x559110003c28)) called at /usr/bin/shutter line 10943
*** Gtk3::RadioMenuItem::new_from_widget: passed too many parameters (expected 2, got 3); ignoring excess at /usr/share/perl5/Gtk3.pm line 1494.
	Gtk3::__ANON__("Gtk3::RadioMenuItem", Gtk3::RadioMenuItem=HASH(0x55910cda6fc8), "Attendre maximum 30 secondes") called at /usr/bin/shutter line 8666
	Shutter::App::fct_ret_web_menu(Gtk3::MenuToolButton=HASH(0x559110c6bf68)) called at /usr/lib/x86_64-linux-gnu/perl5/5.30/Glib/Object/Introspection.pm line 67
	eval {...} called at /usr/lib/x86_64-linux-gnu/perl5/5.30/Glib/Object/Introspection.pm line 67
	Glib::Object::Introspection::__ANON__(Shutter::App=HASH(0x559110003c28)) called at /usr/bin/shutter line 10943
*** Gtk3::RadioMenuItem::new_from_widget: passed too many parameters (expected 2, got 3); ignoring excess at /usr/share/perl5/Gtk3.pm line 1494.
	Gtk3::__ANON__("Gtk3::RadioMenuItem", Gtk3::RadioMenuItem=HASH(0x55910cda6fc8), "Attendre maximum 1 minute") called at /usr/bin/shutter line 8667
	Shutter::App::fct_ret_web_menu(Gtk3::MenuToolButton=HASH(0x559110c6bf68)) called at /usr/lib/x86_64-linux-gnu/perl5/5.30/Glib/Object/Introspection.pm line 67
	eval {...} called at /usr/lib/x86_64-linux-gnu/perl5/5.30/Glib/Object/Introspection.pm line 67
	Glib::Object::Introspection::__ANON__(Shutter::App=HASH(0x559110003c28)) called at /usr/bin/shutter line 10943
*** Gtk3::RadioMenuItem::new_from_widget: passed too many parameters (expected 2, got 3); ignoring excess at /usr/share/perl5/Gtk3.pm line 1494.
	Gtk3::__ANON__("Gtk3::RadioMenuItem", Gtk3::RadioMenuItem=HASH(0x55910cda6fc8), "Attendre maximum 2 minutes") called at /usr/bin/shutter line 8668
	Shutter::App::fct_ret_web_menu(Gtk3::MenuToolButton=HASH(0x559110c6bf68)) called at /usr/lib/x86_64-linux-gnu/perl5/5.30/Glib/Object/Introspection.pm line 67
	eval {...} called at /usr/lib/x86_64-linux-gnu/perl5/5.30/Glib/Object/Introspection.pm line 67
	Glib::Object::Introspection::__ANON__(Shutter::App=HASH(0x559110003c28)) called at /usr/bin/shutter line 10943

fct_update_tray_menu was called by Wnck::Screen=HASH(0x559110097b08)
```

#### Extra information :

Shutter 0.99.2 Rev. 1593
Ubuntu 20.04, Xorg.
French.

About 2nd "issue" for the French translation, I already made the correction [HERE](https://translations.launchpad.net/shutter/trunk/+pots/shutter/fr/+translate?batch=10&show=all&search=abandonn%C3%A9). That's why I am just mentioning this here and not in a dedicated issue, hope this will be enough.

About 3rd minor "issue", that's more of a suggestion. Let me know if it sounds feasible, then I'll do another issue, otherwise we can just forget about it. :)

**Comment by Photon89** [comment]
Hi, thanks for the report and the translation fix! I pushed a PR for the invisible radio button labels (first issue) and put the translation in place (second issue, please review: https://github.com/shutter-project/shutter/pull/444/files).

Regarding the third issue, the Safari-like icon is taken from the current icon theme. In my case it also looks a lot like some Safari icon, but that is what the icon theme offers which I chose to use. It is also the same icon which is used by the DE main menu (in my case Xfce's Whisker menu) for the default web browser. I don't think, we will be able to find a more suiting icon for web capture than the one which is used for the default web browser...

**Comment by Photon89** [comment]
Issues one and two ixed in #443 and #444.
