### ISSUE TITLE
Commands not active

### ISSUE THREAD

**Issue by ValerioTSK** [shutter-project/shutter#441]
Linux Manjaro rolling Gnome 41.2 
Only Desktop command is available on the main window, Selection, Window, Export.... option are not active. I verified all preference with installation on my old linuxbox Mint 20 Cinnamon

**Comment by DarthGandalf** [comment]
Are you using wayland by any chance instead of x11?

**Comment by ValerioTSK** [comment]
Yes, I use Wayland as window system, I mean it's the default option in Manjaro

**Comment by DarthGandalf** [comment]
Shutter has very little support for wayland yet. See #187

**Comment by ValerioTSK** [comment]
Ohhh... thanks anyway
