### ISSUE TITLE
Hotkey in debian 11 cinnamon 4.8.6

### ISSUE THREAD

**Issue by nobef** [shutter-project/shutter#446]
An error occurred while executing 'shutter -f' :: Failed to execute child process 'shutter' (No such file or directory)
 
   Perhaps this is a desktop environment error, because the assigned hotkey does not work in "Diodon" either (the same error) But can anyone know how to fix this?

**Comment by Photon89** [comment]
What if you use the complete path, that is, most probably, `/usr/bin/shutter -f`?

**Comment by nobef** [comment]
@Photon89 The same error.

**Comment by Photon89** [comment]
What if you run the same command from terminal?

**Comment by nobef** [comment]
@Photon89  "No such file or directory"

**Comment by Photon89** [comment]
How did you install Shutter? It is not available in Debian's repos yet, so you most probably had to do some magic. :smiley:

**Comment by nobef** [comment]
@Photon89 Lol, was I wrong? Well, I typed "shutter" in the "application center" and showed me a flameshot https://github.com/flameshot-org/flameshot (I thought maybe the same program). Damn, I'm sorry!

**Comment by Photon89** [comment]
Well, maybe Flameshot has "Shutter" in its description as it has been developed later than Shutter. I'd recommend to give Shutter a go at this point, but unfortunately it is currently quite a hassle to get Shutter running in Debian so you better stick to Flameshot.

**Comment by nobef** [comment]
@Photon89 xD We are waiting for debian then

**Comment by Photon89** [comment]
Yeah, good that you submitted this issue, I pinged the Debian guys again to see what Shutter's status in Debian 12 is. :smile:
