### ISSUE TITLE
How to remove fill color?

### ISSUE THREAD

**Issue by greensleeves01** [shutter-project/shutter#457]
I want the fill color to NOT have a color.  it should be transparent, which, it appears to be, but there is a purple tint inside the fill which is likely pulling from the OS dock  (Fedora 34) and which I set to the color.  But shutter is not part of the OS so why is it pulling the transparency color from the dock?  

There should be a way for shutter NOT to mimic transparencies from the OS it installs to.  In fact, fill should simply be transparent.  Period. NO_COLOR_WHATSOEVER AND NO_COLORS_PULLED_FROM_THE_OS.  

whatever happened to just a transparent fill without color??  

Defeats the entire purpose of a simplistic image editor.  If I wanted to spend days learning GIMP, I would.  It's a sad sad day for Linux when windoze has a bettere image editor that does not require contacting developers to enable the ability for a fill color to be transparent rather than colored.

**Comment by Photon89** [comment]
Would you please add a screenshot demonstrating the issue? I'm having a hard time finding the purple tint on my machine. Thanks!

**Comment by DarthGandalf** [comment]
Why do you need to fill anything at all if you don't want any color? Can you explain what are you trying to do? And yes, screenshots would help

**Comment by rod-farias** [comment]
I have the same question. The rectangle is not transparent:

![Screenshot_20220615_112333](https://user-images.githubusercontent.com/57115850/173866031-095f4f92-367c-4792-acbd-c69b4cb9e6ad.png)
![Screenshot_20220615_112835](https://user-images.githubusercontent.com/57115850/173866332-ba5600d3-b22f-454b-8c9b-c81f42b62a5b.png)

**Comment by Photon89** [comment]
That's because the fill color is set to semitransparent blue, you can change it by clicking the button "Color de relleno" on the bottom left in your first screenshot.

**Comment by rod-farias** [comment]
Yes, I know that button and the color picker. But how do I select the fully transparent fill? Any selection that can be made on that screen is a fully opaque color.

**Comment by rod-farias** [comment]
Oh, I already saw it. In the custom selector, the horizontal bar is the transparency.
Thank you and sorry to use your time.

**Comment by DarthGandalf** [comment]
I suppose, @greensleeves01 had the same issue (except couldn't explain it). If it's not the case, please reopen with more details.
