### ISSUE TITLE
Reduce shutter clutter in /tmp directory.

### ISSUE THREAD

**Issue by ak2766** [shutter-project/shutter#459]
#### Description of requested feature:
Reduce clutter in `/tmp` directory.

#### Reasons for adding feature:
When starting shutter, it loads thumbnails of all screenshots it has taken into the root of `/tmp` folder.  This creates too much clutter in the `/tmp` directory (what can I say, I like a tidy house - 😳).

#### Extra information, such as Shutter version, operating system and ideas for how to implement:
I suggest creating a temporary directory in `/tmp` (say `/tmp/shutter-screenshot-thumbnails`) and placing the thumbnails in there.

**Comment by Photon89** [comment]
That's a dupe: #324. Thanks for the report though!

**Comment by ak2766** [comment]
@Photon89
Apologies.  My laziness is showing; I should have searched first to avoid you having the extra work of cleaning up my mess.

**Comment by Photon89** [comment]
@ak2766 No worries, we aren't flooded with bug reports lately. :smile:
