### ISSUE TITLE
Shutter for dummies

### ISSUE THREAD

**Issue by dickcarr** [shutter-project/shutter#469]
Where will I find a users manual. This version doesn't work like the previous one I had. Selection button greyed out.

**Comment by Photon89** [comment]
Please specify which Shutter version and which distro  you use, and whether you use Xorg or Wayland.

**Comment by DarthGandalf** [comment]
If it's greyed out, it means you're on Wayland, which is not well supported yet (see #187), where only some functionality is available.

To see how it was looking before, relogin to your user using X11 session instead.
