### ISSUE TITLE
Fixed aspect ratio

### ISSUE THREAD

**Issue by jalabaya** [shutter-project/shutter#472]
#### Description of requested feature:

I would like to fix the aspect ratio of my "selection" screenshot.

#### Reasons for adding feature:

For data acquisition purposes it is recommended to have square images.

#### Extra information, such as Shutter version, operating system and ideas for how to implement:

Some image processing software uses the Ctrl key to fix the aspect ratio during resizing. Not sure if that approach would work in this case though.

**Comment by Photon89** [comment]
Thanks for your report, the feature has been already requested in #433.
