### ISSUE TITLE
Problem using shutter after upgrade to 22.04

### ISSUE THREAD

**Issue by nunomdias** [shutter-project/shutter#475]
#### Brief summary of issue
After update to Ubuntu 22.04, shutter stop working. 
I already remove and install but same problem.

#### Steps to reproduce the issue

1. First, the only image that I can screenshot is from desktop
![image](https://user-images.githubusercontent.com/30905441/173357330-5ea3882d-1e47-4c69-9a18-a7856e188b4d.png)

#### Error output

When I try to do a screenshot from desktop I get this message.

![image](https://user-images.githubusercontent.com/30905441/173357629-4eb02e42-0bcc-4d8e-b4ff-ed2808dcf310.png)

#### Extra information, such as Shutter version, display server in use (Xorg or Wayland), operating system and ideas for how to solve:
I'm using Wayland. I think before upgrade I was using Xorg.

**Comment by DarthGandalf** [comment]
> I'm using Wayland

> First, the only image that I can screenshot is from desktop

Correct. See #187 

> When I try to do a screenshot from desktop I get this message.

How did you install shutter?

This looks like a dependency is missing. From https://shutter-project.org/downloads/dependencies/ :

> xdg-desktop-portal (since 0.99.1) for Wayland support

>    You will also need one of its backends installed, such as xdg-desktop-portal-kde, xdg-desktop-portal-gtk, xdg-desktop-portal-wlr, etc. The backend needs to match the wayland compositor you’re using.

**Comment by nunomdias** [comment]
Thanks @DarthGandalf for your reply 

I have been using old repository but when shutter stop working I remove the old repository 
"sudo add-apt-repository -r ppa:linuxuprising/shutter"

and started to work with official repositories, since in Ubuntu 22.04 Shutter is already included.
I have installed with command
"sudo apt install shutter"
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
shutter is already the newest version (0.99.2-4).
The following packages were automatically installed and are no longer required:
  fonts-inter gnome-getting-started-docs libasync-mergepoint-perl
  libdata-random-perl libfuture-perl libgd-perl libigdgmm11 libilmbase24
  libio-async-loop-epoll-perl libio-async-perl libkaccounts1
  libkf5pulseaudioqt2 liblinux-epoll-perl liblua5.1-0 libmetrics-any-perl
  libnet-dropbox-api-perl libopenexr24 libpython3.8 libpython3.8-minimal
  libpython3.8-stdlib libref-util-perl libref-util-xs-perl libsereal-perl
  libstruct-dumb-perl libtest-fatal-perl libtest-metrics-any-perl
  libtest-refcount-perl libtype-tiny-perl libtype-tiny-xs-perl
  libxml-writer-perl libxmlb1 nspluginviewer:i386 nspluginwrapper ruby2.7
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

I also try to reinstall but same problem.

**Comment by Photon89** [comment]
Unfortunately, Ubuntu's package does not list any of those as dependencies, not even as recommended or suggested. So you will have to install `xdg-desktop-portal-gtk` by hand. Not a great solution, but I think, we haven't found a better one yet...

**Comment by nunomdias** [comment]
Thanks @Photon89 . How can I do that? 
I try to install but it give-me information that is already installed.
sudo apt install xdg-desktop-portal-gtk
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
xdg-desktop-portal-gtk is already the newest version (1.14.0-1build1).
xdg-desktop-portal-gtk set to manually installed.
The following packages were automatically installed and are no longer required:
  gir1.2-goocanvas-2.0 libcarp-always-perl libcrypt-openssl-bignum-perl
  libcrypt-openssl-random-perl libcrypt-openssl-rsa-perl libfile-which-perl
  libgoocanvas-2.0-9 libgoocanvas-2.0-common libgoocanvas2-cairotypes-perl
  libgoocanvas2-perl libgtk3-imageview-perl libhttp-server-simple-perl
  libimage-exiftool-perl libjson-perl libmime-charset-perl
  libnet-dbus-glib-perl libnet-oauth-perl libnumber-bytes-human-perl
  libpango-perl libpath-class-perl libproc-simple-perl libreadonly-perl
  libsombok3 libsort-naturally-perl libunicode-linebreak-perl
  libwww-mechanize-perl libx11-protocol-other-perl
Use 'sudo apt autoremove' to remove them.

Can you give-me some hints?
Before upgrade to 22.04 I was using shutter with no problems, this only happend after upgrade

**Comment by Photon89** [comment]
That's weird, is the error message still the same?

> Before upgrade to 22.04 I was using shutter with no problems, this only happend after upgrade

Of course, you were using Xorg before the update, so things were much simpler. In principle, you can switch back to Xorg (in Ubuntu's log in screen) which would fix this problem and also enable all the other capture modes. But if there are reasons for using Wayland, this might be not an option for you.

**Comment by nunomdias** [comment]
Thanks for your reply. 
I will try switch to Xorg since I'm used to work with shutter
