### ISSUE TITLE
Shutter only allows new desktop screen capture option

### ISSUE THREAD

**Issue by philippulus** [shutter-project/shutter#479]
#### Brief summary of issue

Under Ubuntu 22.04, Shutter 0.99.2 Rev 1593 installed from store only allows for Desktop screen capture option.
Any other option such as 'Selection', 'Active Window', 'Select Window', etc... are not active and greyed out. 

#### Steps to reproduce the issue

1. Launch Shutter
2. Click on File, New 
3. See the menu of screen shot options

#### Error output

![Screenshot from 2022-06-26 16-20-15](https://user-images.githubusercontent.com/89039695/175816624-dd408843-af64-4d58-9cc0-47d00784f04b.png)

#### Extra information, such as Shutter version, display server in use (Xorg or Wayland), operating system and ideas for how to solve:

$ inxi -Fxz
System:
  Kernel: 5.15.0-40-generic x86_64 bits: 64 compiler: gcc v: 11.2.0
    Desktop: GNOME 42.2 Distro: Ubuntu 22.04 LTS (Jammy Jellyfish)
Machine:
  Type: Desktop System: Gigabyte product: Z97X-UD5H v: N/A
    serial: <superuser required>
  Mobo: Gigabyte model: Z97X-UD5H v: x.x serial: <superuser required>
    UEFI: American Megatrends v: F10 date: 08/03/2015
CPU:
  Info: quad core model: Intel Core i7-4790 bits: 64 type: MT MCP
    arch: Haswell rev: 3 cache: L1: 256 KiB L2: 1024 KiB L3: 8 MiB
  Speed (MHz): avg: 3964 high: 3988 min/max: 800/4000 cores: 1: 3952
    2: 3955 3: 3988 4: 3939 5: 3982 6: 3965 7: 3951 8: 3984 bogomips: 57468
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: Intel Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics
    vendor: Gigabyte driver: i915 v: kernel bus-ID: 00:02.0
  Device-2: NVIDIA GM200 [GeForce GTX TITAN X] vendor: eVga.com.
    driver: nouveau v: kernel bus-ID: 01:00.0
  Device-3: Microsoft LifeCam HD-3000 type: USB
    driver: snd-usb-audio,uvcvideo bus-ID: 3-10:7
  Display: wayland server: X.Org v: 1.22.1.1 with: Xwayland v: 22.1.1
    compositor: gnome-shell driver: gpu: nouveau resolution: 1: 3840x2160~60Hz
    2: 3840x2160~60Hz
  OpenGL: renderer: NV120 v: 4.3 Mesa 22.0.1 direct render: Yes
Audio:
  Device-1: Intel Xeon E3-1200 v3/4th Gen Core Processor HD Audio
    driver: snd_hda_intel v: kernel bus-ID: 00:03.0
  Device-2: Intel 9 Series Family HD Audio vendor: Gigabyte
    driver: snd_hda_intel v: kernel bus-ID: 00:1b.0
  Device-3: NVIDIA GM200 High Definition Audio vendor: eVga.com.
    driver: snd_hda_intel v: kernel bus-ID: 01:00.1
  Device-4: C-Media CMI8788 [Oxygen HD Audio] vendor: ASUSTeK Virtuoso 100
    driver: snd_virtuoso v: kernel bus-ID: 08:04.0
  Device-5: Microsoft LifeCam HD-3000 type: USB
    driver: snd-usb-audio,uvcvideo bus-ID: 3-10:7
  Device-6: Logitech Headset H340 type: USB
    driver: hid-generic,snd-usb-audio,usbhid bus-ID: 3-5:3
  Sound Server-1: ALSA v: k5.15.0-40-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Intel Ethernet I217-V vendor: Gigabyte driver: e1000e v: kernel
    port: f080 bus-ID: 00:19.0
  IF: eno1 state: down mac: <filter>
  Device-2: Broadcom BCM4360 802.11ac Wireless Network Adapter
    vendor: ASUSTeK driver: wl v: kernel bus-ID: 02:00.0
  IF: wlp2s0 state: up mac: <filter>
  Device-3: Qualcomm Atheros Killer E220x Gigabit Ethernet vendor: Gigabyte
    driver: alx v: kernel port: d000 bus-ID: 04:00.0
  IF: enp4s0 state: down mac: <filter>
Drives:
  Local Storage: total: 931.51 GiB used: 465.07 GiB (49.9%)
  ID-1: /dev/nvme0n1 vendor: Smart Modular Tech. model: SHGP31-1000GM-2
    size: 931.51 GiB temp: 45.9 C
Partition:
  ID-1: / size: 912.73 GiB used: 464.82 GiB (50.9%) fs: ext4 dev: /dev/dm-1
    mapped: vgubuntu-root
  ID-2: /boot size: 1.61 GiB used: 252 MiB (15.3%) fs: ext4
    dev: /dev/nvme0n1p2
  ID-3: /boot/efi size: 511 MiB used: 5.2 MiB (1.0%) fs: vfat
    dev: /dev/nvme0n1p1
Swap:
  ID-1: swap-1 type: partition size: 976 MiB used: 0 KiB (0.0%)
    dev: /dev/dm-2 mapped: vgubuntu-swap_1
Sensors:
  System Temperatures: cpu: 29.8 C mobo: 27.8 C gpu: nouveau temp: 57.0 C
  Fan Speeds (RPM): N/A gpu: nouveau fan: 1047
Info:
  Processes: 312 Uptime: 33m Memory: 31.17 GiB used: 5.07 GiB (16.3%)
  Init: systemd runlevel: 5 Compilers: gcc: 11.2.0 Packages: 2064 Shell: Bash
  v: 5.1.16 inxi: 3.3.13

**Comment by Photon89** [comment]
That's because Shutter has only rudimentary Wayland support: #187 You can switch your desktop session to Xorg to get all the other capture modes.
