### ISSUE TITLE
Ability to change time format

### ISSUE THREAD

**Issue by t-rexamarin** [shutter-project/shutter#484]
At the moment there is only one time format, which we can use in screenshot name - %T.
It will save time using colon to separate numbers - 09:27:38.
Some software, as example - jira, do no want to validate files which contains in name colon.
Asking for ability to set your own separator for time.
Probably manual input of time format as %h (hours), %m (minutes), %s (seconds).

**Comment by Photon89** [comment]
It actually already works, however with %H, %M and %S, as is documented in the `date` manpage: https://man7.org/linux/man-pages/man1/date.1.html The information could be added to the tooltip though, maybe also a hint to check out this manpage for further wildcards.

**Comment by t-rexamarin** [comment]
Indeed. Thanks.
