### ISSUE TITLE
Plugin Error: Hard Shadow not working 

### ISSUE THREAD

**Issue by aproposnix** [shutter-project/shutter#498]
#### Brief summary of issue
Drop shadow pliugin doesn't work

#### Steps to reproduce the issue

1. from an image, select "run a plugin"
2. CLick on the hard shadow plugin
3. Plugin opens > Run the plugin
4. Error 

#### Error output
```

fct_update_tray_menu was called by Wnck::Screen=HASH(0x5570f9f81178)
Redundant argument in printf at /usr/bin/shutter line 6815.
	Shutter::App::fct_execute_plugin(undef, ARRAY(0x5570f78c2170)) called at /usr/bin/shutter line 10063
	Shutter::App::dlg_plugin("[3] - Workspace 1_001.png") called at /usr/bin/shutter line 5699
	Shutter::App::fct_plugin(Gtk3::ImageMenuItem=HASH(0x5570fa7b6e60)) called at /usr/lib/x86_64-linux-gnu/perl5/5.34/Glib/Object/Introspection.pm line 67
	eval {...} called at /usr/lib/x86_64-linux-gnu/perl5/5.34/Glib/Object/Introspection.pm line 67
	Glib::Object::Introspection::__ANON__(Shutter::App=HASH(0x5570f9f7f698)) called at /usr/bin/shutter line 10943
```

#### Extra information, such as Shutter version, display server in use (Xorg or Wayland), operating system and ideas for how to solve:

OS: Ubuntu 22.04 
Running X NOT Wayland

![image](https://user-images.githubusercontent.com/6204273/184591626-23b99c5e-a879-4aed-b987-309927e30d3a.png)

**Comment by Photon89** [comment]
It works for me. What is your imagemagick version?

`convert --version`

**Comment by aproposnix** [comment]
@Photon89 thank you for the feedback. It turns out it was a imagemagick issue. In ubuntu, for some reason, a compatibility version was installed. After installing the regular version it works fine. Thank you. 

![image](https://user-images.githubusercontent.com/6204273/184819364-121ab4bb-d8f2-40a7-b7e1-7835e7c7c842.png)
