### ISSUE TITLE
SHUTTER button to fast screenshot

### ISSUE THREAD

**Issue by wtfkimi** [shutter-project/shutter#499]
Is there available to configure button, which will do capture of screen?

**Comment by Photon89** [comment]
You can add keybindings in your DE's keyboard settings. Say, you could map the Print button to the command "shutter -f" to get a full screen screenshot.

**Comment by wtfkimi** [comment]
Hmm, found this type of settings. Than you so much :)

**Comment by Photon89** [comment]
Great, you're welcome! :smiley:
