### ISSUE TITLE
After Ubuntu upgrade to 22.04.1 upgrade the function "selection" no longer opens in Shutter

### ISSUE THREAD

**Issue by Garoolgan** [shutter-project/shutter#500]
After Ubuntu upgrade to 22.04.1  the function "selection" no longer opens in Shutter. It is there but "greyed out".
I can however take a screenshot.
I have tried removing Shutter through "Ubuntu software" but I receive a reply "unable to remove shutter: no packages to remove".
Any ideas for a Novice ?
Thanks in advance
Bob

**Comment by Photon89** [comment]
That's #187, Shutter has only rudimentary Wayland support, you can switch to Xorg to get back full functionality.

**Comment by Garoolgan** [comment]
Thanks for the "Xorg" tip, it saved my day ! - Bob alias Garoolgan

**Comment by Photon89** [comment]
You're welcome! Closing, please comment if further issues arise.
