### ISSUE TITLE
How to use Shutter In Windows

### ISSUE THREAD

**Issue by JWillOfGmail** [shutter-project/shutter#508]
Hi.

I'm writing now from an Ubuntu machine which runs Shutter well.

I'll soon be getting a new computer which runs Windows 10.   I plan to reformat it for Windows 7 and Ubuntu.

Question #1: Is there any way to use Shutter in Windows?

Question #2: How good a Shutter substitute is the GNU Image Manipulation Program (which can run in Windows)?

Question #3: Is there ANY good Shutter substitute for Windows?

**Comment by DarthGandalf** [comment]
> Is there any way to use Shutter in Windows?

Shutter relies on X11 (or Wayland) to take the picture, neither X11 nor Wayland are normally used on Windows. It is possible to run X11 server on Windows, but then screenshot functionality will be limited only to other clients of the same X11 server.

> How good a Shutter substitute is the GNU Image Manipulation Program (which can run in Windows)?

Does Gimp take screenshots on Windows?
