### ISSUE TITLE
Cannot select area for screenshot

### ISSUE THREAD

**Issue by Jagyashila** [shutter-project/shutter#512]
#### Steps to reproduce the issue

1. Launch the app
2. Take screenshot

#### Extra information, such as Shutter version, display server in use (Xorg or Wayland), operating system and ideas for how to solve:
Previous version used to come with a pointer where the user was given a choice to grab specific areas for screenshots. This bug is very irritating, as it has rendered Shutter useless.

**Comment by DarthGandalf** [comment]
Are you using wayland? if so, switch to x11. You should have provided that information in the details of the bug, it even asks for that.
#187

**Comment by Photon89** [comment]
Closing as duplicate, please comment if you need further assistance.
