### ISSUE TITLE
Linux Manjaro: Features not availables

### ISSUE THREAD

**Issue by ValerioTSK** [shutter-project/shutter#513]
#### Brief summary of issue
Selection and Windows captures are not availables. Some other menu/button option doesen't work

#### Steps to reproduce the issue

1. Open Shutter
2. Menu/button commands not active
3. 

#### Extra information, such as Shutter version, display server in use (Xorg or Wayland), operating system and ideas for how to solve:
Shutter vers. 0.99.2 Rev.1593
My system 
![image](https://user-images.githubusercontent.com/82206423/201163280-3fe8ada9-1e8c-4a45-a213-170f8e4f0952.png)

**Comment by Photon89** [comment]
That's #187, Shutter has only rudimentary Wayland support, if you want to get all features, you would have to switch to Xorg.

**Comment by Photon89** [comment]
Closing as duplicate, please comment, if you need further assistance.
