### ISSUE TITLE
Capture a Window currently not working

### ISSUE THREAD

**Issue by francescoingv** [shutter-project/shutter#515]
#### Brief summary of issue
The function 

#### Steps to reproduce the issue

1. Select the drop down button next to Window button
2. Click on the window name from which you want to take the screenshot
3. 

#### Error output
The screenshot shows a picture with dimensions smaller than the selected window,
whose center is moved right and down, showing also part of the desktop (and possibly other windows below)

#### Extra information, such as Shutter version, display server in use (Xorg or Wayland), operating system and ideas for how to solve:
Shutter 0.99.2 Rev. 1593
Graphics: NV166 / Mesa Intel(r) UHD Graphics 630 (CML GT2)
Resolution 3480X2160; Scale 200
O.S. Ubuntu 20.04.5

Note: the application was working as expected until a month ago

Attached is a test trying to take the screenshot of Shutter, with below this window page.
![Session - Shutter_001](https://user-images.githubusercontent.com/9592487/201653651-fab812dd-fb31-4aaa-84f8-6f6f133cf9d2.png)

**Comment by Photon89** [comment]
Were there any notable changes during the last month? For example changes in screen resolution or scaling?

**Comment by nbx3** [comment]
I'm on Ubuntu 22.04.1 LTS with Gnome 42.5 on Wayland and only Desktop screenshot option is available, selection and window are greyed out/disabled. I'm running Shutter 0.99.2 Rev 1593

**Comment by Photon89** [comment]
@nbx3 That's a different issue, #187. Switch to Xorg to get back the full functionality.

**Comment by Photon89** [comment]
@FrancescoIngv Is this thill an issue?

**Comment by francescoingv** [comment]
I did not experience the issue anymore, as I changed the scale.

Thank you,
Francesco

**Comment by Photon89** [comment]
Thanks for getting back to this issue, I'm closing it then!
