### ISSUE TITLE
Wie öffne ich Shutter Screenshott?

### ISSUE THREAD

**Issue by hjsent** [shutter-project/shutter#516]
Möchte mit Shutter Screenshott arbeiten, wie öffne ich Shutter Screenshott?

**Comment by Photon89** [comment]
Der Befehl ist "shutter", aber eigentlich sollte auch ein Eintrag im Startmenü vorhanden sein.

**Comment by Photon89** [comment]
Ich hoffe, ich konnte die Frage beantworten, falls nicht, bitte einfach nochmal kommentieren.
