### ISSUE TITLE
Constrain aspect ratio

### ISSUE THREAD

**Issue by visjble** [shutter-project/shutter#517]
I would really like Shutter to have a checkbox that constrains the aspect ratio of the manual width and height values. Eg, I set the W and H to be 512x512px (popular size recently)and then I am able to drag that square around the screen as I see fit. However, if I want to resize it prior taking the shot it looses the aspect ratio. I would like to be able to drag the corner of the square mantaining the same ratio. Perhaps a feature that can be accessed via terminal as well.
Thanks!!

**Comment by Photon89** [comment]
Thanks for the idea, it has been proposed already though: https://github.com/shutter-project/shutter/issues/433 Closing as duplicate, discussions can go to the earlier issue.
