### ISSUE TITLE
mr tony

### ISSUE THREAD

**Issue by tonyfromspace** [shutter-project/shutter#518]
new install of Shutter 0.99.2 on ubuntu 22.04 doesn't work. "Selection" remains greyed out. says 
can't take screenshotss without X11 server. I think I have an X11 server which I use with xterm, etc.
What am I missing?
tony@Opti-9020:~$ ps -ef|grep xterm
tony        2973    1985  0 Nov27 ?        00:01:23 xterm
tony        4419    1985  0 Nov27 ?        00:00:00 xterm
tony       52049    4422  0 11:21 pts/1    00:00:00 grep --color=auto xterm

**Comment by Photon89** [comment]
I assume, xterm can also run on Wayland. Please try `ps -ef|grep Xorg` directly.

You can switch to Xorg in your login screen, in case it is the Wayland problem.

**Comment by tonyfromspace** [comment]
Nail on head. Somehow I slept through all the Wayland/Xorg drama. Works OK
if I swap Xorg in (and presumably
Wayland out).

Thanks for taking time to give a pointer.
Mr Tony

**Comment by Photon89** [comment]
Great, then happy screenshot taking! :smiley:
