### ISSUE TITLE
Only the Desktop capture mode is available on Ubuntu 22.10.

### ISSUE THREAD

**Issue by hongyi-zhao** [shutter-project/shutter#519]
Hi here,

On Ubuntu 22.10, I installed the latest version of shutter using the trick discussed [here](https://github.com/shutter-project/shutter/issues/395#issuecomment-898993972). But I found that only the Desktop capture mode is available, as shown below:

![image](https://user-images.githubusercontent.com/11155854/205491989-98d200a5-fa13-4cc4-9b13-acf050b4633f.png)

Any tips and comments will be appreciated.

Regards,
Zhao

**Comment by Photon89** [comment]
That's #187, please switch to Xorg to get back full functionality.

**Comment by hongyi-zhao** [comment]
Yes. Based on the tip [here](https://askubuntu.com/questions/1410256/how-do-i-use-x-instead-of-wayland-on-22-04), the following setting fixed this problem:

```shell
$ sudo nano /etc/gdm3/custom.conf
[daemon]
# Uncomment the line below to force the login screen to use Xorg
WaylandEnable=false
```
