### ISSUE TITLE
dpkg-query: no packages found matching gnome-web-photo

### ISSUE THREAD

**Issue by hongyi-zhao** [shutter-project/shutter#520]
I'm using Ubuntu 22.10, as shown below:

```shell
$ lsb_release -a 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.10
Release:	22.10
Codename:	kinetic
```
In this version, Ubuntu hasn't `gnome-web-photo` package as described [here](https://launchpad.net/~shutter/+archive/ubuntu/ppa):

```
You may also install the optional gnome-web-photo (which depends on some old libraries) from this PPA to capture full website screenshots with Shutter:

$ sudo apt install gnome-web-photo
```
See the following information for more details:
```
$ dpkg -l gnome-web-photo
dpkg-query: no packages found matching gnome-web-photo
```
Any comments for this problem?

Regards,
Zhao

**Comment by Photon89** [comment]
See #285, it's the last remaining outdated dependency which Shutter still has.
