### ISSUE TITLE
clicking new "Selection" doesn't work to capture at all in Ubuntu22

### ISSUE THREAD

**Issue by jernelson** [shutter-project/shutter#527]
#### Steps to reproduce the issue

1.  open shutter, 
2. "selection" option is greyed out
3.

**Comment by jernelson** [comment]
Version, 0.99.2-4 , installed on Ubuntu 22.04

**Comment by jernelson** [comment]
oops, later I googled this exact error and found this fix/work around for Ubuntu21,  seems to have fixed U22 too:

I found a solution. In this file sudo nano /etc/gdm3/custom.conf uncomment this line WaylandEnable=false save and exit. Then run this command in the terminal sudo systemctl restart gdm3 Happy Ubuntu :)

**Comment by Photon89** [comment]
Yep, that's our bug #187 here. ;)
