### ISSUE TITLE
Selection button is inactive

### ISSUE THREAD

**Issue by viciu** [shutter-project/shutter#529]
#### Brief summary of issue

I cannot take a screenshot - selection button is inactive

![image](https://user-images.githubusercontent.com/56233/208247719-2ad47a91-96db-44e8-aa81-f61ba98f75c1.png)

#### Steps to reproduce the issue

* shutter version 0.99.2 Rev.1593
* Debian 10

**Comment by Photon89** [comment]
That's https://github.com/shutter-project/shutter/issues/187, Shutter has only rudimentary Wayland support, you can switch to Xorg to get back full functionality.
