### ISSUE TITLE
Don't work with burn-my-windows

### ISSUE THREAD

**Issue by Nasdrovia69** [shutter-project/shutter#530]
#### Brief summary of issue
shutter does not disappear when take a selection
and remains in front of the area you wish to select

#### Steps to reproduce the issue

1. install burn-my-windows hexagon
2. launch shutter
3. take selection
4. 

#### Extra information, such as Shutter version, display server in use (Xorg or Wayland), operating system and ideas for how to solve:
Fedora 37 Kde Xorg  
add keyboard shortcut to take selection

**Comment by Nasdrovia69** [comment]
I love shutter but Programmable keyboard shortcuts would be very useful

**Comment by Nasdrovia69** [comment]
for the moment I found a way to avoid this, I move the shutter window as far down as possible and I can take a selection on the area of the screen that interests me
Nice I can continue to use shutter

**Comment by vadi2** [comment]
You can also put in a delay for a screenshot - 3s. That's what I do with burn my windows.

**Comment by Photon89** [comment]
Does Shutter not disappear at all, or does it disappear too late, so it is visible on the screenshot?

**Comment by Nasdrovia69** [comment]
In fact, it disappear too late, and it is visible on the screenshot, but the solution I found still suits me quite well
vadi2 how you put a delay for a screenshot 
in preferences, it is not possible to indicate negative values ? In a config file ?

**Comment by Photon89** [comment]
I think, the value should be positive.

I am puzzled that the issue exists, actually. I use Compiz which also has some window animation effects and never had this issue, even when setting the delay to 0. Is it possible to set the animation duration in burn-my-windows? It is set to 300ms in my Compiz settings and works well with Shutter.

**Comment by Nasdrovia69** [comment]
Yes, I try with 300ms but I lose part of the effect that makes the charm of hexagon, it is too fast, I will stay with the solution of moving the shutter window down

**Comment by DarthGandalf** [comment]
This delay is configured here:
![Выделение_441](https://user-images.githubusercontent.com/325092/208304356-84c2fd97-453e-40b9-8b28-f08f5440aadb.png)

Currently it's capped at 1000ms though

**Comment by DarthGandalf** [comment]
It should work if you make this delay bigger than the hexagon's duration

**Comment by vadi2** [comment]
Delay for me can be up to 3s - configurable bottom-left of the main window

(can't show a screenshot - I'm on a Chromebook and Shutter is not trivial to install in Debian)

**Comment by DarthGandalf** [comment]
No, that's a different delay: the one in main window is to make the screenshot essentially twice. First just to draw the area which take the screenshot of, then this delay, then actual screenshot of the selected area.

The delay in settings is between making the window disappear, and starting drawing the area.

**Comment by Photon89** [comment]
@Nasdrovia69 Could you solve the problem by increasing Shutter's redraw delay as proposed by DarthGandalf?

**Comment by Nasdrovia69** [comment]
Like I say #https://github.com/shutter-project/shutter/issues/530#issuecomment-1356807805
I lost effect with this solution, I prefer moving shutter windows down 
I close the Issue however

**Comment by Photon89** [comment]
@Nasdrovia69 As far as I understood, you tried to reduce the effect duration in burn-my-windows, but the proposal was to increase the redraw duration in Shutter, see https://github.com/shutter-project/shutter/issues/530#issuecomment-1356813073

**Comment by DarthGandalf** [comment]
Yes, these are different delays.
