### ISSUE TITLE
Selection is not working / disabled 

### ISSUE THREAD

**Issue by abdurrahimstockton** [shutter-project/shutter#540]
#### Steps to reproduce the issue

1. sudo apt install shutter and launch shutter in Ubuntu 22.04
2. try to use  Selection  or click on Desktop to take a screenshot of a specific area in the desktop 
3. Expected --should be able to take screen shot , Actual --Selection and other pieces are disabled. Not able to take screen shot.

**Comment by Photon89** [comment]
That's a known issue: https://github.com/shutter-project/shutter/issues/187 You need to switch to Xorg if you want to get full functionality in Shutter.
