### ISSUE TITLE
Shutter option keeps opening $HOME dir in file manager when I try to do a screen capture

### ISSUE THREAD

**Issue by jelabarre59** [shutter-project/shutter#544]
#### Brief summary of issue
Shutter's "selection" option to 
#### Steps to reproduce the issue
1. Bring up Shutter to take a screenshot of a selected part of my desktop
2. I have two windows open, and I want to capture the overlap between two windows
3. Even though my file manager (Nemo) is closed, as soon as the selection box comes up, my home directory comes  up and covers the area I'm trying to select
4. Even if I have the Nemo up but with /tmp selected, as soon as I bring up the selection window it switches BACKK to my home directory

OR

1. bring up shutter to capture the entire desktop
2. even though the file manager is closed, the resulting screenshot of the entire desktop has opened my home directory in my file manager, and is on top of the very section I wanted to get a copy of.  Not even in a different corner.

#### Extra information, such as Shutter version, display server in use (Xorg or Wayland), operating system and ideas for how to solve:
 Shutter 0.99.2
Fedora 37
Cinnamon Desktop 5.6 (Nemo file manager)
Xorg

**Comment by Photon89** [comment]
Is it possibly capturing an outdated screen state? That is, the file manager has been opened in the past and this is what Shutter captures? In this case, it might be a duplicate of #523 which ultimately is a problem related to GTK (see discussion in the linked issue).

**Comment by jelabarre59** [comment]
Ah, of *course* it's yet more broken-ness in GTK.  How utterly surprising.
