### ISSUE TITLE
I can't use the button Selection after installing Shutter on Ubuntu 22.04

### ISSUE THREAD

**Issue by Rosie2000** [shutter-project/shutter#547]
#### Brief summary of the issue
I can hit the button Selection

#### Steps to reproduce the issue

1. Install Shutter (the newest version 0.99.2-4) on Ubuntu 22.04
2. Open Shutter to capture a specific area of my screen
3. The Selection button and some others are blurred, only the Desktop button is bold

#### Error output
I can hit the button Selection

**Comment by Photon89** [comment]
That's https://github.com/shutter-project/shutter/issues/187 You can switch to a Xorg session to get back the full functionality.

**Comment by Rosie2000** [comment]
> That's #187 You can switch to a Xorg session to get back the full functionality.

Thanks bro! I fix it well

**Comment by Photon89** [comment]
You're welcome! Closing.
