### ISSUE TITLE
Can only do full desktop capture

### ISSUE THREAD

**Issue by ahazi** [shutter-project/shutter#550]
#### Brief summary of issue
All other options are grayed out

#### Steps to reproduce the issue

1. 
2. 
3. 

#### Extra information, such as Shutter version, display server in use (Xorg or Wayland), operating system and ideas for how to solve:
Shutter version 0.99.2
Ubuntu 22.04
Xorg ver 1.22.1.1

**Comment by DarthGandalf** [comment]
>  Xorg ver 1.22.1.1

Lies. You're using wayland, not Xorg, and this is #187

**Comment by ahazi** [comment]
Thank you!
