### ISSUE TITLE
Update 0.99.3-1 broken on Arch Linux

### ISSUE THREAD

**Issue by delinuxco** [shutter-project/shutter#559]
#### Brief summary of issue
Upgraded to 0.99.3-1 shutter no longer loads.

#### Steps to reproduce the issue

1. update package
2. 
3. 

#### Error output
Will not start

"perl-moo" is not marked as a dependency in the Arch package, therefore after package update, Shutter will not load. Installing perl-moo package, installed all additional packages needed and Shutter fired right up.

It would seem that adding perl-moo as a required package would fix the issue.

**Comment by Photon89** [comment]
This is a packaging issue which is tracked downstream: https://bugs.archlinux.org/task/77758?project=5&string=shutter
