### ISSUE TITLE
Redo last screenshot does not respect the new delay time

### ISSUE THREAD

**Issue by hsandt** [shutter-project/shutter#563]
#### Brief summary of issue

Reboot of https://bugs.launchpad.net/shutter/+bug/1020381 since issues seem to have moved to GitHub

More info on use case: after doing a bad screenshot, I want to repeat it with a different delay, generally a longer one to give me time to make it right. But the old delay is reused, so I need to redo the last screenshot manually, selecting the correct area, etc.

#### Steps to reproduce the issue

1. Do a screenshot with delay of 1s
2. Set delay to 4s
3. Click Redo last screenshot button

#### Result

The screenshot is repeated with only 1s of delay.

#### Extra information, such as Shutter version, display server in use (Xorg or Wayland), operating system and ideas for how to solve:

Shutter v0.99.2
Ubuntu 22.04 with Unity desktop

**Comment by hsandt** [comment]
Right now we got a bigger issue: https://github.com/shutter-project/shutter/issues/560 which covers this one: Even I redo my screenshots manually, the new delay is not taken into account and I only have 1-2 seconds whatever. So we need to fix that one first.

**Comment by Photon89** [comment]
As far as I understand, the "Redo" button repeats the previous capture in exactly the same manner, that is, also using the previous delay setting. So the behavior is intended this way.

**Comment by hsandt** [comment]
OK. I opened a feature request instead, so closing this issue.
