### ISSUE TITLE
segfault at launch in fedora 38 beta

### ISSUE THREAD

**Issue by Chevek** [shutter-project/shutter#568]
#### Brief summary of issue
It crash at launch in fedora 38 beta.

#### Steps to reproduce the issue

1. install the rpm and launch it
2. segfault

#### Error output
ns_changed was emitted by widget Gtk3::ComboBoxText=HASH(0x5633130fcdc0)
Can't locate object method "remove_submenu" via package "Gtk3::MenuItem" at /usr/bin/shutter line 7174, <DATA> line 19.
	Shutter::App::fct_update_profile_selectors(Gtk3::ComboBoxText=HASH(0x563312e96c10), ARRAY(0x563310bdb628)) called at /usr/bin/shutter line 2687
	Shutter::App::STARTUP(Shutter::App=HASH(0x5633125a5788)) called at /usr/lib64/perl5/vendor_perl/Glib/Object/Introspection.pm line 67
	Glib::Object::Introspection::__ANON__(Shutter::App=HASH(0x5633125a5788)) called at /usr/bin/shutter line 10922
Erreur de segmentation (core dumped)

#### Extra information, such as Shutter version, display server in use (Xorg or Wayland), operating system and ideas for how to solve:
0.99.3 Rev.1607

**Comment by Photon89** [comment]
This is fixed in 0.99.4: https://github.com/shutter-project/shutter/issues/561

**Comment by Chevek** [comment]
Indeed, here is how to install Shutter 0.99.4 on fedora 38 :

Download and extract the source:
[https://github.com/shutter-project/shutter/releases/tag/v0.99.4](url)

Install dependencies :
`sudo dnf install make gettext perl-Test-MockModule.noarch ImageMagick ImageMagick-perl hicolor-icon-theme libwnck3 perl-Carp-Always perl-Data-Dumper perl-Digest-MD5 perl-Encode perl-Encode-Locale perl-English perl-Exporter perl-File-Basename perl-File-Copy perl-File-Copy-Recursive perl-File-Temp perl-File-Which perl-File-stat perl-FindBin perl-Getopt-Long perl-Glib perl-Glib-Object-Introspection perl-Goo-Canvas perl-GooCanvas2 perl-GooCanvas2-CairoTypes perl-Gtk3 perl-Gtk3-ImageView perl-HTTP-Message perl-IO perl-Image-ExifTool perl-JSON-MaybeXS perl-Locale-gettext perl-MIME-Base64 perl-Moo perl-Net-DBus perl-Number-Bytes-Human perl-POSIX perl-Pango perl-Path-Class perl-PathTools perl-Pod-Usage perl-Proc-ProcessTable perl-Proc-Simple perl-Scalar-List-Utils perl-Sort-Naturally perl-Time-HiRes perl-URI perl-X11-Protocol-Other perl-XML-Simple perl-constant perl-diagnostics perl-lib perl-libnet perl-libs perl-libwww-perl tango-icon-theme`

Go the source folder and install shutter :
`sudo make install`

Best regards

**Comment by Cardiacman13** [comment]
THX
