### ISSUE TITLE
Shutter causes coredump at every launch

### ISSUE THREAD

**Issue by Sterntrix** [shutter-project/shutter#571]
#### Brief summary of issue
Every time I start shutter I get a coredump.  It happens while reading plugins.
I uninstalled, removed all traces of configuration in user home and reinstalled.
Same result.

#### Steps to reproduce the issue

1. start shutter from command line
2. 
3. 

#### Error output
see attached file output of error messages:  shuttererrors.txt

#### Extra information, such as Shutter version, display server in use (Xorg or Wayland), operating system and ideas for how to solve:
[shuttererrors.txt](https://github.com/shutter-project/shutter/files/11105346/shuttererrors.txt)

**Comment by Sterntrix** [comment]
Fedora release 37 (Thirty Seven)

**Comment by DarthGandalf** [comment]
Known issue. This was fixed in 0.99.4

**Comment by Sterntrix** [comment]
Thanks. I guess I will have to wait for the fedora repo to switch to the
latest release.

**Comment by DarthGandalf** [comment]
Either that, or you can edit your /usr/bin/shutter similar to this: https://github.com/shutter-project/shutter/commit/4c885f70426c3bc84b899c3e6e9ee372f5794bd7

**Comment by Sterntrix** [comment]
Thanks.  I made that edit and it works now.
Your help was much appreciated.
