### ISSUE TITLE
Can take only 1 screenshot.

### ISSUE THREAD

**Issue by Thamone** [shutter-project/shutter#572]
#### Brief summary of issue
When I try to take a 2nd screenshot using "Selection" without closing the shutter first, no matter what is on the screen, it always goes back to the first screen from which I took the 1st screenshot. If I select "Desktop" or "Window" I get a screenshot of the first screen.

I have to quit Shutter(on systray) before I can take another screenshot.

#### Steps to reproduce the issue

1. Open Shutter from the menu or keyboard shortcut.
2. Take a screenshot.
3. Change what appears on the screen.
4. Take another screenshot.
5. Always get the same picture.
6. reinstall from another source again and again, still the same.

#### Extra information, such as Shutter version, display server in use (Xorg or Wayland), operating system and ideas for how to solve:
Shutter version : 0.99.2 from Manjaro Repo or 0.99.4 from AUR
OS : Manjaro

**Comment by Photon89** [comment]
Seems like a duplicate of https://github.com/shutter-project/shutter/issues/523 Which GTK version are you using?

**Comment by Thamone** [comment]
> Seems like a duplicate of #523 Which GTK version are you using?

2.24.33
3.24.36
4.8.3

**Comment by Photon89** [comment]
Ok, please downgrade gtk3 to 3.24.35-1 as a workaround.

**Comment by Thamone** [comment]
Thank you.
