### ISSUE TITLE
Fedora 37: Can't locate object method "remove_submenu" via package "Gtk3::MenuItem"

### ISSUE THREAD

**Issue by ilovepumpkin** [shutter-project/shutter#576]
#### Brief summary of issue

I installed Shutter on Fedora 37, but saw the following error when launching it.

```
ns_changed was emitted by widget Gtk3::ComboBoxText=HASH(0x55fadbe084b8)
Can't locate object method "remove_submenu" via package "Gtk3::MenuItem" at /usr/bin/shutter line 7174, <DATA> line 19.
	Shutter::App::fct_update_profile_selectors(Gtk3::ComboBoxText=HASH(0x55fadbba5ef0), ARRAY(0x55fad957bb78)) called at /usr/bin/shutter line 2687
	Shutter::App::STARTUP(Shutter::App=HASH(0x55fadb5a2f78)) called at /usr/lib64/perl5/vendor_perl/Glib/Object/Introspection.pm line 67
	Glib::Object::Introspection::__ANON__(Shutter::App=HASH(0x55fadb5a2f78)) called at /usr/bin/shutter line 10922
Segmentation fault (core dumped)
```

#### Steps to reproduce the issue

1.  Install from fedora 37 official repoisitory
2.  Launch it via command line
3. 

#### Error output
```
ns_changed was emitted by widget Gtk3::ComboBoxText=HASH(0x55fadbe084b8)
Can't locate object method "remove_submenu" via package "Gtk3::MenuItem" at /usr/bin/shutter line 7174, <DATA> line 19.
	Shutter::App::fct_update_profile_selectors(Gtk3::ComboBoxText=HASH(0x55fadbba5ef0), ARRAY(0x55fad957bb78)) called at /usr/bin/shutter line 2687
	Shutter::App::STARTUP(Shutter::App=HASH(0x55fadb5a2f78)) called at /usr/lib64/perl5/vendor_perl/Glib/Object/Introspection.pm line 67
	Glib::Object::Introspection::__ANON__(Shutter::App=HASH(0x55fadb5a2f78)) called at /usr/bin/shutter line 10922
Segmentation fault (core dumped)
```

#### Extra information, such as Shutter version, display server in use (Xorg or Wayland), operating system and ideas for how to solve:

Tried in Gnome and i3wm.

**Comment by Photon89** [comment]
Version 0.99.4 fixing the issue is already in testing: https://packages.fedoraproject.org/pkgs/shutter/shutter/

**Comment by ilovepumpkin** [comment]
> Version 0.99.4 fixing the issue is already in testing: https://packages.fedoraproject.org/pkgs/shutter/shutter/

@Photon89  Thank you for quick response! When will 0.99.4 be available to update? Is there any outlook date?

**Comment by Photon89** [comment]
Unfortunately, I don't know, maybe @martinkg can tell more.

**Comment by ilovepumpkin** [comment]
@Photon89  Okay, it's fine. I tried to install https://kojipkgs.fedoraproject.org//packages/shutter/0.99.4/1.fc37/noarch/shutter-0.99.4-1.fc37.noarch.rpm and it is launched now. Thank you!

**Comment by Photon89** [comment]
You're welcome! I think, you can switch back to the official repo package in a few days (unless this happens automatically with the next package update).
