### ISSUE TITLE
Shutter editor icons are almost invisible in dark theme Desktop Environment

### ISSUE THREAD

**Issue by tethragon** [shutter-project/shutter#578]
#### Brief summary of issue
The icons of the shutter editor are almost invisible in Dark Theme DE

#### Steps to reproduce the issue

1. Open shutter while using a dark themed DE
2. Open shutter editor
3. Watch as many icons are very hard to distinguish

#### Error output
None

#### Extra information, such as Shutter version, display server in use (Xorg or Wayland), operating system and ideas for how to solve:
My system specs: https://docs.google.com/document/d/1yYK4Rx4Mu-XeaO9YiiDxI79BS17ge_5pYAdPank6K84/edit?usp=sharing

An idea to solve the problem is either chose colors for the icons that can be distinguished both in dark or light environment or implement an extra icon set for dark themes and allow the user to select it in shutter settings.

![Screenshot from 2023-04-11 14-07-29](https://user-images.githubusercontent.com/39238674/231145455-1dea18aa-5045-4df6-b98c-37f7d2b70982.png)

**Comment by Photon89** [comment]
Thanks for the report, we already discussed this in https://github.com/shutter-project/shutter/issues/382 but so far couldn't figure out a good way to solve the issue...

**Comment by Photon89** [comment]
Let's continue the discussion in #382, I'll close this one!

**Comment by pmorch** [comment]
Another option is to just not use the dark theme, like so:

```shell
$ GTK_THEME=Adwaita shutter
```
