### ISSUE TITLE
shutter segfaults on right click on preview with Glib-Object-Introspection-0.050

### ISSUE THREAD

**Issue by christian-heusel** [shutter-project/shutter#583]
#### Brief summary of issue
Shutter crashes with SIGSEGV when one right-clicks on a image preview.
This was first reported in the archlinux bugtracker (https://bugs.archlinux.org/task/78377) where one can also find a backtrace.

#### Steps to reproduce the issue

1. open shutter
2. create a screenshot
3. right-click on the preview image
4. see shutter segfault

#### Error output
https://gist.github.com/christian-heusel/fdeda83827c6608f6fce6f94003b4e5a

#### Extra information, such as Shutter version, display server in use (Xorg or Wayland), operating system and ideas for how to solve:
- OS: Archlinux `Linux meterpeter 6.3.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 01 May 2023 17:42:39 +0000 x86_64 GNU/Linux`
- Shutter version: `0.99.4-1` as installed per https://archlinux.org/packages/community/any/shutter/
- Xorg is in use

**Comment by muflone** [comment]
for the records, both issues seem related
https://rt.cpan.org/Public/Bug/Display.html?id=147409
https://rt.cpan.org/Public/Bug/Display.html?id=148280

**Comment by Photon89** [comment]
Thanks for looking into it! Looks like, we can only wait for an upstream fix!

**Comment by Photon89** [comment]
@christian-heusel The bug is fixed upstream at https://gitlab.gnome.org/GNOME/perl-glib-object-introspection/-/commit/eef3b1f8662bf76095987eeef41308094693cf3e but there is no new release yet. I asked upstream when a new release is expected.

**Comment by muflone** [comment]
fixed in perl-glib-object-introspection 0.050-2 by backporting the patch from master

**Comment by Photon89** [comment]
Great, thanks for backporting the patch!
