### ISSUE TITLE
Update Clipboard after Image capture is edited

### ISSUE THREAD

**Issue by fcortesjp** [shutter-project/shutter#586]
#### Description of requested feature:
would be nice to see a button or something in the menu that allows to update the clipboard once a screen cap has been edited

#### Reasons for adding feature:
if you edit a screencap, you have to save it and then look for the file so you can use it where you needed it. Instead, it would be nice just have the edited screencap available in the clipboad by a click of button after it's been edited, so it can be readly available so it be pasted in slack, or chat or an email or a document.

#### Extra information, such as Shutter version, operating system and ideas for how to implement:
Im using 0.99.2 on linux mint

**Comment by Photon89** [comment]
Thanks for the idea, we had it in #392 already, though! :smile:
