### ISSUE TITLE
RIght Click on screenshot crashes Shutter

### ISSUE THREAD

**Issue by delinuxco** [shutter-project/shutter#589]
#### Brief summary of issue
Take a screenshot, right click on image to access menu to run a plugin. 

#### Steps to reproduce the issue

1. start SHutter
2. takescreenshot
3. Right click on image

#### Error output
```
(shutter:2070): Gtk-CRITICAL **: 08:10:34.010: gtk_drag_source_set_icon_pixbuf: assertion 'site != NULL' failed
screenshot successfully saved to /home/delinuxco/Pictures/Screenshots/Selection_002.png!
GLib-CRITICAL **: Source ID 34 was not found when attempting to remove it at /usr/bin/shutter line 6957.
 at /usr/bin/shutter line 6955.
	Shutter::App::fct_show_status_message(1, "Selection_002.png saved") called at /usr/bin/shutter line 6534
	Shutter::App::fct_take_screenshot(Gtk3::ToolButton=HASH(0x56297a1cc7e8), "select", undef, undef) called at /usr/bin/shutter line 3038
	Shutter::App::__ANON__() called at /usr/lib/perl5/5.36/vendor_perl/Glib/Object/Introspection.pm line 67
	eval {...} called at /usr/lib/perl5/5.36/vendor_perl/Glib/Object/Introspection.pm line 67
	Glib::Object::Introspection::__ANON__(Shutter::App=HASH(0x562979b8ea20)) called at /usr/bin/shutter line 10944

fct_update_tray_menu was called by Wnck::Screen=HASH(0x562979ba75a8)
Segmentation fault (core dumped)

```

#### Extra information, such as Shutter version, display server in use (Xorg or Wayland), operating system and ideas for how to solve:
Manjaro Cinnamon Spin, 
Xorg
Arch Repo package is 0.99.4-1
Shutter About dialog: 0.99.3 Rev. 1607

**Comment by Photon89** [comment]
That's https://github.com/shutter-project/shutter/issues/583 Please wait for perl-glib-object-introspection 0.050-2 which backports a fix.

**Comment by delinuxco** [comment]
Thank you, I did do a search for "right click" and did not find anything, perhaps issue #583, may want to edit the title from "rightclick" to "right click" so that it picks up on the issue search.

**Comment by delinuxco** [comment]
Closed
