### ISSUE TITLE
Removing confirmation feature when selecting screenshot area?

### ISSUE THREAD

**Issue by 10kmotorola** [shutter-project/shutter#590]
I'm used to programs like ShareX where selecting an area to take a screenshot is quick and snappy, and having to confirm where I want it to be instead of just letting go of mouse feels clunky to me. Maybe there's a setting for this, but I can't find it anywhere.

**Comment by Photon89** [comment]
No, unfortunately, there is no such setting. I guess, Shutter is aimed at people who need to make the screenshot area exact with pixel accuracy. :smiley: 

No idea if it helps, but you can confirm the selection both with the Enter key and using your mouse with a double click.

**Comment by 10kmotorola** [comment]
Yeah makes sense, most times I'm just looking for a quick snap of what I'm doing to send to a friend.

**Comment by Photon89** [comment]
@mariospicross I created a PR implementing this feature, feel free to test: https://github.com/shutter-project/shutter/archive/refs/heads/590-removing-confirmation-feature-when-selecting-screenshot-area.zip

**Comment by 10kmotorola** [comment]
Sorry for the late response, but it is working well :)

**Comment by Photon89** [comment]
Great, thanks for testing!
