### ISSUE TITLE
shutter 0.99 crashes when a 

### ISSUE THREAD

**Issue by pimvlaar** [shutter-project/shutter#593]
#### Brief summary of issue

-after downloading version 0.99.4 as a zip into /opt/shutter
-unzipped it
-did a 'make', 
-shutter runs the ./po2mo.sh file
-launched it ./bin/shutter
-shutter [About} shows version 0.99.3 (strange, i downloaded version 0.99.4)
-main window comes up

#### Steps to reproduce the issue

1.  load a profile
2. edit the profile, like setting the directory for the images to be saved
3. save the profile under the new name, like 'movetub' (in mine case)
4. confirm 'profile already exists'
5. take a screenshot, draw an area, 
6. press [ENTER] to save the screenshot
7. exception is thrown

#### Error output

fct_update_tray_menu was called by Wnck::Screen=HASH(0x561b98e0b758)

select was emitted by widget Gtk3::ToolButton=HASH(0x561b99617088)
Using monitor: 1920 - 0 - 1920 - 1200
Parsing wildcards for 
Parsed $width and $height: 
Parsed $profile: 
Parsed $name: 
*** unhandled exception in callback:
***   Can't locate object method "append_string" via package "Glib::Object::_Unregistered::GLocalFile" at ./bin/shutter line 7908.
***   	Shutter::App::fct_get_next_filename("", "/work/cofely/projecten/verkade2/branches/deruijter2/doc/movet"..., "png") called at ./bin/shutter line 6330
***   	Shutter::App::fct_take_screenshot(Gtk3::ToolButton=HASH(0x561b99617088), "select", undef, undef) called at ./bin/shutter line 3038
***   	Shutter::App::__ANON__() called at /usr/lib/x86_64-linux-gnu/perl5/5.30/Glib/Object/Introspection.pm line 67
***   	eval {...} called at /usr/lib/x86_64-linux-gnu/perl5/5.30/Glib/Object/Introspection.pm line 67
***   	Glib::Object::Introspection::__ANON__(Shutter::App=HASH(0x561b987c42b8)) called at ./bin/shutter line 10944
***  ignoring at /usr/lib/x86_64-linux-gnu/perl5/5.30/Glib/Object/Introspection.pm line 67.
 at ./bin/shutter line 10944.

fct_update_tray_menu was called by Wnck::Screen=HASH(0x561b98e0b758)

**Comment by Photon89** [comment]
>  -shutter [About} shows version 0.99.3 (strange, i downloaded version 0.99.4)

My bad, I forgot to change the version info before release...

> edit the profile, like setting the directory for the images to be saved

What is your filename setting?

**Comment by pimvlaar** [comment]
fileName setting:

$profile%NNN


Op ma 24 jul 2023 om 14:57 schreef Michael Kogan ***@***.***>:

**Comment by Photon89** [comment]
I can reproduce it, looks like the filename is empty after saving the profile. Temporary workaround: Edit `~/.shutter/profiles/movetub.xml` and add the desired filename in line 2:

 <general app_version="0.99.3Rev.1607" as_help_active="1" asel_h="0" asel_w="0" asel_x="0" asel_y="0" ask_on_delete="" ask_on_fs_delete="" autofs="" autofs_min="" autofs_not="" autohide="1" autohide_time="400" autoshape_active="" border="1" bordereffect="2" bordereffect_active="" bordereffect_col="#000000" close_at_close="1" current_monitor_active="" cursor="" delay="0" delete_on_close="" **filename="$profile%NNN"** filetype="0" [...] />

**Comment by Photon89** [comment]
@pimvlaar You might want to test whether #601 fixes the issue for you.

**Comment by pimvlaar** [comment]
How do i checkout the related commit from shutter git repo?
what is the branchname for this pull request fix?

Op ma 24 jul 2023 om 20:12 schreef Michael Kogan ***@***.***>:

**Comment by Photon89** [comment]
You can just download https://github.com/Photon89/shutter/blob/master/bin/shutter and put it into `/usr/bin`.

**Comment by pimvlaar** [comment]
Running the downloaded version (
https://github.com/Photon89/shutter/blob/master/bin/shutter)

this error pops up, just after starting:

-rwxrwxr-x 1 root root      1799409 Jul 31 12:05  shutter
***@***.***:/usr/bin$ /usr/bin/shutter
/usr/bin/shutter: line 1: \t\t\t\tmy $new_giofile =
Glib::IO::File::new_for_path(${$session_xml}{$key}{'filename'});: bad
substitution



Op vr 28 jul 2023 om 11:26 schreef Michael Kogan ***@***.***>:

**Comment by Photon89** [comment]
This is very strange, there is no such line in line 1. Maybe there is some copy&paste mistake? How exactly did you download the file? Can you make a md5sum for it, just to make sure?

**Comment by DarthGandalf** [comment]
Did you download an HTML file of github itself which depicts shutter code
instead? Such HTML is not a valid perl

пн, 31 июл. 2023 г., 12:04 Michael Kogan ***@***.***>:

**Comment by Photon89** [comment]
Also, if the rest of the 0.99.4 files are in `/opt/shutter`, you should of course put the file into some subfolder in this path, not into `/usr/bin`.

**Comment by pimvlaar** [comment]
The version in : https://github.com/Photon89/shutter/blob/master/bin/shutter
seems to work.
I diff-ed that perl file with the perl file of the master and they are the
same.

But
i detected a problem:

When i start with a profile 'x' and configure the 'Automatically save file:
Directory' setting to the images directory for that profile
then images are saved in that directory, which is okay.
But when switching to another profile, via the 'quick profile select' or
via the 'dropdown box',
that does NOT alter the 'Automatically save file: Directory' setting.
The directory setting remains as were defined for profile 'x'.

That effect can also be seen in the main window still showing the directory
setting for profile 'x'.

I hope you can simulate that.

Op ma 31 jul 2023 om 13:17 schreef Michael Kogan ***@***.***>:

**Comment by Photon89** [comment]
I can reproduce it and will have a look, thanks!

**Comment by Photon89** [comment]
Since the original crash and saving/loading the filename seems to be fixed and loading the path is a completely different issue, I'd propose to split it off to not mix things up..
