### ISSUE TITLE
Images imported from Clipboard behave differently from captured ones

### ISSUE THREAD

**Issue by jmbreuer** [shutter-project/shutter#595]
#### Brief summary of issue

Images imported from the clipboard (using File/New/Import from Clipboard...) behave differently in the session interface than (all?) other images.

#### Steps to reproduce the issue

0. Have image data on the clipboard
1. Add an image using File/New/Import from Clipboard...

#### Error output

- The image imported from the clipboard shows up zoomed 1:1 (with its upper left corner shown), whereas all other images come up zoomed to fit in their session tab.

There's two similar bugs handling such images that I'm putting together for now:

- Pressing the Delete key on an active tab with an image imported from the clipboard does not close that tab, nor does it remove that image from the Session overview (list, that first tab called "Session")

- Using 'Move to Trash' on an image imported from the clipboard in the Session tab removes its tab (if opened), but doesn't remove it/its thumbnail from the Session tab. Also, the image file does remain on the filesystem.

#### Extra information, such as Shutter version, display server in use (Xorg or Wayland), operating system and ideas for how to solve:

Shutter 0.99.3/Rev. 1607 on Gentoo Linux, KDE Plasma 5.27.5.

**Comment by Photon89** [comment]
@jmbreuer: This should be fixed with #663, you can test from here: https://github.com/shutter-project/shutter/tree/fix-%23595
