### ISSUE TITLE
Image save path not loaded correctly when loading a profile

### ISSUE THREAD

**Issue by Photon89** [shutter-project/shutter#604]
When i start with a profile 'x' and configure the 'Automatically save file:
Directory' setting to the images directory for that profile
then images are saved in that directory, which is okay.
But when switching to another profile, via the 'quick profile select' or
via the 'dropdown box',
that does NOT alter the 'Automatically save file: Directory' setting.
The directory setting remains as were defined for profile 'x'.

That effect can also be seen in the main window still showing the directory
setting for profile 'x'.

I hope you can simulate that.

_Originally posted by @pimvlaar in https://github.com/shutter-project/shutter/issues/593#issuecomment-1662779391_

**Comment by Photon89** [comment]
@pimvlaar I found the following in the code which deals with loading the save path, around line 4746 https://github.com/shutter-project/shutter/blob/154d9a1c23b8adb44015f5c238f021e245569713/bin/shutter#L4747

```
	#FIXME
	#this is a dirty hack to force the setting to be enabled in session tab
	#at the moment i simply dont know why the filechooser "caches" the old value
	# => weird...
	$settings_xml->{'general'}->{'folder_force'} = TRUE;
```

Looks like whatever this was doing doesn't work any more.

**Comment by Photon89** [comment]
I've asked for support at https://stackoverflow.com/questions/76830330/how-to-change-the-folder-in-gtk3filechooserbutton-programmatically

**Comment by Photon89** [comment]
@pimvlaar: Please test https://raw.githubusercontent.com/Photon89/shutter/Photon89-604/bin/shutter

**Comment by pimvlaar** [comment]
the version at '
https://raw.githubusercontent.com/Photon89/shutter/Photon89-604/bin/shutter'
seems to work.

I'v tested it,
via Edit->Preferences and  changing the profile in the dropbox and ticking
'load the selected profile's configuration'-button
and
via Edit->Quick profile select (selecting another profile).

Both methods seems to work fine,
the 'Automatically save file: Directory' is changed to the correct
directory.

Thanks.

Very nice application 'Shutter' !

Op vr 4 aug 2023 om 15:49 schreef Michael Kogan ***@***.***>:

**Comment by Photon89** [comment]
Great, thanks for testing!
