### ISSUE TITLE
Shutter GUI disappear after catching screen selection

### ISSUE THREAD

**Issue by stelesgh** [shutter-project/shutter#613]
When I try to catch a portion of screen or catch a menu the Shutter GUI disappear and the tray bar widget doesn't show any menu. 
To get it working again I have to kill it and re-run.

In attachment termlog.txt.zip (clipboard of terminal I used to run shutter) you can see the error from line 1602  to line 1609.

Other information:
uname -a 
Linux fedora 6.4.11-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Aug 16 17:42:12 UTC 2023 x86_64 GNU/Linux

cat /etc/redhat-release 
Fedora release 38 (Thirty Eight)
[termlog.txt.zip](https://github.com/shutter-project/shutter/files/12408648/termlog.txt.zip)

**Comment by Photon89** [comment]
Could you please specify which Shutter version you are using?
Is the issue 100% reproducible or does it appear sporadically?
Could you test the latest git version? Just download https://github.com/shutter-project/shutter/archive/refs/heads/master.zip unpack it somewhere and execute `./bin/shutter` in the unpacked folder.

**Comment by stelesgh** [comment]
Shutter version: 0.99.3  Rev. 1607
The issue is 100% reproducible.
I will try latest git version and I will add a comment with result
Tnx

**Comment by Photon89** [comment]
Probably it's version 0.99.4, I messed up the version information on release. :smile:  So, latest stable version then. Let's see if the issue is fixed in git!

**Comment by stelesgh** [comment]
Latest shuter version throw the same error "Can't locate object method "append_string" via package".
Look at 1610_termlog.txt.zip attachments for full detail (from row 750 to row 758)
Best regards
Stefano
[1610_termlog.txt.zip](https://github.com/shutter-project/shutter/files/12409615/1610_termlog.txt.zip)

**Comment by stelesgh** [comment]
> Probably it's version 0.99.4, I messed up the version information on release. 😄 So, latest stable version then. Let's see if the issue is fixed in git!

Well.. this is shutter version extracted by "dnf":
_shutter.noarch                                                                           0.99.4-1.fc38_

**Comment by Photon89** [comment]
Could you please check what is your setting for the file name?

![Bildschirmfoto_2023-08-22_16-27-10](https://github.com/shutter-project/shutter/assets/1191480/434aa4d5-148f-40ce-a637-7bac8a1976a5)

**Comment by stelesgh** [comment]
Bingo! That was the problem!
I set "%NN" in Filename and now GUI appear with the screenshot!
Thank you very much
Stefano

**Comment by Photon89** [comment]
I guess, we need a better error handling here!

**Comment by Photon89** [comment]
Let's keep it open for the moment, so we don't forget about improving the error handling!
