### ISSUE TITLE
Query on gnome-web-photo

### ISSUE THREAD

**Issue by wizardfromoz57** [shutter-project/shutter#615]
#### Shutter version, 0.99.2-4

Thanks

Chris Turner
wizardfromoz
I am an administrator at linux.org

**Comment by Photon89** [comment]
Yes, this is a known issue: https://github.com/shutter-project/shutter/issues/285 We were considering to switch from gnome-web-photo to `wkhtmltoimage` or `weasyprint` but had security concerns (please read the discussion in the last few comments of above issue report).

**Comment by Photon89** [comment]
Closing as duplicate of #285. Please comment there if there are further open questions!
