### ISSUE TITLE
Errors on start

### ISSUE THREAD

**Issue by Colburse** [shutter-project/shutter#616]
The program errors whenever I run it.

#### Extra information, such as Shutter version, display server in use (Xorg or Wayland) and operating system:
`shutter-git` from the AUR , version r1636.d6dcd492-1 (0.99.4)
Display Server: X11
OS: Artix Linux

`$ shutter --debug -v > shutter.log 2>&1`
[shutter.log](https://github.com/shutter-project/shutter/files/12515352/shutter.log)

**Comment by Photon89** [comment]
The log shows no errors, those are all warnings. Are you sure that the log is complete?

**Comment by Colburse** [comment]
Oh, apologies. It didn't capture the last part. Here you go:

```

Shutter 0.99.4 Rev.1608
Linux coco 6.4.9-273-tkg-pds #1 SMP PREEMPT_DYNAMIC TKG Wed, 09 Aug 2023 20:55:03 +0000 x86_64 GNU/Linux
 
Artix Linux \r (\l)
 
Glib 1.3293
Gtk3 0.038
 
Glib built for 2.76.4, running with 2.76.5
 
Can't use an undefined value as an ARRAY reference at /usr/bin/shutter line 8390, <DATA> line 19.
        Shutter::App::fct_ret_window_menu() called at /usr/bin/shutter line 8493
        Shutter::App::fct_ret_tray_menu() called at /usr/bin/shutter line 475
        Shutter::App::STARTUP(Shutter::App=HASH(0x564f425cb7d8)) called at /usr/lib/perl5/5.38/vendor_perl/Glib/Object/Introspection.pm line 67
        Glib::Object::Introspection::__ANON__(Shutter::App=HASH(0x564f425cb7d8)) called at /usr/bin/shutter line 10962
GLib-GObject-CRITICAL **: g_boxed_free: assertion 'boxed != NULL' failed, <DATA> line 19 during global destruction.
 at /usr/bin/shutter line 0, <DATA> line 19.
        eval {...} called at /usr/bin/shutter line 0
GLib-GObject-CRITICAL **: g_boxed_free: assertion 'boxed != NULL' failed, <DATA> line 19 during global destruction.
 at /usr/bin/shutter line 0, <DATA> line 19.
        eval {...} called at /usr/bin/shutter line 0
GLib-GObject-CRITICAL **: g_boxed_free: assertion 'boxed != NULL' failed, <DATA> line 19 during global destruction.
 at /usr/bin/shutter line 0, <DATA> line 19.
        eval {...} called at /usr/bin/shutter line 0
GLib-GObject-CRITICAL **: g_boxed_free: assertion 'boxed != NULL' failed, <DATA> line 19 during global destruction.
 at /usr/bin/shutter line 0, <DATA> line 19.
        eval {...} called at /usr/bin/shutter line 0
GLib-GObject-CRITICAL **: g_boxed_free: assertion 'boxed != NULL' failed, <DATA> line 19 during global destruction.
 at /usr/bin/shutter line 0, <DATA> line 19.
        eval {...} called at /usr/bin/shutter line 0
GLib-GObject-CRITICAL **: g_boxed_free: assertion 'boxed != NULL' failed, <DATA> line 19 during global destruction.
 at /usr/bin/shutter line 0, <DATA> line 19.
        eval {...} called at /usr/bin/shutter line 0
GLib-GObject-CRITICAL **: g_boxed_free: assertion 'boxed != NULL' failed, <DATA> line 19 during global destruction.
 at /usr/bin/shutter line 0, <DATA> line 19.
        eval {...} called at /usr/bin/shutter line 0
GLib-GObject-CRITICAL **: g_boxed_free: assertion 'boxed != NULL' failed, <DATA> line 19 during global destruction.
 at /usr/bin/shutter line 0, <DATA> line 19.
        eval {...} called at /usr/bin/shutter line 0
GLib-GObject-CRITICAL **: g_boxed_free: assertion 'boxed != NULL' failed, <DATA> line 19 during global destruction.
 at /usr/bin/shutter line 0, <DATA> line 19.
        eval {...} called at /usr/bin/shutter line 0
GLib-GObject-CRITICAL **: g_boxed_free: assertion 'boxed != NULL' failed, <DATA> line 19 during global destruction.
 at /usr/bin/shutter line 0, <DATA> line 19.
        eval {...} called at /usr/bin/shutter line 0
```

**Comment by Photon89** [comment]
As far as I can see, you are at this commit from November 2021: https://github.com/shutter-project/shutter/commit/d6dcd49291eead28cc5e15a5562b68d7924e223d Could you please rebuild shutter-git to get to the latest commit? I don't bump the package rev, such that users don't get updates too frequently, so it gets easily stuck at some old commit...

**Comment by Colburse** [comment]
I tried to manually build [shutter-git](https://aur.archlinux.org/shutter-git.git) from the AUR, but that doesn't seem to work for me either. I get almost the same error. According to pacman, the package version is `r1746.09ece08c-1`, and according to `shutter -v`, the version is `0.99.3 Rev.1607`.
I also tried building it from source, but I get this error:

```
coco@coco ~/Desktop/shutter-0.99.4 $ sudo make install
./po2mo.sh
install -Dm644 COPYING /usr/local/share/doc/shutter/COPYING
install -Dm644 README /usr/local/share/doc/shutter/README
install -Dm755 bin/shutter /usr/local/bin/shutter
cp -r share/ /usr/local/
cp: cannot overwrite non-directory '/usr/local/share/man' with directory 'share/man'
make: *** [Makefile:14: install] Error 1
```
It builds successfully when I set the prefix to something else, but I get an error when running the binary.
```
coco@coco ~/Desktop/shutter-0.99.4 $ /home/coco/Desktop/shutter-0.99.4/shutter/bin/shutter
Can't locate Carp/Always.pm in @INC (you may need to install the Carp::Always module) (@INC entries checked: /usr/lib/perl5/5.38/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/5.38/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/5.38/core_perl /usr/share/perl5/core_perl) at /home/coco/Desktop/shutter-0.99.4/shutter/bin/shutter line 39.
BEGIN failed--compilation aborted at /home/coco/Desktop/shutter-0.99.4/shutter/bin/shutter line 39 (#1)
    (F) You said to do (or require, or use) a file that couldn't be found.
    Perl looks for the file in all the locations mentioned in @INC, unless
    the file name included the full path to the file.  Perhaps you need
    to set the PERL5LIB or PERL5OPT environment variable to say where the
    extra library is, or maybe the script needs to add the library name
    to @INC.  Or maybe you just misspelled the name of the file.  See
    "require" in perlfunc and lib.
 
Uncaught exception from user code:
        Can't locate Carp/Always.pm in @INC (you may need to install the Carp::Always module) (@INC entries checked: /usr/lib/perl5/5.38/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/5.38/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/5.38/core_perl /usr/share/perl5/core_perl) at /home/coco/Desktop/shutter-0.99.4/shutter/bin/shutter line 39.
        BEGIN failed--compilation aborted at /home/coco/Desktop/shutter-0.99.4/shutter/bin/shutter line 39.
```

I apologize if I'm just missing something obvious. I don't have very much experience in dealing with packages.

**Comment by Photon89** [comment]
For testing purposes it's perfectly fine to run Shutter from the unpacked folder without installation. It doesn't launch, because the package `perl-carp-always` is missing. It's strange though, because it is a dependency for `shutter-git`... Anyway, could you please check whether the package is installed, and if not install it? Then try to run Shutter from the unpacked folder again.

**Comment by Colburse** [comment]
It seems that `perl-carp-always` is already installed on my system. Version is `0.16-4`.

**Comment by Colburse** [comment]
Ah, I didn't have it when I ran shutter from the unpacked folder. The reason I have it now is because I installed the AUR package, which came with all the dependencies. I had uninstalled it whenever I went to run the unpacked one. This is the log from the shutter that I built from source.
[shutter.log](https://github.com/shutter-project/shutter/files/12533916/shutter.log)

**Comment by Photon89** [comment]
This looks good but not complete again. Does Shutter still crash?

**Comment by Colburse** [comment]
Oh, running with the `-v`  flag causes it to not print the full output... My mistake for forgetting about that. Here is the full log:
[shutter.log](https://github.com/shutter-project/shutter/files/12533936/shutter.log)

Edit: Yes, Shutter still crashes.

**Comment by Photon89** [comment]
Ok, I will try to have a look after work. Could you specify, which desktop environment you are running? It looks like Shutter fails to get the window list on launch.

**Comment by Colburse** [comment]
I don't use a desktop environment, and the window manager I'm using is a modified [dwm](https://dwm.suckless.org/). Here are my "glib" packages in case that helps:
```
glib-networking 1:2.76.1-1
glib-perl 1.329.3-4
glib2 2.76.5-1
glib2-docs 2.76.5-1
glibc 2.38-3
glibc-runit 20180226-2
glibmm 2.66.6-1
glibmm-2.68 2.76.0-1
json-glib 1.6.6-2
lib32-dbus-glib 0.112-2
lib32-glib-networking 2.76.1-1
lib32-glib2 2.76.5-1
lib32-glibc 2.38-3
lib32-json-glib 1.6.6-2
lib32-libdbusmenu-glib 16.04.0-5
lib32-taglib 1.13.1-1
libaccounts-glib 1.26-2
libdbusmenu-glib 16.04.0.r498-1
libmm-glib 1.20.6-2
libqrtr-glib 1.2.2-2
libvirt-glib 4.0.0-2
perl-glib-object-introspection 0.050-3
poppler-glib 23.08.0-1
```

**Comment by Photon89** [comment]
Please check out this workaround: https://shutter-project.org/faq-help/workarounds/

**Comment by Colburse** [comment]
I added the _NET_CLIENT_LIST and ewmh patches, and that fixed it. Thank you for your help, and I'm very sorry for wasting your time. Might I recommend changing the name of the page from "Workarounds" to "Troubleshooting/Workarounds"? I only checked the man page because the other two help pages didn't seem to be what I was looking for.

**Comment by Photon89** [comment]
Maybe we should just kick out the other workaround, as most probably nobody uses the GTK2 version any more, and name the page "Workaround for crash on DWM".
