### ISSUE TITLE
 Install appdata files to /usr/share/metainfo/

### ISSUE THREAD

**Issue by sidt4** [shutter-project/shutter#620]
```
$ apt-file search shutter.appdata.xml
shutter: /usr/share/appdata/shutter.appdata.xml
shutter: /usr/share/metainfo/shutter.appdata.xml
...
```

- Refer: https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#spec-component-location
- Refer: https://appstream.debian.org/sid/main/issues/shutter.html
- Refer: https://appstream.debian.org/sid/main/metainfo/shutter.html

**Comment by Photon89** [comment]
Aren't we doing so already? The file is located in `$prefix/share/metainfo/shutter.metainfo.xml`  for half a year, actually: https://github.com/shutter-project/shutter/commit/c3dec93780e49a6df312bd7d3a4dd3269e633cbf

**Comment by sidt4** [comment]
Yes. The other file `/usr/share/appdata/shutter.appdata.xml` can be removed.

**Comment by sidt4** [comment]
Note: Use `appstreamcli validate` ( and not the deprecated `appstream-util validate` ) command to validate appstream metainfo files.

**Comment by Photon89** [comment]
It looks like it hasn't been cleanly removed by your distro's packager, as it doesn't exist in our file tree: https://github.com/shutter-project/shutter/tree/master/share

**Comment by sidt4** [comment]
Seems like Debian does something here: 

Refer: https://salsa.debian.org/perl-team/modules/packages/shutter/-/blob/debian/unstable/debian/install

P.S.: I'm just trying to notify all projects which populate `/usr/share/appdata/`. So, some messages might not be 100% relevant.

**Comment by Photon89** [comment]
This package is for version 0.98, we are at 0.99.4 and the relevant change has been introduced just before its release.  I'd say, let's wait for Debian to pick up the latest version!

**Comment by Photon89** [comment]
Actually, they updated already, but it is unreleased currently according to the changelog: https://salsa.debian.org/perl-team/modules/packages/shutter/-/blob/debian/unstable/debian/changelog You might want to report the issue against the Debian package though so they update their install file which you linked in your previous comment.

**Comment by sidt4** [comment]
If things are clear on the `shutter-project` side, rest will be taken care by the Debian maintainers.

**Comment by Photon89** [comment]
Well, we didn't mention the new location for this file in the changelog for 0.99.4 because we didn't consider it relevant.  I guess, it is too late to add this information now.
