### ISSUE TITLE
Shutter hang 

### ISSUE THREAD

**Issue by stelesgh** [shutter-project/shutter#627]
Hi. 
When I try to take a picture, after area selection, Shutter window doesn't come back on screen.
If I try to open Shutter manually from menu, the window appear without image and "Selection" button is disabled.

Software version: 0.99.3 Rev 1607

[fedora]$ uname -a
Linux fedora 6.5.7-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Oct 11 04:07:58 UTC 2023 x86_64 GNU/Linux

[fedora]$ cat /etc/redhat-release 
Fedora release 38 (Thirty Eight)

[fedora]$rpm -qa|grep shutter
shutter-0.99.4-1.fc38.noarch

Thanks

**Comment by Photon89** [comment]
Could you please run Shutter from terminal and paste the output (which is added during the selection screenshot, or just the complete output, as you prefer)?

**Comment by stelesgh** [comment]
Sure.. I attach zipped terminal output.
Rows details:

rows 0 -> 699  : startup
rows 700 -> 279: after click selection
rows 730 -> 744: after selection
rows 745 -> 784: after interupt with ctrl-C

[shutter.log.txt.zip](https://github.com/shutter-project/shutter/files/13052553/shutter.log.txt.zip)

**Comment by Photon89** [comment]
Could you please try this version (you can just unpack it and run from the unpacked folder): https://github.com/shutter-project/shutter/archive/refs/heads/zero_dimension_selection_fix2.zip

**Comment by stelesgh** [comment]
Ok. Same behavior..
[shutter_fix2.log.txt.zip](https://github.com/shutter-project/shutter/files/13052670/shutter_fix2.log.txt.zip)

**Comment by Photon89** [comment]
Sorry, I was on the wrong track. Could you please check your setting for the filename in the general settings? It looks like https://github.com/shutter-project/shutter/issues/613

**Comment by Photon89** [comment]
Oh wait, you were actually the one to report it. It looks like the same problem though!

**Comment by stelesgh** [comment]
I had checked the parameter before opening the ticket and I am convinced that it was ok.
I did a new test after re-entering the value on the parameter and saving it as the "default" profile.
The behavior is the same: after selecting the area, shutter gui does not appear on the screen and the icon on the tray bar does not respond.
T.I.A.
[RecApp-2023-10-22-22:47:27.webm](https://github.com/shutter-project/shutter/assets/9663731/3a913a76-5052-44da-84d0-0941bfc54d86)

**Comment by Photon89** [comment]
Looks like the filename is not being set properly. Could you please add the terminal output while saving the preferences with a new filename pattern?

**Comment by stelesgh** [comment]
I've done a new complete test after uninstall and reinstall program (dnf remove.. ; dnf install...)
These are the steps on the attached file:
- as far row 704: program startup
- from 705 to 735: setting "file name" parameter to value "%T"
- from 736 to 753: close settings window.
- from 754 to 777: capture screen area and  program stuck
- from 778 to 816: program killed (CTRL-C)
Thank in advance

[shutter_log_terminal.txt](https://github.com/shutter-project/shutter/files/13078610/shutter_log_terminal.txt)

**Comment by Photon89** [comment]
Could you please do the following: 
1. Set the file name
2. Close the settings window
3. Open the settings window and check whether the file name setting has been saved correctly
4. If so, capture the screen area

**Comment by stelesgh** [comment]
Hi! Sorry for the delay.
I've shoot a video for this test.
Now Shutter keeps file name settings
But it generates two images, the first normal and a second in thumbnail format.
I haven't found a parameter for this last behavior, but it doesn't matter.
Software version is ever 0.99.3 Rev 1607
Thanks 
SL
[RecApp-2023-11-09-22:42:09.webm](https://github.com/shutter-project/shutter/assets/9663731/fa914f0f-f1c8-4683-8694-2942ea5be0ce)

**Comment by Photon89** [comment]
You can switch thumbnail generation on and off in the Preferences > Actions dialog.
