### ISSUE TITLE
how to download & install gnome-web-photo

### ISSUE THREAD

**Issue by dduran1210** [shutter-project/shutter#630]

**Comment by Photon89** [comment]
That's a bit tricky nowadays. Could you please specify, which distribution you are using?

**Comment by dduran1210** [comment]
NEVER MIND...such a damn hassle with github.  can't seem to find a program
with a .deb extension to
install anything easy.

**Comment by Photon89** [comment]
So, is the issue solved for you?

**Comment by dduran1210** [comment]
well...yes...i went and found a different rolling screenshot program.

thanks
dave

**Comment by Photon89** [comment]
Well, that's another possible solution, I guess. ;) Closing!
