### ISSUE TITLE
Support webp image format

### ISSUE THREAD

**Issue by hsandt** [shutter-project/shutter#636]
#### Description of requested feature:

Add webp (with adequate quality range 0-100) to the list of supported image format in Preferences > Main > Image format

#### Reasons for adding feature:

Allows me to capture many lightweight screenshots during development of my apps (esp. games) without having to convert png to webp afterward.

#### Extra information, such as Shutter version, operating system and ideas for how to implement:

Linux Ubuntu 22.04 (webp support already installed, I can preview webp images in eye of gnome at least)
Shutter 0.99.2 Rev.1593

(P.S.: any way to see version in app instead of using command line `shuuter -v` which printed a bunch of errors before finally showing the version number?)

**Comment by DarthGandalf** [comment]
> any way to see version in app instead of using command line

Help>About should show it

**Comment by Photon89** [comment]
It gives the wrong value for the current stable release though. I created the release tarball right after bumping the version info and it looks like something went wrong...

**Comment by Photon89** [comment]
Regarding the actual issue: https://github.com/aruiz/webp-pixbuf-loader adds webp support to GDK Pixbuf. If you install it, Shutter will be able to open webp images and the editor will be able to edit them. But I assume that we would need to add an entry to the settings dialog where the image format for saving new screenshots can be selected. The entry should only be visible if the dependency is available though.

**Comment by Photon89** [comment]
Webp support is implemented in #642. Please test!
