### ISSUE TITLE
Option for Select to Automatically Create Screenshot on Mouse Release

### ISSUE THREAD

**Issue by StuartJAtkinson** [shutter-project/shutter#637]
#### Description of requested feature:
Option for Select to Automatically Create Screenshot on Mouse Release

#### Reasons for adding feature:
Windows snips works to create the screenshot on hotkey combo click and release. This is a nice feature so an option for it to work this way would help transitionsers from Windows.

#### Extra information, such as Shutter version, operating system and ideas for how to implement:
Any

**Comment by Photon89** [comment]
It's implemented with #610, please try the latest git commit!

**Comment by Photon89** [comment]
Closing, as the feature request is already implemented in master.
