### ISSUE TITLE
Remove broken link to snap

### ISSUE THREAD

**Issue by Flimm** [shutter-project/shutter#638]
This is the downloads web page for the Shutter project: https://shutter-project.org/downloads/third-party-packages/

Let me quote part of that page:

> For RHEL 7 and 8 Shutter can be installed using snap following [these instructions](https://snapcraft.io/install/shutter/rhel).

This link is broken. There does not seem to be a Snap package for Shutter any more. The broken link should be removed from this page.

**Comment by Photon89** [comment]
@Flimm Thanks, fixed!
