### ISSUE TITLE
.

### ISSUE THREAD

**Issue by jp-x-g** [shutter-project/shutter#639]
.

**Comment by jp-x-g** [comment]
I will mention that I've also tried manually emptying its cache. Nothing -- it doesn't even give me an error message, it simply refuses to work and I can't take screenshots on my computer.

**Comment by DarthGandalf** [comment]
How did you solve it?

**Comment by jp-x-g** [comment]
I went into some more detail [here](https://github.com/shutter-project/shutter/issues/640); the "filename" pattern in the preferences had somehow become blank, so it seemed to have been experiencing some kind of issue with that, but instead of giving an error message it just hung forever.

**Comment by DarthGandalf** [comment]
I see, you don't need to do such closing of issue and removing all the details - you can just update same issue with the new findings instead of opening new one
