### ISSUE TITLE
Snippet

### ISSUE THREAD

**Issue by JGSum** [shutter-project/shutter#645]
How do you use shutter to take a snippet?

**Comment by Photon89** [comment]
Hi, could you please explain in more detail, what is a snippet exactly, as opposed to a screenshot?

**Comment by JGSum** [comment]
It’s a cutout of a screen shot you create by using the Microsoft snipping
tool. I figured it out with shutter though

**Comment by Photon89** [comment]
Ah, you mean the selection mode! Great, I'm closing then, as you already figured it out!
