### ISSUE TITLE
Scrolling screenshot

### ISSUE THREAD

**Issue by AnonymousRonin** [shutter-project/shutter#647]
I want to be able to take a screenshot of items that are larger than the display, ie I need to scroll down to see all of it.  Is there a way to take a scrolling screenshot?  Is there an add on or extension I need to install?  Thanks.

**Comment by Photon89** [comment]
Unfortunately, this is not (yet) possible, see https://github.com/shutter-project/shutter/issues/13

**Comment by Photon89** [comment]
For further discussion please comment #13. Closing.
