### ISSUE TITLE
selection bind stopped working after update to KDE plasma 6

### ISSUE THREAD

**Issue by papaollie** [shutter-project/shutter#660]
would use a global shortcut before, but now the fullscreen one i set up works but the selection one does not. if i can be refreshed as to what command to set it up with id appreciate it!

**Comment by DarthGandalf** [comment]
Do you happen to use wayland?

**Comment by papaollie** [comment]
i have but am currently using x11 as i find its more stable in general with plasma 6 atm

**Comment by Photon89** [comment]
So, does the selection mode work when started from the GUI?

**Comment by papaollie** [comment]
deleted and readded it using shutter -s as before and now it works. couldve been an update or restart, thanks for your help feller!

**Comment by Photon89** [comment]
Great, glad that you could solve this issue! Closing.
