### ISSUE TITLE
Ubuntu/Debian package 0.99.5 is on the road :-)

### ISSUE THREAD

**Issue by Cyrille37** [shutter-project/shutter#666]
Hi and thanks a lot for this really great tool <3

Ubuntu has only the 0.99.2 version :(

https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=shutter&searchon=names

Thanks & cheers

**Comment by Photon89** [comment]
Unfortunately, we cannot make the distros' packagers update Shutter sooner. It's 0.99.2 in Debian as well, so Ubuntu won't have a more recent version either.

The only way to get the latest stable version is to download it from  https://github.com/shutter-project/shutter/releases/tag/v0.99.5, unpack the tarball and run it from the unpacked directory or `make install` it: https://shutter-project.org/downloads/source-code/

**Comment by Photon89** [comment]
@andrewshadura Possibly you could have a look into packaging 0.99.5 for Debian? Thanks!

**Comment by moritz89** [comment]
Just installed 0.9.5 on Ubuntu 22.04 and all you need in addition to running the `sudo make install` command in the downloaded release folder is installing `libmoo-perl` via apt.

**Comment by Cyrille37** [comment]
Great.

But, perhaps adding to the project a script that permits to construct the `.deb` file like the system will know what is installed ... I don't know how it works but it perhaps simple ?

**Comment by Photon89** [comment]
You should uninstall shutter 0.99.2, if you want to `make install` shutter 0.99.5.

**Comment by Photon89** [comment]
Thanks to @andrewshadura 0.99.5 entered Debian testing a few days ago: https://tracker.debian.org/pkg/shutter

**Comment by Cyrille37** [comment]
> Thanks to @andrewshadura 0.99.5 entered Debian testing a few days ago: https://tracker.debian.org/pkg/shutter

Yearh! That's a nice nows, good job. Thanks a lot @andrewshadura !

**Comment by Photon89** [comment]
@martinkg Maybe you could have a look into releasing a new Fedora package for 0.99.5, as well? Thanks! :smiley:

**Comment by martinkg** [comment]
> @martinkg Maybe you could have a look into releasing a new Fedora package for 0.99.5, as well? Thanks! 😃

done :)

**Comment by Photon89** [comment]
Thanks!

**Comment by Photon89** [comment]
Shutter 0.99.5 entered the Ubuntu Oracular repos in the mean time: https://packages.ubuntu.com/oracular/shutter

Thanks to everybody who was involved into the packaging work!
