### ISSUE TITLE
Toolbars too small on my screen.

### ISSUE THREAD

**Issue by klequis** [shutter-project/shutter#674]
I'm using Shutter on Ubuntu 23.10. The toolbar on the left side of the window is too small. Is there a way to make them larger?

Thank you,
Carl

**Comment by Photon89** [comment]
Do you mean the tools panel in the integrated editor?

**Comment by klequis** [comment]
The editor

![image](https://github.com/shutter-project/shutter/assets/18337376/993b03c4-b272-4403-b54d-819351057cd1)

**Comment by Photon89** [comment]
Unfortunately, we have no good solution for it so far, the issue has been reported already at #382. We need an icon designer, I guess, who could create icons which look good on both bright and dark GTK themes...
