### ISSUE TITLE
Shutter has problems lauching at startup

### ISSUE THREAD

**Issue by conualfy** [shutter-project/shutter#681]
#### Brief summary of issue

For some reasons, even if the checkbox is set to launch minimized (tray icon actually) at startup and on startup list I do have "shutter --min_at_startup", it has problems auto starting. Not sure what exactly is the problem, but I would expect something easy, like some path not being recognized or something like that, just don't know how to check exactly.

#### Steps to reproduce the issue

1.  Installed Shutter, set for autostart on startup
2. Shutter does not start on startup
3. 

#### Error output
-

#### Extra information, such as Shutter version, display server in use (Xorg or Wayland), operating system and ideas for how to solve:

I use X11 on Ubuntu 24.04 but it worked the same on previous releases. I checked the startup apps and it should work as "shutter --min_at_startup" is there, but it does not.

**Comment by Photon89** [comment]
Does it show the main window at launch or doesn't it start up at all?

**Comment by conualfy** [comment]
It does not start at all.

> Does it show the main window at launch or doesn't it start up at all?

**Comment by Photon89** [comment]
Does it only happen with the `--min_at_startup` option or is Shutter possibly not starting at all, regardless what options are set?

**Comment by conualfy** [comment]
I did not try without the parameter as that is the default when the option is activated. Editing now.

**Comment by conualfy** [comment]
Just tried it without the parameter. Both with autologin and with manual login it does not start.

**Comment by Photon89** [comment]
Does it only crash when launched at startup, or does it crash if launched manually after DE session start as well? Which DE are you using btw., Gnome, right?

**Comment by conualfy** [comment]
Sorry for the late reply, I only now saw the reply. If I run it manually, it starts, so only on startup. Yes, Gnome Shell.
[log.txt](https://github.com/user-attachments/files/16100947/log.txt)

**Comment by Photon89** [comment]
Here is a possible workaround: https://github.com/shutter-project/shutter/issues/372#issuecomment-1229431940 

Brief summary: Add a .desktop file `shutter1.desktop`  into `.config/autostart/` with the `X-GNOME-Autostart-Delay=30` option. This will delay the startup process by 30 seconds (you can edit the value to suit your needs), such that Shutter isn't started too early for Gnome Shell.

**Comment by conualfy** [comment]
This is interesting and strange at the same time. I only added the delayed start 30 seconds (X-GNOME-Autostart-Delay=30 ) to the existing shutter.desktop and it starts now (tried only one restart, but I guess it should work every time). Why would it not start otherwise? Thank you.

> Here is a possible workaround: [#372 (comment)](https://github.com/shutter-project/shutter/issues/372#issuecomment-1229431940)
> 
> Brief summary: Add a .desktop file `shutter1.desktop` into `.config/autostart/` with the `X-GNOME-Autostart-Delay=30` option. This will delay the startup process by 30 seconds (you can edit the value to suit your needs), such that Shutter isn't started too early for Gnome Shell.

**Comment by Photon89** [comment]
I fear that it will stop working next time, because Shutter automatically overwrites the edited .desktop file. That's why you need another one with a different name.

We couldn't figure out why Shutter needs a delay to correctly start in Gnome. Most probably the Gnome panel/tray takes too long and apps are launched too early, before it has finished starting up.

**Comment by Photon89** [comment]
I propose to continue the discussion at #372 if further questions arise. Closing here as duplicate.
