### ISSUE TITLE
[request] Opening from command line straight into edit mode in a maximized Shutter

### ISSUE THREAD

**Issue by TheSHEEEP** [shutter-project/shutter#682]
#### Description of requested feature:
Add two command line parameters, one for opening Shutter maximized/in fullscreen, another for opening straight into edit mode.

#### Reasons for adding feature:
I'd like to be able to open Shutter from the command line straight into its editing mode in fullscreen, without having to manually go into the edit mode and maximizing Shutter.
There does not seem to be any command line argument to achieve this at the moment.

My current workaround is to take a screenshot with Shutter in the background and then open that created file in an editor (eg. `shutter -a -o bla.png && krita --nosplash bla.png`). This command I can put on a shortcut so I can trigger it easily on a single button press and can get right into annotation.  
While this works, Krita is certainly overkill for quick screenshot annotation.

#### Extra information, such as Shutter version, operating system and ideas for how to implement:
Something like this would be nice `shutter -a --maximized --edit_mode`.

**Comment by Photon89** [comment]
Thanks for your request, this has been already requested in #542. Please comment there for further discussion. Closing here as duplicate.
