### ISSUE TITLE
Request AVIF Format

### ISSUE THREAD

**Issue by 3xploiton3** [shutter-project/shutter#690]
#### Description of requested feature:
Add AVIF Format

#### Reasons for adding feature:
AVIF is more compression efficient than older image formats, with file sizes that can be 50% smaller than JPEG and 20-30% smaller than WebP. AVIF uses advanced compression techniques, such as AV1's inter- and intra-frame coding, to reduce redundancy and compress images.

https://caniuse.com/avif

#### Extra information, such as Shutter version, operating system and ideas for how to implement:
Arch Linux

**Comment by Photon89** [comment]
Hi, thanks for your request! I added the AVIF support in #691, please test!
