### ISSUE TITLE
Barcode/QR reader functionality

### ISSUE THREAD

**Issue by ghost** [shutter-project/shutter#705]
#### Description of requested feature:
Barcode/QR reader functionality where you select the area and it decodes the image on screen.

#### Reasons for adding feature:
Ease of use so users don't have to use a secondary program to do it increasing workflow.

#### Extra information, such as Shutter version, operating system and ideas for how to implement:
None

**Comment by vadi2** [comment]
Unfortunately I believe this would be scope creep for Shutter and would put it down towards a bad path.

**Comment by Photon89** [comment]
Agreed. Proposing to close.
