### ISSUE TITLE
shutter won't edit screenshots

### ISSUE THREAD

**Issue by martinkg** [shutter-project/shutter#714]
#### Brief summary of issue
shutter won't edit screenshots on Fedora 41

#### Steps to reproduce the issue

1. Take screenshot.
2. Select it.
3. Click Edit

Actual Results:  
Nothing happens.

#### Error output
When opening shutter from terminal, it prints this when clicking Edit:

*** unhandled exception in callback:
***   Couldn’t recognize the image file format for file “/usr/share/shutter/resources/icons/drawing_tool/cursor/arrow” at /usr/lib64/perl5/vendor_perl/Glib/Object/Introspection.pm line 67.
***  ignoring at /usr/lib64/perl5/vendor_perl/Glib/Object/Introspection.pm line 67.
 at /usr/bin/shutter line 11031.

#### Extra information, such as Shutter version, display server in use (Xorg or Wayland), operating system and ideas for how to solve: version shutter-0.99.5 with Wayland
Problem does' nt exists on Fedora 40

[Bugzilla Report](https://bugzilla.redhat.com/show_bug.cgi?id=2323682)

**Comment by Photon89** [comment]
Could you please check whether /usr/share/shutter/resources/icons/drawing_tool/cursor/arrow exists and is an image which can be viewed?

**Comment by yajo** [comment]
It looks like it's a text file, not image:
![image](https://github.com/user-attachments/assets/d06844cb-cfed-4a39-b01e-8c1884fb45ef)

**Comment by DarthGandalf** [comment]
That's actually how XPM format looks like. Maybe somehow your system lost ability to read XPM files? E.g. https://packages.ubuntu.com/focal/libxpm4 missing? (no idea what would be the Fedora analog of this)

**Comment by yajo** [comment]
AFAICS it's installed:

```
$ dnf info libXpm
Updating and loading repositories:
Repositories loaded.
Installed packages
Name            : libXpm
Epoch           : 0
Version         : 3.5.17
Release         : 4.fc41
Architecture    : x86_64
Installed size  : 148.4 KiB
Source          : libXpm-3.5.17-4.fc41.src.rpm
From repository : fedora
Summary         : X.Org X11 libXpm runtime library
URL             : http://www.x.org
License         : MIT AND X11-distribute-modifications-variant
Description     : X.Org X11 libXpm runtime library
Vendor          : Fedora Project

Available packages
Name           : libXpm
Epoch          : 0
Version        : 3.5.17
Release        : 4.fc41
Architecture   : i686
Download size  : 67.7 KiB
Installed size : 151.7 KiB
Source         : libXpm-3.5.17-4.fc41.src.rpm
Repository     : fedora
Summary        : X.Org X11 libXpm runtime library
URL            : http://www.x.org
License        : MIT AND X11-distribute-modifications-variant
Description    : X.Org X11 libXpm runtime library
Vendor         : Fedora Project

$ sudo dnf install libXpm
Updating and loading repositories:
 Fedora 41 - x86_64 - Updates           100% |  61.5 KiB/s |  24.1 KiB |  00m00s
 RPM Fusion for Fedora 41 - Free - Upda 100% |  15.5 KiB/s |   7.8 KiB |  00m01s
 RPM Fusion for Fedora 41 - Nonfree - U 100% |  16.0 KiB/s |   7.9 KiB |  00m00s
 RPM Fusion for Fedora 41 - Nonfree - S 100% |  17.8 KiB/s |   7.3 KiB |  00m00s
 Copr repo for PyCharm owned by phracek 100% |   3.0 KiB/s |   1.8 KiB |  00m01s
 google-chrome                          100% |  12.3 KiB/s |   1.3 KiB |  00m00s
 RPM Fusion for Fedora 41 - Nonfree - N 100% |  16.1 KiB/s |   8.2 KiB |  00m01s
 Fedora 41 - x86_64 - Updates           100% |   1.7 MiB/s |   2.1 MiB |  00m01s
 RPM Fusion for Fedora 41 - Free - Upda 100% |  22.5 KiB/s |  17.2 KiB |  00m01s
 RPM Fusion for Fedora 41 - Nonfree - U 100% |  24.8 KiB/s |  23.0 KiB |  00m01s
 google-chrome                          100% |  13.6 KiB/s |   3.3 KiB |  00m00s
 RPM Fusion for Fedora 41 - Nonfree - N 100% |  23.2 KiB/s |  17.2 KiB |  00m01s
Repositories loaded.
Package "libXpm-3.5.17-4.fc41.x86_64" is already installed.

Nothing to do.

**Comment by Photon89** [comment]
Not sure if we can do anything about it here, besides of a better error handling. But the original issue is somewhere in this libxpm library which seems to be installed but dysfunctional.

**Comment by DarthGandalf** [comment]
Potentially somehow gdk-pixbuf forgot how to use libxpm.

**Comment by martinkg** [comment]
I have installed a older version of gdk-pixbuf2 from Fedora40 for my Fedora41, and i can edit the screenshots again.

gdk-pixbuf2-2.42.10-8.fc40.x86_64.rpm
gdk-pixbuf2-devel-2.42.10-8.fc40.x86_64.rpm
gdk-pixbuf2-modules-2.42.10-8.fc40.x86_64.rpm

root@fc41:/tmp# **rpm -Uvh gdk-pixbuf2-* --force**
Will be checked ...                ################################# [100%]
Prepare ...                              ################################# [100%]
Update/ Installation ...
   1:gdk-pixbuf2-2.42.10-8.fc40       ################################# [ 17%]
   2:gdk-pixbuf2-devel-2.42.10-8.fc40 ################################# [ 33%]
   3:gdk-pixbuf2-modules-2.42.10-8.fc4################################# [ 50%]
Clean up/ remove ...
   4:gdk-pixbuf2-modules-2.42.11-1.fc4################################# [ 67%]
   5:gdk-pixbuf2-devel-2.42.11-1.fc41 ################################# [ 83%]
   6:gdk-pixbuf2-2.42.11-1.fc41       ################################# [100%]

**Comment by lefred** [comment]
On Fedora 41, you need to install gdk-pixbuf2-modules-extra.
This package should become a dependency of shutter's rpm on Fedora 41.

From the package's information:
_This package contains modules for loading ANI, BMP, ICNS, ICO, PNM, QTIF,
TGA, XBM, and XPM images,_

**Comment by martinkg** [comment]
> On Fedora 41, you need to install gdk-pixbuf2-modules-extra. This package should become a dependency of shutter's rpm on Fedora 41.
> 
> From the package's information: _This package contains modules for loading ANI, BMP, ICNS, ICO, PNM, QTIF, TGA, XBM, and XPM images,_

@lefred great, then I'll build a new shutter package with the dependencies for fc41 right away.

**Comment by martinkg** [comment]
it's a packaging problem, ticket can be closed.

**Comment by Photon89** [comment]
Great, thanks for taking care of it!

**Comment by Photon89** [comment]
@martinkg You bumped the version to 0.99.6 though which isn't released yet. :smiley:
