### ISSUE TITLE
hotkey

### ISSUE THREAD

**Issue by badabing2** [shutter-project/shutter#715]
looking for hotkeys for shutter (and thanks!)

**Comment by DarthGandalf** [comment]
please state your question in form of a question

**Comment by Photon89** [comment]
See also #319 and #499.

**Comment by DarthGandalf** [comment]
like in https://shutter-project.org/faq-help/set-shutter-as-the-default-screenshot-tool ?

Btw, when you **edit** the post, there's no notification, I've noticed your edit only accidentally
